using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
internal static class AiToolTests {
 static void Check(bool value,string reason){if(!value)throw new Exception(reason);}
 static byte[] ReferenceFixture(string weapon,int offset=0){
  using(var bytes=new MemoryStream()){
   using(var zip=new System.IO.Compression.ZipArchive(bytes,System.IO.Compression.ZipArchiveMode.Create,true)){
    Action<string,string> part=(path,xml)=>{using(var writer=new StreamWriter(zip.CreateEntry(path).Open()))writer.Write(xml);};
    string ns="http://schemas.openxmlformats.org/spreadsheetml/2006/main";
    part("xl/sharedStrings.xml","<sst xmlns='"+ns+"'/>");
    part("xl/styles.xml","<styleSheet xmlns='"+ns+"'><fonts><font/></fonts><cellXfs><xf fontId='0'/></cellXfs></styleSheet>");
    part("xl/workbook.xml","<workbook xmlns='"+ns+"' xmlns:r='http://schemas.openxmlformats.org/officeDocument/2006/relationships'><sheets><sheet name='이정도면잘키웠다' r:id='a'/><sheet name='올인원 준종결표' r:id='b'/></sheets></workbook>");
    part("xl/_rels/workbook.xml.rels","<Relationships><Relationship Id='a' Target='worksheets/a.xml'/><Relationship Id='b' Target='worksheets/b.xml'/></Relationships>");
    Func<string,string,string> cell=(address,value)=>"<c r='"+address+"' t='inlineStr'><is><t>"+value+"</t></is></c>";
    string rows="<row>"+cell("A2","캐릭터")+cell("B2","무기")+cell("C2","성유물")+"</row>";
    for(int i=0;i<30;i++){int row=5+i+offset;rows+="<row>"+cell("A"+row,"시험"+(char)('가'+i))+cell("B"+row,weapon)+cell("C"+row,"세트")+"</row>";}
    string sheet="<worksheet xmlns='"+ns+"'><sheetData>"+rows+"</sheetData></worksheet>";part("xl/worksheets/a.xml",sheet);part("xl/worksheets/b.xml",sheet);
   }return bytes.ToArray();
  }
 }
 static void VerifyBuildReferences(string root){
  string cache=Path.Combine(root,"references");int downloads=0;
  var first=BuildReferences.Load(cache,false,()=>{downloads++;return ReferenceFixture("첫 무기");});
  Check(first.Error==null&&first.Sheets.Count==2&&first.Sheets.All(s=>s.Characters.Count==30),"Both source tabs are parsed without a character-specific table");
  var cached=BuildReferences.Load(cache,false,()=>{downloads++;throw new IOException();});Check(downloads==1&&cached.Hash==first.Hash,"Fresh source cache performs no network request");
  var revised=BuildReferences.Load(cache,true,()=>ReferenceFixture("새 무기",3));Check(revised.Hash!=first.Hash&&revised.Sheets[0].Characters[0].First==8&&revised.Sheets[0].Characters[0].Rows[0].Values["무기"]=="새 무기","Source edits and inserted rows replace derived cache automatically");
  var failed=BuildReferences.Load(cache,true,()=>new byte[]{1,2,3});Check(failed.Error!=null&&failed.Hash==revised.Hash&&failed.FetchedUtc==revised.FetchedUtc&&failed.Sheets.Count==2,"Malformed update preserves last good source and its date");
  BuildReferences.Load(cache,false,()=>{downloads++;throw new IOException();});Check(downloads==1,"Failed source refresh backs off instead of repeated downloads");
  var artifact=CatheryneTools.Json().Deserialize<Dictionary<string,object>>(@"{""rarity"":5,""level"":20,""mainStatKey"":""critRate_"",""substats"":[{""key"":""critRate_"",""value"":8.6},{""key"":""critDMG_"",""value"":7.8},{""key"":""atk_"",""value"":5.8},{""key"":""eleMas"",""value"":23}]}");
  var score=BuildAnalysis.Score(artifact,new[]{"critRate_"});Check(score.Status=="calculated"&&score.CritValue==25&&score.RollMinimum==520&&score.UsefulMinimum==220,"CV excludes main stat and RV honors upstream float corrections and selected useful stats: "+CatheryneTools.Json().Serialize(score));
  artifact["substats"]=null;Check(!BuildAnalysis.Score(artifact,new string[0]).CritValue.HasValue,"Uncollected artifact stats cannot become zero scores");
 }
 static void VerifyGameCheckpoint(){
  var request=CatheryneTools.Json().Deserialize<Dictionary<string,object>>(@"{""task_id"":""task"",""frame_id"":""frame"",""mode"":""navigation"",""evidence"":""clear path"",""previous_result"":{""outcome"":""success"",""evidence"":""arrived""},""execution"":{""command"":""delegate"",""parameters"":{""groups"":[""fixture""],""intent"":""follow route"",""expected"":""destination""}}}");
  var order=new List<string>();
  Func<string,Dictionary<string,object>,object> record=(command,args)=>{order.Add(command);Check(CodexChat.S(args,"task_id")=="task"&&CodexChat.S(args,"frame_id")=="frame","Checkpoint keeps one task and observation");Check(!args.ContainsKey("previous_result")&&!args.ContainsKey("execution"),"Composition does not leak into domain commands");return command;};
  Check(Equals(GameTools.RegisterAndExecute(request,record),"delegate")&&order.SequenceEqual(new[]{"result","register","delegate"}),"Verify result before changing state and dispatching the existing executor");
  var execution=CodexChat.Map(request["execution"]);var parameters=CodexChat.Map(execution["parameters"]);Check(!parameters.ContainsKey("task_id"),"Composition preserves caller parameters");
  order.Clear();bool failed=false;try{GameTools.RegisterAndExecute(request,(command,args)=>{order.Add(command);throw new InvalidOperationException("fixture result rejected");});}catch(InvalidOperationException){failed=true;}Check(failed&&order.SequenceEqual(new[]{"result"}),"Rejected result prevents state change and input");
  order.Clear();parameters["task_id"]="other";failed=false;try{GameTools.RegisterAndExecute(request,record);}catch(ArgumentException){failed=true;}Check(failed&&order.Count==0,"Foreign task is rejected before any mutation");parameters.Remove("task_id");
  CodexChat.Map(request["previous_result"])["outcome"]="unknown";failed=false;try{GameTools.RegisterAndExecute(request,record);}catch(ArgumentException){failed=true;}Check(failed&&order.Count==0,"Unknown outcome cannot advance a checkpoint");
  request.Remove("previous_result");request["mode"]="dialogue";failed=false;try{GameTools.RegisterAndExecute(request,record);}catch(ArgumentException){failed=true;}Check(failed&&order.Count==0,"Auto dialogue cannot dispatch a competing executor");
  request.Remove("execution");GameTools.RegisterAndExecute(request,record);Check(order.SequenceEqual(new[]{"register"}),"Dialogue uses canonical registration only");
 }
 internal static void Run(){
  string root=Path.Combine(Path.GetTempPath(),"catheryne-ai-test-"+Guid.NewGuid().ToString("N"));Directory.CreateDirectory(root);
  try{
   Check(!AiWorkspacePanel.HasConversation(null)&&!AiWorkspacePanel.HasConversation(new AiTaskRecord{Thread=""})&&!AiWorkspacePanel.HasConversation(new AiTaskRecord{Thread="mcp-session"}),"Non-conversation tasks route to work records");
   Check(AiWorkspacePanel.HasConversation(new AiTaskRecord{Thread="00000000-0000-7000-8000-000000000001"}),"Codex conversation task keeps its chat destination");
   VerifyGameCheckpoint();ChatText.Test();AiTaskCard.Test();TaskProgress.StoreTest(Path.Combine(root,"progress-store"));
   var planned=new AiTaskRecord{Id="planned",Title="Goal",Plan=new[]{"Reach destination","Finish conversation"}};var canonicalPlan=CodexChat.Map(CatheryneTools.Json().DeserializeObject(CatheryneTools.Json().Serialize(GameTools.BuildPlan(planned))));Check(CodexChat.Items(canonicalPlan["steps"]).Select(step=>CodexChat.S(step,"title")).SequenceEqual(planned.Plan)&&GameTools.StageId(planned,1)=="step-2"&&GameTools.StageId(new AiTaskRecord(),0)=="task","Registered work order is projected into the canonical game plan, including legacy single-stage IDs");
   var requestGroup=new AiTaskRequest(new AiTaskRecord{Id="settings-a",TurnId="request-one",State="completed",Tool="catheryne_launcher",Title="FPS"});requestGroup.Update(new AiTaskRecord{Id="settings-b",TurnId="request-one",State="running",Tool="catheryne_launcher",Title="Display"});Check(requestGroup.Operations.Count()==2&&requestGroup.Summary().State=="running"&&requestGroup.Theme()=="설정 변경","One user request groups multiple operations without premature completion");requestGroup.Update(new AiTaskRecord{Id="settings-b",TurnId="request-one",State="failed",Tool="catheryne_launcher",Title="Display"});Check(requestGroup.Summary().State=="failed"&&AiTaskRequest.KeyFor(new AiTaskRecord{Id="next",TurnId="request-two"})!=requestGroup.Key,"Failure is visible and the next user request has its own card");
   var feed=new AiTaskFeed(root,"feed-thread");feed.Bind("first","task");feed.Bind("after",null);feed.Bind("first","other");string owner;
   var reopenedFeed=new AiTaskFeed(root,"feed-thread");Check(reopenedFeed.TryOwner("first",out owner)&&owner=="task"&&reopenedFeed.TryOwner("after",out owner)&&owner=="","Task item ownership including post-task chat survives reopening without reassignment");
   Check(!new AiTaskFeed(root,"other-thread").TryOwner("first",out owner),"Task feed isolation between conversations");
   var span=new AiTaskRecord{Id="task",State="completed",Started="2030-01-01T00:00:00Z",Ended="2030-01-01T00:01:00Z"};Check(AiTaskFeed.OwnerAt(new[]{span},DateTimeOffset.Parse("2030-01-01T00:00:30Z"))=="task"&&AiTaskFeed.OwnerAt(new[]{span},DateTimeOffset.Parse(span.Ended))==null&&AiTaskFeed.OwnerAt(new[]{span},null)==null,"Restored task boundaries exclude post-completion and unknown-time messages");
   var storySummary=new AiTaskRequest(new AiTaskRecord{Id="parent-story",Action="game_control",State="completed",Title="Story",Reason="Verified completion"});
   storySummary.Update(new AiTaskRecord{Id="failed-route",ParentTaskId="parent-story",State="failed",Reason="Blocked route"});
   Check(storySummary.Summary().State=="completed"&&storySummary.Summary().Reason=="Verified completion"&&storySummary.Operations.Count()==2,"Recovered child failure stays in history without overriding verified parent completion");
   storySummary.Update(new AiTaskRecord{Id="failed-route",ParentTaskId="parent-story",State="blocked"});Check(!storySummary.StatusOperations.Any(AiTaskFeed.Open),"Handled child blockage does not hold the parent card open");
   storySummary.Update(new AiTaskRecord{Id="failed-route",ParentTaskId="parent-story",State="running"});Check(storySummary.Summary().State=="running","Still-running child remains visible even if parent was incorrectly marked complete");
   string fightUser=Path.Combine(root,"fight-strategy"),fightFolder=Path.Combine(fightUser,"AutoFight");Directory.CreateDirectory(fightFolder);
   AtomicFile.Write(Path.Combine(fightUser,"config.json"),"{\"autoFightConfig\":{\"strategyName\":\"selected\"}}");
   bool missingFight=false;try{ExternalTools.ReadCombatStrategyPath(fightUser);}catch(InvalidOperationException){missingFight=true;}Check(missingFight,"Missing selected combat strategy fails before execution");
   File.WriteAllText(Path.Combine(fightFolder,"selected.txt"),"rotation");Check(ExternalTools.ReadCombatStrategyPath(fightUser)==Path.Combine(fightFolder,"selected.txt"),"Existing text combat strategy is used");
   File.WriteAllText(Path.Combine(fightFolder,"selected.json"),"{}");Check(ExternalTools.ReadCombatStrategyPath(fightUser)==Path.Combine(fightFolder,"selected.json"),"Official JSON precedence is preserved for combat strategies");
   AtomicFile.Write(Path.Combine(fightUser,"config.json"),"{\"autoFightConfig\":{\"strategyName\":\"根据队伍自动选择\"}}");Check(ExternalTools.ReadCombatStrategyPath(fightUser)==fightFolder+Path.DirectorySeparatorChar,"Party recognition keeps the official directory strategy");
   AtomicFile.Write(Path.Combine(fightUser,"config.json"),"{\"autoFightConfig\":{\"strategyName\":\"missing\"},\"autoBossConfig\":{\"strategyName\":\"selected\"}}");
   Check(ExternalTools.ReadCombatStrategyPath(fightUser,"autoBossConfig")==Path.Combine(fightFolder,"selected.json"),"Boss uses its selected strategy rather than unrelated general combat settings");
   VerifyBuildReferences(root);CharacterBuildTests.Run(root);BuildReviewTests.Run(root);
   string cardUser=Path.Combine(root,"card-strategy"),cardFolder=Path.Combine(cardUser,"AutoGeniusInvokation");Directory.CreateDirectory(cardFolder);
   AtomicFile.Write(Path.Combine(cardUser,"config.json"),"{\"autoGeniusInvokationConfig\":{\"strategyName\":\"selected\"}}");
   bool missingCard=false;try{ExternalTools.ReadCardStrategy(cardUser);}catch(InvalidOperationException){missingCard=true;}Check(missingCard,"Missing card strategy cannot silently complete");
   File.WriteAllText(Path.Combine(cardFolder,"selected.txt")," \r\n");bool emptyCard=false;try{ExternalTools.ReadCardStrategy(cardUser);}catch(InvalidOperationException){emptyCard=true;}Check(emptyCard,"Empty card strategy cannot silently complete");
   string cardContent="deck strategy\r\n\"quoted\" 한국어";File.WriteAllText(Path.Combine(cardFolder,"selected.txt"),cardContent);Check(ExternalTools.ReadCardStrategy(cardUser)==cardContent,"Selected card strategy contents are preserved");
   AtomicFile.Write(Path.Combine(cardUser,"config.json"),"{\"autoGeniusInvokationConfig\":{\"strategyName\":\"../outside\"}}");bool outsideCard=false;try{ExternalTools.ReadCardStrategy(cardUser);}catch(InvalidOperationException){outsideCard=true;}Check(outsideCard,"Card strategy stays within its official directory");
   string attachment=Path.Combine(root,"attachment.txt");File.WriteAllText(attachment,"test content");
   var prepared=CodexChat.PrepareInput("Attached file: literal\nuser text",new[]{attachment});
   var inputView=CodexChat.ReadUserContent(prepared);
   var restoredView=CodexChat.ReadUserContent(CatheryneTools.Json().DeserializeObject(CatheryneTools.Json().Serialize(prepared)));
   Check(inputView.Text=="Attached file: literal\nuser text"&&inputView.Files.SequenceEqual(new[]{"attachment.txt"})&&restoredView.Text==inputView.Text&&restoredView.Files.SequenceEqual(inputView.Files),"Attachment display is identical before send and after history restore; literal first-part text stays text");
   Check(CodexChat.S(CodexChat.Items(prepared).Last(),"text").EndsWith("test content"),"Attachment body still reaches the model");
   File.WriteAllText(attachment,new string('x',512001));bool oversized=false;try{CodexChat.PrepareInput("test",new[]{attachment});}catch(InvalidOperationException){oversized=true;}Check(oversized,"Oversized text rejected before starting a conversation");
   bool missing=false;try{CodexChat.PrepareInput("test",new[]{Path.Combine(root,"missing.png")});}catch(FileNotFoundException){missing=true;}Check(missing,"Missing image rejected before starting a conversation");

   var history=new List<Dictionary<string,object>>{new Dictionary<string,object>{{"id","reopened"},{"recencyAt",10},{"updatedAt",900}},new Dictionary<string,object>{{"id","recent-message"},{"recencyAt",20},{"updatedAt",20}},new Dictionary<string,object>{{"id","legacy"},{"updatedAt",15}}};
   Check(CodexChat.SortHistory(history).Select(t=>CodexChat.S(t,"id")).SequenceEqual(new[]{"recent-message","legacy","reopened"}),"Opening old chat does not outrank recent conversation; old runtimes retain fallback");
   var feedStore=new AiTaskStore(root);var feedTask=feedStore.Begin("feed","thread","request","test");var initial=feedStore.Changes(0);Check(initial.Count==1,"Task feed initial snapshot");long cursor=initial[0].Key;Check(feedStore.Changes(cursor).Count==0,"Unchanged task feed must not reread records");feedStore.End(feedTask,"completed","done");var delta=feedStore.Changes(cursor);Check(delta.Count==1&&delta[0].Value.State=="completed"&&delta[0].Key>cursor,"Task feed receives completion");Check(feedStore.Changes(0).Count==1,"Task feed restart restores only latest versions");
   var late=feedStore.Find(feedTask.Id);late.State="running";late.Reason="late progress";feedStore.Save(late);Check(late.State=="completed"&&late.Reason=="done","Late progress cannot reopen completed work");
   var preparing=feedStore.Begin("preparing","test-thread","preparing-request","catheryne_request");preparing.Action="game_control";feedStore.Save(preparing);new GameTools(root).Run("stop",new Dictionary<string,object>{{"task_id",preparing.Id}},"test-thread",null);Check(feedStore.Find(preparing.Id).State=="cancelled","Game startup can be cancelled before a host connection exists");
   var plannedTask=feedStore.Begin("plan","thread","plan-request","test");var oldProgress=feedStore.Find(plannedTask.Id);plannedTask.ExecutionPlan=new{projects=new[]{new{name="route"}}};feedStore.Save(plannedTask);oldProgress.Reason="progress";feedStore.Save(oldProgress);Check(CatheryneTools.Json().Serialize(feedStore.Find(plannedTask.Id).ExecutionPlan)==CatheryneTools.Json().Serialize(plannedTask.ExecutionPlan),"Late progress preserves the persisted execution plan");feedStore.End(oldProgress,"completed","executor finished");Check(feedStore.Find(plannedTask.Id).ExecutionPlan!=null,"Finished execution retains its plan for history");
   var cancelTask=feedStore.Begin("cancel","thread","cancel-request","test");var stale=feedStore.Find(cancelTask.Id);feedStore.RequestCancellation(cancelTask.Id);stale.Reason="late update";feedStore.Save(stale);Check(stale.CancelRequested,"Cancellation survives stale progress writes");feedStore.End(stale,"completed","late success");Check(stale.State=="cancelled","Cancellation before result cannot become success");
   using(GameInputLease.Acquire(root,false)){bool collision=false;try{using(GameInputLease.Acquire(root,false)){} }catch(InvalidOperationException){collision=true;}Check(collision,"One application input lease rejects competing executors");}using(GameInputLease.Acquire(root,false)){}
   feedTask=feedStore.Begin("attention","thread","attention-request","test");feedStore.End(feedTask,"blocked","needs game");Check(AiTaskStore.NeedsAttention(feedTask,feedStore.ReadAttention()),"Blocked task needs attention");feedStore.DismissAttention(feedTask);var notices=new AiTaskStore(root).ReadAttention();Check(!AiTaskStore.NeedsAttention(feedTask,notices)&&feedStore.Find(feedTask.Id).State=="blocked","Notice dismissal persists without cancelling task");feedStore.End(feedTask,"blocked","needs login");Check(AiTaskStore.NeedsAttention(feedTask,notices),"New blocker not suppressed by old dismissal");feedStore.DismissAttention(feedTask);feedStore.End(feedTask,"completed","done");Check(!AiTaskStore.NeedsAttention(feedTask,feedStore.ReadAttention()),"Resolved task does not alert");
   using(var chat=new CodexChat(root)){chat.ThreadId="test-thread";var item=new Dictionary<string,object>{{"id","message-1"}};Check(!chat.MessageTime(item).HasValue,"Unknown historical time must remain unknown");var first=chat.MessageTime(item,true);Check(first.HasValue&&chat.MessageTime(item,true)==first,"Repeated message events retain the first observation");using(var reopened=new CodexChat(root)){reopened.ThreadId=chat.ThreadId;var restored=reopened.MessageTime(item);Check(restored.HasValue&&Math.Abs((restored.Value-first.Value).TotalSeconds)<1,"Message timestamp survives reopening");reopened.ThreadId="other-thread";Check(!reopened.MessageTime(item).HasValue,"Message timestamps cannot leak across threads");}Check(chat.MessageTime(new Dictionary<string,object>{{"createdAt",0}}).Value.Year==1970,"Provider timestamp takes precedence");chat.MessageTime(new Dictionary<string,object>{{"id","dated-message"},{"createdAt",946684800}},true);using(var reopened=new CodexChat(root)){reopened.ThreadId=chat.ThreadId;Check(reopened.MessageTime(new Dictionary<string,object>{{"id","dated-message"}}).Value.Year==2000,"Provider event time persists even if history omits it");}Check(!chat.MessageTime(new Dictionary<string,object>{{"createdAt","NaN"}}).HasValue,"Invalid epoch is ignored");}

   Check(GameTools.MatchesAspect(1920,1080,16,9)&&GameTools.MatchesAspect(1280,720,16,9)&&!GameTools.MatchesAspect(3440,1440,16,9)&&!GameTools.MatchesAspect(1920,0,16,9),"Unsupported capture aspect must be rejected before automation starts");
   Check(HutaoPipe.Hash(new byte[0])==0xef46db3751d8e999UL,"Hutao XXHash64 empty vector");
   Check(HutaoPipe.Hash(System.Text.Encoding.UTF8.GetBytes("hello"))==0x26c7827d889f6da3UL,"Hutao XXHash64 payload vector");
   var routeProject=new Dictionary<string,object>{{"type","Pathing"},{"name","route.json"},{"folderName","test"},{"index",9}};
   var routeBundle=ExternalTools.Bundle("route:test",new object[]{routeProject});
   var fightBundle=ExternalTools.Bundle("combat:auto",new object[]{new{type="Javascript",name="combat",folderName="Catheryne-Combat"}});
   var plannedRoute=CatheryneTools.Json().Deserialize<Dictionary<string,object>>("{\"title\":\"fixture\",\"evidence\":\"mapped fixture coordinates\",\"positions\":[{\"x\":1,\"y\":2,\"type\":\"teleport\",\"move_mode\":\"walk\"},{\"x\":3,\"y\":4,\"type\":\"target\",\"move_mode\":\"walk\"}]}");
   var routeProjection=ExternalTools.ValidateRoute(plannedRoute);Check(CodexChat.Items(routeProjection["positions"]).Count()==2,"Route retains ordered warp and destination");
   var routePoint=CodexChat.Items(plannedRoute["positions"]).Last();routePoint["action"]="fight";bool routeRejected=false;try{ExternalTools.ValidateRoute(plannedRoute);}catch(ArgumentException){routeRejected=true;}Check(routeRejected,"Navigation cannot smuggle unrelated actions");routePoint.Remove("action");routePoint["x"]=double.NaN;routeRejected=false;try{ExternalTools.ValidateRoute(plannedRoute);}catch(ArgumentException){routeRejected=true;}Check(routeRejected,"Navigation rejects nonfinite coordinates");
   Check(ExternalTools.ObservationOnly(new[]{"position:map_center"})&&ExternalTools.ObservationOnly(new[]{"position:current"}),"Reviewed position queries are observation-only");
   Check(!ExternalTools.ObservationOnly(new[]{"position:map_center","combat:auto"})&&!ExternalTools.ObservationOnly(new[]{"saved-group"})&&!ExternalTools.ObservationOnly(new string[0]),"Mixed and user groups cannot claim paused observation permission");
   var dialogueBundle=ExternalTools.Bundle("dialogue:auto",new object[]{new{type="Javascript",folderName="Catheryne-Dialogue"}});
   Check(ExternalTools.RequiredHeight(ExternalTools.ComposeBundle("route-with-fight",new[]{routeBundle,fightBundle}))==DisplayPresets.AiHeight,"Mixed automation inherits the route's minimum viewport");
   Check(ExternalTools.RequiredHeight(dialogueBundle["definition"])==0&&ExternalTools.RequiredHeight(null)==0,"Dialogue and unconfigured tasks do not acquire a navigation-only resolution requirement");
   Check(ExternalTools.RequiredHeight(ExternalTools.Bundle("position:current",new object[]{new{type="Javascript",folderName=ExternalTools.BuiltinFolder("position:current")}})["definition"])==DisplayPresets.AiHeight,"Current position shares the map recognition viewport requirement");
   Check(CodexChat.Items(ExternalTools.ComposeBundle("dialogue-only",new[]{dialogueBundle})["projects"]).Count()==1,"State-bound dialogue remains executable alone");
   bool continuousBlocked=false;try{ExternalTools.ComposeBundle("never-finishes",new[]{dialogueBundle,routeBundle});}catch(ArgumentException){continuousBlocked=true;}Check(continuousBlocked,"Continuous dialogue cannot silently block later bundled work");
   var searchableGroup=ExternalTools.RouteBundle("이동 경로.json",new Dictionary<string,object>{{"info",new Dictionary<string,object>{{"description","Mondstadt statue"}}},{"positions",new object[0]}});
   Check(ExternalTools.GroupMatches(searchableGroup,"mondstadt 이동")&&!ExternalTools.GroupMatches(searchableGroup,"Liyue"),"Automation search combines localized title and route metadata without returning unrelated routes");
   var composed=ExternalTools.ComposeBundle("test",new[]{routeBundle,fightBundle});var projects=CodexChat.Items(composed["projects"]).ToArray();
   Check(projects.Length==2&&Convert.ToInt32(projects[0]["index"])==0&&Convert.ToInt32(projects[1]["index"])==1&&Convert.ToInt32(routeProject["index"])==9,"Ordered automation batches preserve source definitions and reindex derived execution");
   Check(CodexChat.Items(ExternalTools.ComposeBundle("standalone",new[]{ExternalTools.Bundle("saved",new object[]{new Dictionary<string,object>{{"type","Shell"},{"name","existing"}}})},true)["projects"]).Count()==1,"Existing standalone groups retain their supported project types");
   bool shellBlocked=false;try{ExternalTools.ComposeBundle("bad",new[]{ExternalTools.Bundle("shell",new object[]{new Dictionary<string,object>{{"type","Shell"}}})});}catch(ArgumentException){shellBlocked=true;}Check(shellBlocked,"Game delegation rejects shell projects");
   Check((string)ExternalTools.Value(new Dictionary<string,object>{{"name","group"}},"Name")=="group","BetterGI camel-case group names");
   var scriptResult=new Dictionary<string,object>{{"taskEnd",true},{"status",1}};
   var progress=new Dictionary<string,object>{{"endTime","2030-01-01T00:00:10Z"},{"history",new[]{scriptResult}},{"currentScriptGroupProjectInfo",scriptResult}};
   Check(ExternalTools.ExecutionState(progress)=="completed","Official script success finishes executor task");scriptResult["status"]=2;Check(ExternalTools.ExecutionState(progress)=="failed","Official script errors cannot become success");scriptResult["status"]=1;scriptResult["taskEnd"]=false;Check(ExternalTools.ExecutionState(progress)=="blocked","Partial script execution remains unverified");progress.Remove("endTime");Check(ExternalTools.ExecutionState(progress)=="running","Unfinished project without a group end remains running");
   scriptResult["taskEnd"]=true;scriptResult["status"]=2;Check(ExternalTools.ExecutionState(progress)=="failed","Failed project ends delegation even when BetterGI omits group endTime");
   progress["history"]=new object[0];Check(ExternalTools.ExecutionState(progress)=="failed","Current failed project is sufficient before history is flushed");
   scriptResult["status"]=1;progress["history"]=new[]{scriptResult};Check(ExternalTools.ExecutionState(progress)=="running","One successful project without group end cannot complete a multi-project bundle");
   scriptResult["status"]=2;scriptResult["taskEnd"]=false;Check(ExternalTools.ExecutionState(progress)=="running","Nonterminal status is not a failure receipt");
   string runtime=Path.Combine(root,"codex.exe");File.WriteAllText(runtime,"");Check(!CodexChat.RuntimeComplete(runtime),"Incomplete Codex runtime must not be selected");File.WriteAllText(Path.Combine(root,"codex-code-mode-host.exe"),"");Check(CodexChat.RuntimeComplete(runtime),"Complete Codex runtime is eligible");
   string newer=Path.Combine(root,"updated");Directory.CreateDirectory(newer);string latest=Path.Combine(newer,"codex.exe");File.WriteAllText(latest,"");File.SetLastWriteTimeUtc(latest,DateTime.UtcNow.AddMinutes(1));Check(CodexChat.SelectRuntime(new[]{runtime,latest})==runtime,"Partial update keeps complete runtime");File.WriteAllText(Path.Combine(newer,"codex-code-mode-host.exe"),"");Check(CodexChat.SelectRuntime(new[]{runtime,latest})==latest,"New complete runtime supersedes stale PATH");File.Delete(Path.Combine(newer,"codex-code-mode-host.exe"));Check(CodexChat.SelectRuntime(new[]{latest,runtime})==runtime,"Removed update helper falls back to complete installation");
   string job=CollectionScanner.Folder(root,Guid.NewGuid().ToString("N"));Directory.CreateDirectory(job);Check(CollectionScanner.Progress(job).Count==0,"Scanner startup without first status is pending, not failure");File.WriteAllText(Path.Combine(job,"status.json"),"{\"state\":\"completed\"}");File.WriteAllText(Path.Combine(job,"result.json"),"{\"format\":\"GOOD\",\"version\":3,\"characters\":[],\"weapons\":[]}");File.WriteAllText(Path.Combine(job,"stop"),"");bool cancelled=false;try{CollectionScanner.Complete(root,"account",job,0);}catch(OperationCanceledException){cancelled=true;}Check(cancelled&&!File.Exists(Path.Combine(root,"profiles/default/account/current.json")),"Cancelled scan cannot import even a completed result");File.Delete(Path.Combine(job,"stop"));bool failed=false;try{CollectionScanner.Complete(root,"account",job,1);}catch(InvalidOperationException){failed=true;}Check(failed,"Nonzero scanner exit cannot import output");CollectionScanner.Complete(root,"account",job,0);Check(File.Exists(Path.Combine(root,"profiles/default/account/current.json")),"Successful scanner result uses canonical account import");
   var journal=new Dictionary<string,object>();var observed=new List<string>();string[] refreshPlan={"characters","weapons","achievements"};bool interrupted=false;
   try{CollectionRefresh.Execute(refreshPlan,journal,()=>false,(area,index)=>{observed.Add(area);if(area=="weapons")throw new OperationCanceledException();},()=>{});}catch(OperationCanceledException){interrupted=true;}
   Check(interrupted&&Equals(journal["charactersDone"],true)&&!journal.ContainsKey("weaponsDone"),"Interrupted refresh commits only finished sections");observed.Clear();
   CollectionRefresh.Execute(refreshPlan,journal,()=>false,(area,index)=>observed.Add(area),()=>{});
   Check(observed.SequenceEqual(new[]{"weapons","achievements"}),"Resume skips committed sections and retries interrupted section");
   var dates=new Dictionary<string,object>{{"characters",DateTime.UtcNow.ToString("o")},{"weapons",DateTime.UtcNow.AddDays(-8).ToString("o")},{"artifacts",DateTime.UtcNow.ToString("o")}};
   Check(CollectionRefresh.Plan("auto",new CatheryneScanning.AccountScanOptions(),dates,DateTime.UtcNow).SequenceEqual(new[]{"weapons","materials","achievements"}),"Automatic selection respects freshness and missing sections");
   var fullScan=CatheryneScanning.AccountScanOptions.Read(new Dictionary<string,object>());
   Check(fullScan.Sections.Length==4&&Equals(fullScan.Coverage()["weapons"],"full"),"Default scope keeps full collection");
   var subset=CatheryneScanning.AccountScanOptions.Read(new Dictionary<string,object>{{"sections",new[]{"weapons"}},{"minimum_weapon_level",90}});
   var roundtrip=CatheryneScanning.AccountScanOptions.Read(CatheryneTools.Json().Deserialize<Dictionary<string,object>>(CatheryneTools.Json().Serialize(subset.Parameters())));
   Check(roundtrip.Sections.SequenceEqual(new[]{"weapons"})&&roundtrip.WeaponLevel==90&&Equals(roundtrip.Coverage()["weapons"],"partial")&&!roundtrip.Coverage().ContainsKey("artifacts"),"Filtered scan roundtrip never claims full or unselected coverage");
   foreach(var bad in new[]{new Dictionary<string,object>{{"sections",new string[0]}},new Dictionary<string,object>{{"sections",new[]{"unknown"}}},new Dictionary<string,object>{{"minimum_weapon_level",1.5}},new Dictionary<string,object>{{"minimum_artifact_level",21}}}){
    bool rejected=false;try{CatheryneScanning.AccountScanOptions.Read(bad);}catch(ArgumentException){rejected=true;}Check(rejected,"Invalid scan scope rejected before process launch");
   }
   var oldAccount=CatheryneTools.Json().Deserialize<Dictionary<string,object>>(@"{""weapons"":[{""key"":""DullBlade"",""level"":1},{""key"":""SilverSword"",""level"":20}],""artifacts"":[{""setKey"":""Adventurer"",""level"":0}],""characters"":[{""key"":""Amber"",""level"":20}]}");
   var incoming=CatheryneTools.Json().Deserialize<Dictionary<string,object>>(@"{""weapons"":[{""key"":""SilverSword"",""level"":20}]}");incoming["catheryne"]=new Dictionary<string,object>{{"coverage",subset.Coverage()}};
   oldAccount["format"]="GOOD";incoming["format"]="GOOD";var mergedScan=AccountMerge.Merge(oldAccount,incoming);
   Check(CodexChat.Items(mergedScan["weapons"]).Count()==2&&ReferenceEquals(oldAccount["artifacts"],mergedScan["artifacts"])&&ReferenceEquals(oldAccount["characters"],mergedScan["characters"]),"Partial scan keeps unseen equipment and omitted areas");
   var imageResult=new Dictionary<string,object>{{"frame_id","synthetic"},{"image_url","data:image/png;base64,AA=="}};
   var content=CatheryneTools.Json().Serialize(CodexChat.ToolContent(imageResult));Check(content.Contains("inputImage")&&content.Contains("imageUrl"),"Image must be a model-visible image item");Check(imageResult.ContainsKey("image_url"),"Formatting must not mutate domain result");
   var noteRoot=Path.Combine(root,"notes");var note=new Dictionary<string,object>{{"current_resin",123},{"max_resin",200},{"resin_recovery_time",600}};
   var resin=HoyoNotes.Save(noteRoot,"123456789","os_asia",note);
   Check(Equals(resin["current"],123)&&HoyoNotes.SavedStatus(noteRoot,"123456789","os_asia").Contains("123 / 200"),"AI and GUI read the same stored resin observation");
   Check(!HoyoNotes.SavedStatus(noteRoot,"123456789","os_usa").Contains("123 / 200")&&!HoyoNotes.SavedStatus(noteRoot,"987654321","os_asia").Contains("123 / 200"),"Resin observations cannot cross account or server");
   using(var notesDb=new LocalDataService(noteRoot)){Check(notesDb.Recent("123456789","daily-note").Count==1&&notesDb.Recent("123456789","resin").Count==1,"One refresh stores calendar source and resin projection together");}
   using(var unrelatedDb=new LocalDataService(root)){Check(unrelatedDb.Recent("123456789","daily-note").Count==0,"Observation respects caller storage root");}
   HoyoNotes.Save(noteRoot,"123456789","os_usa",new Dictionary<string,object>{{"current_resin",7},{"max_resin",200},{"resin_recovery_time",800}});
   var asiaNote=HoyoNotes.Latest(noteRoot,"123456789","os_asia");var usaNote=HoyoNotes.Latest(noteRoot,"123456789","os_usa");
   Check(Equals(((Dictionary<string,object>)asiaNote["value"])["current"],123)&&Equals(((Dictionary<string,object>)usaNote["value"])["current"],7),"A newer observation from another server never replaces the selected server's value");
   var calendarRoot=Path.Combine(root,"calendar-identities");
   var tower=new Dictionary<string,object>{{"id",0},{"type","ActTypeTower"},{"name","Tower"},{"start_timestamp","1893456000"},{"end_timestamp","1896134399"},{"is_finished",true}};
   var theater=new Dictionary<string,object>{{"id",0},{"type","ActTypeRoleCombat"},{"name","Theater"},{"start_timestamp","1893456000"},{"end_timestamp","1896134399"},{"is_finished",false}};
   using(var calendarDb=new LocalDataService(calendarRoot))calendarDb.Observe("","calendar:"+Locale.LanguageCode,new Dictionary<string,object>{{"fixed_act_list",new[]{tower,theater}}});
   var fixedEvents=new CalendarStore(calendarRoot).Read();
   using(var otherLanguageDb=new LocalDataService(calendarRoot))otherLanguageDb.Observe("","calendar:other-language",new Dictionary<string,object>{{"fixed_act_list",new object[0]}});
   Check(new CalendarStore(calendarRoot).Read().Count==fixedEvents.Count,"Other-language cache must not replace current calendar");
   Check(fixedEvents.Count==2&&fixedEvents.Select(x=>x.Id).Distinct().Count()==2&&fixedEvents.Single(x=>x.Title=="Tower").Done&&!fixedEvents.Single(x=>x.Title=="Theater").Done,"Fixed challenges sharing provider id zero retain separate identities and completion");
   string towerId=fixedEvents.Single(x=>x.Title=="Tower").Id;
   tower["name"]="Translated tower";
   using(var calendarDb=new LocalDataService(calendarRoot))calendarDb.Observe("","calendar:"+Locale.LanguageCode,new Dictionary<string,object>{{"fixed_act_list",new[]{theater,tower}}});
   Check(new CalendarStore(calendarRoot).Read().Single(x=>x.Title=="Translated tower").Id==towerId,"Calendar identity survives translated names and provider order changes");
   tower["start_timestamp"]="1896134400";tower["end_timestamp"]="1898553599";
   using(var calendarDb=new LocalDataService(calendarRoot))calendarDb.Observe("","calendar:"+Locale.LanguageCode,new Dictionary<string,object>{{"fixed_act_list",new[]{tower,theater}}});
   Check(new CalendarStore(calendarRoot).Read().Single(x=>x.Title=="Translated tower").Id!=towerId,"A new challenge period has a distinct identity");
   Check(CodexChat.CurrentInstructions().Contains(GameTools.Guide),"Existing chats receive current canonical game behavior on resume");
   var movingScene=new Dictionary<string,object>{{"mode","navigation"},{"paused",false}};Check(GameTools.RunInBackground(new Dictionary<string,object>(),movingScene),"Movement plans default to continuous background execution");Check(!GameTools.RunInBackground(new Dictionary<string,object>{{"background",false}},movingScene),"Explicit foreground mode is preserved");Check(!GameTools.RunInBackground(new Dictionary<string,object>(),new Dictionary<string,object>{{"mode","interaction"}}),"Direct interactions retain post-input observation by default");bool invalidBackground=false;try{GameTools.RunInBackground(new Dictionary<string,object>{{"background","true"}},movingScene);}catch(ArgumentException){invalidBackground=true;}Check(invalidBackground,"Invalid background flag cannot start input");
   var fullGameState=new Dictionary<string,object>{{"plan_id","test"},{"mode","dialogue"},{"owner","dialogue"},{"control","agent"},{"alert","focus_lost"},{"pending_result",new{intent="advance"}},{"plan_title","Repeated long title"},{"host_pid",42}};
   var modelGameState=(Dictionary<string,object>)GameTools.ModelReply(fullGameState);
   Check(!modelGameState.ContainsKey("plan_title")&&!modelGameState.ContainsKey("host_pid")&&Equals(modelGameState["alert"],"focus_lost")&&modelGameState.ContainsKey("pending_result")&&Equals(modelGameState["owner"],"dialogue")&&fullGameState.ContainsKey("plan_title"),"Model projection preserves control and pending evidence without mutating UI state");
   int postInputCaptures=0;var pendingInput=new Dictionary<string,object>{{"pending_result",new{intent="close menu"}}};
   var lostImage=GameTools.AfterInput(()=>{postInputCaptures++;throw new InvalidOperationException("window closed");},pendingInput);
   Check(postInputCaptures==1&&lostImage.ContainsKey("input_status")&&lostImage.ContainsKey("observation_error")&&!lostImage.ContainsKey("frame_id")&&!lostImage.ContainsKey("image_url"),"Dispatched input with lost window stays unverified without retry or stale frame");
   var preservedImage=GameTools.AfterInput(()=>new Dictionary<string,object>{{"frame_id","new-frame"},{"image_url","data:image/png;base64,AA=="}},pendingInput);
   Check(Equals(preservedImage["frame_id"],"new-frame")&&preservedImage.ContainsKey("input_status")&&!preservedImage.ContainsKey("observation_error"),"Successful post-input observation keeps its image and pending result");
   bool outside=false;try{GameTools.Coordinate(new Dictionary<string,object>{{"x",1280}},"x",1280);}catch(ArgumentException){outside=true;}Check(outside,"Out-of-frame clicks rejected");
   Check(AiWorkspacePanel.ContextPercent(null)==null,"No reported context is unknown");
   Check(AiWorkspacePanel.ContextPercent(new Dictionary<string,object>{{"modelContextWindow",1000},{"last",new Dictionary<string,object>{{"totalTokens",100}}},{"total",new Dictionary<string,object>{{"totalTokens",9000}}}})==10,"Context uses latest call, not cumulative account usage");
   var engine=Path.Combine(root,"engine.exe");var config=new Dictionary<string,object>(UnlockerOptions.Defaults());config["GamePath"]=Path.Combine(root,"GenshinImpact.exe");File.WriteAllText(Path.Combine(root,"fps_config.json"),CatheryneTools.Json().Serialize(config));File.WriteAllText(Path.Combine(root,"installation.json"),CatheryneTools.Json().Serialize(new{Engine=engine,Data=root}));
   var launcher=new LauncherOperations(root,()=>false);launcher.Apply("fps",100,false);Check(Convert.ToInt32(new ConfigStore(Path.Combine(root,"fps_config.json")).Read()["FPSTarget"])==100,"AI FPS uses canonical config");
   launcher.Apply("unlocker",0,false);Check(Equals(StoryClient.Read(Path.Combine(root,"launcher-settings.json"))["UseUnlockerLaunch"],false),"Unlocker preference persisted");
   bool guarded=false;try{new LauncherOperations(root,()=>true).Apply("fps",120,false);}catch(InvalidOperationException){guarded=true;}Check(guarded,"Running game blocks settings mutation");
   bool invalid=false;try{launcher.Apply("fps",0,false);}catch(ArgumentException){invalid=true;}Check(invalid&&Convert.ToInt32(new ConfigStore(Path.Combine(root,"fps_config.json")).Read()["FPSTarget"])==100,"Invalid setting preserves prior value");
   var tools=new CatheryneTools(root);var empty=CatheryneTools.Json().Serialize(tools.Context());Check(empty.Contains("\"total\":null"),"Missing inventory must remain unknown");Check(!empty.Contains("Cookie"),"No credentials in context");
   var goal=new Dictionary<string,object>{{"title","테스트 목표"},{"category","story"}};
   var a=(AiTaskRecord)tools.Run("catheryne_goal_add",goal,"synthetic","request1");Check(a.State=="completed","Goal mutation verified");tools.Run("catheryne_goal_add",goal,"synthetic","request1");Check(new GoalStore(root).Read().Goals.Count==1,"Duplicate call must not add a goal twice");
   foreach(var invalidPlan in new object[]{null,new string[0]}){bool rejected=false;int beforeCount=feedStore.List().Count;try{tools.Run("catheryne_request",new Dictionary<string,object>{{"title","계획 누락"},{"operation","story"},{"plan",invalidPlan}},"synthetic","invalid-plan");}catch(ArgumentException){rejected=true;}Check(rejected&&feedStore.List().Count==beforeCount,"Invalid story plan must fail before task creation or game startup");}
   bool missingPlan=false;try{tools.Run("catheryne_request",new Dictionary<string,object>{{"title","계획 누락"},{"operation","story"}},"synthetic","missing-plan");}catch(ArgumentException){missingPlan=true;}Check(missingPlan,"Story requires an explicit plan");
   var blocked=(AiTaskRecord)tools.Run("catheryne_request",new Dictionary<string,object>{{"title","게임 수행"},{"operation","story"},{"plan",new[]{"하위 임무 A","하위 임무 B"}}},"synthetic","request2");Check(blocked.State=="blocked","Missing game window must block execution");
   blocked.Operation=null;feedStore.Save(blocked); // Existing records predate the operation field.
   var retryArgs=new Dictionary<string,object>{{"title","게임 수행"},{"operation","story"},{"task_id",blocked.Id}};
   var retry=(AiTaskRecord)tools.Run("catheryne_request",retryArgs,"synthetic","retry1");Check(retry.Id==blocked.Id&&retry.Started==blocked.Started&&retry.State=="blocked","Prerequisite retry preserves the task and original timing");
   bool foreign=false;try{tools.Run("catheryne_request",retryArgs,"another-thread","retry2");}catch(InvalidOperationException){foreign=true;}Check(foreign,"Retry cannot take over another conversation task");
   int count=feedStore.List().Count;var sameTurn=new Dictionary<string,object>{{"title","동일 요청"},{"operation","story"},{"plan",new[]{"하위 임무 A","하위 임무 B"}}};
   var firstAttempt=(AiTaskRecord)tools.Run("catheryne_request",sameTurn,"synthetic","attempt1",null,"turn-retry");
   var nextAttempt=(AiTaskRecord)tools.Run("catheryne_request",sameTurn,"synthetic","attempt2",null,"turn-retry");
   Check(firstAttempt.Id==nextAttempt.Id&&feedStore.List().Count==count+1,"Same-turn prerequisite retry cannot leave an orphan card");
   feedStore.End(nextAttempt,"completed","verified fixture");
   Check(((AiTaskRecord)tools.Run("catheryne_request",sameTurn,"synthetic","attempt2",null,"turn-retry")).Id==nextAttempt.Id&&feedStore.List().Count==count+1,"Replayed retry call keeps the same completed task");
   sameTurn["task_id"]=nextAttempt.Id;
   Check(((AiTaskRecord)tools.Run("catheryne_request",sameTurn,"synthetic","attempt3",null,"turn-retry")).State=="completed","Repeated completed task must not restart game input");
   tools.Run("catheryne_control",new Dictionary<string,object>{{"target","stop"},{"task_id",blocked.Id}},"synthetic","request3");Check(new AiTaskStore(root).List().Single(t=>t.Id==blocked.Id).State=="cancelled","Cancel persists");
   tools.Run("catheryne_preferences",new Dictionary<string,object>{{"text","전투는 직접 수행"}},"synthetic","request4");Check(CatheryneTools.Json().Serialize(tools.Context()).Contains("전투는 직접 수행"),"Preference available on next query");
   var denied=(AiTaskRecord)tools.Run("catheryne_request",new Dictionary<string,object>{{"title","출석"},{"operation","daily_checkin"}},"synthetic","request5");Check(denied.State=="blocked"&&denied.Action=="hoyolab_login","Missing login produces typed login action, no network action");
   var store=new AiTaskStore(root);var unfinished=store.Begin("중단 복구","synthetic","request6","test");store.Recover();Check(store.List().Single(t=>t.Id==unfinished.Id).State=="running","Live task is not interrupted");unfinished.OwnerPid=int.MaxValue;using(var db=new LocalDataService(root))db.Observe("default","ai-task",unfinished);store.Recover();Check(store.List().Single(t=>t.Id==unfinished.Id).State=="interrupted","Unknown completion survives restart honestly");
   Func<string,Dictionary<string,object>,AiTaskRecord> execute=(action,args)=>(AiTaskRecord)tools.Run("catheryne_execute",new Dictionary<string,object>{{"action",action},{"parameters",args}},"synthetic",Guid.NewGuid().ToString("N"));
   var noLogin=execute("daily.configure",new Dictionary<string,object>{{"automaticCheckIn",true}});Check(noLogin.State=="blocked"&&noLogin.Action=="hoyolab_login","Automatic check-in exposes actual login prerequisite");
   var changed=execute("daily.configure",new Dictionary<string,object>{{"automaticCheckIn",false},{"resinThreshold",150},{"attendanceNotifications",true}});Check(changed.State=="completed"&&Convert.ToInt32(AppPreferences.Read(root)["resinThreshold"])==150,"Daily settings use canonical store");
   var invalidDaily=execute("daily.configure",new Dictionary<string,object>{{"resinThreshold",999},{"automaticCheckIn",false}});Check(invalidDaily.State=="failed"&&Convert.ToInt32(AppPreferences.Read(root)["resinThreshold"])==150,"Invalid daily settings do not partially mutate");
   Check(execute("goals.budget",new Dictionary<string,object>{{"amount",60}}).State=="completed"&&new GoalStore(root).Read().ResinLimit==60,"AI budget shares goal state");
   Check(execute("goals.budget",new Dictionary<string,object>{{"amount",20.5}}).State=="failed"&&new GoalStore(root).Read().ResinLimit==60,"Fractional resin budget is rejected without rounding or overwriting the saved limit");
   string goalId=new GoalStore(root).Read().Goals[0].Id;Check(execute("goals.pause",new Dictionary<string,object>{{"id",goalId}}).Action=="goals.pause","Goal mutation identifies its shared refresh domain");Check(new GoalStore(root).Read().Goals[0].Paused,"AI pause shares existing goal behavior");
   if(ProcessGuard.Busy()){Check(execute("display.ai",new Dictionary<string,object>()).State=="failed","Live game blocks display mutation even for isolated profile");}else{Check(execute("display.ai",new Dictionary<string,object>()).State=="completed","AI preset applies through existing preset domain");execute("display.restore",new Dictionary<string,object>());}Check(Convert.ToInt32(new ConfigStore(Path.Combine(root,"fps_config.json")).Read()["FPSTarget"])==100,"Personal display restored or busy mutation rejected");
   var path=Path.Combine(root,"good.json");File.WriteAllText(path,"{\"format\":\"GOOD\",\"version\":1,\"source\":\"test\",\"characters\":[],\"weapons\":[]}");new ProfileStore(root).Import("account",path);var query=CatheryneTools.Json().Serialize(tools.Query("characters",0));Check(query.Contains("\"collected\":true")&&query.Contains("\"total\":0"),"Collected empty differs from unknown");
   File.WriteAllText(path,"{\"format\":\"GOOD\",\"version\":1,\"source\":\"test\",\"characters\":[{\"key\":\"Amber\",\"level\":20},{\"key\":\"Lisa\",\"level\":20}],\"weapons\":[],\"artifacts\":null}");new ProfileStore(root).Import("account",path);
   Check(Equals(CodexChat.Map(tools.Query("artifacts",0))["collected"],false),"Null section remains unknown in AI queries");
   Check(CodexChat.S(CodexChat.Map(tools.Query("characters",0)),"scope")=="unspecified","Missing scan coverage is not inferred from an array");
   var covered=CatheryneTools.Json().Deserialize<Dictionary<string,object>>(File.ReadAllText(path));covered["catheryne"]=new Dictionary<string,object>{{"coverage",new Dictionary<string,object>{{"characters","partial"},{"weapons","full"},{"artifacts","uncollected"}}}};File.WriteAllText(path,CatheryneTools.Json().Serialize(covered));new ProfileStore(root).Import("account",path);
   Check(CodexChat.S(CodexChat.Map(tools.Query("characters",0)),"scope")=="partial"&&CodexChat.S(CodexChat.Map(tools.Query("weapons",0)),"scope")=="full"&&CodexChat.S(CodexChat.Map(tools.Query("artifacts",0)),"scope")=="uncollected","Query coverage follows the canonical section even when the collection is empty or null");
   var selected=CodexChat.Map(tools.Query("characters",0,"Amber"));Check(Convert.ToInt32(selected["total"])==1&&CodexChat.S(CodexChat.Items(selected["items"]).Single(),"key")=="Amber","Character context fetch does not return unrelated records");

   var metadata=CodexChat.Map(covered["catheryne"]);metadata["characterAliases"]=new Dictionary<string,object>{{"Amber","시험 별칭"}};File.WriteAllText(path,CatheryneTools.Json().Serialize(covered));new ProfileStore(root).Import("account",path);
   var aliasResult=CodexChat.Map(tools.Query("characters",0,"시험 별칭"));var aliasItem=CodexChat.Items(aliasResult["items"]).Single();
   Check(CodexChat.S(aliasItem,"key")=="Amber"&&CodexChat.S(aliasItem,"display_name")=="시험 별칭 ("+(Locale.IsEnglish?"Amber":"엠버")+")","AI alias search and translated display preserve the original GOOD key");
   var imported=execute("records.import",new Dictionary<string,object>{{"kind","account"},{"path",path}});Check(imported.State=="completed","AI import uses ProfileStore");var exported=execute("records.export",new Dictionary<string,object>{{"kind","account"}});Check(exported.State=="completed","AI export produces canonical output");string exportPath=CodexChat.S(CodexChat.Map(CatheryneTools.Json().DeserializeObject(CatheryneTools.Json().Serialize(exported.Result))),"path");Check(File.Exists(exportPath),"Export evidence exists");Check(execute("records.export",new Dictionary<string,object>{{"kind","account"},{"path",exportPath}}).State=="failed","Export cannot overwrite existing file silently");
   var calendarAdded=execute("calendar.add",new Dictionary<string,object>{{"title","연결 시험"},{"due","2030-01-02T18:30:00+09:00"},{"repeat","weekly"}});Check(calendarAdded.State=="completed"&&new CalendarStore(root).Read().Any(x=>x.Title=="연결 시험"&&x.Due.Hour==9),"AI calendar uses UI store and timezone");
   string calendarId=new CalendarStore(root).Read().Single(x=>x.Title=="연결 시험").Id;
   var marked=execute("calendar.complete",new Dictionary<string,object>{{"id",calendarId},{"done",true}});Check(marked.State=="completed"&&new CalendarStore(root).Read().Single(x=>x.Id==calendarId).Done,"Calendar completion persists through a new UI store");
   Check(new AiTaskStore(root).Find(marked.Id).State=="completed","Calendar completion has a restorable work record");
   Check(execute("calendar.complete",new Dictionary<string,object>{{"id",calendarId},{"done",false}}).State=="completed"&&!new CalendarStore(root).Read().Single(x=>x.Id==calendarId).Done,"Calendar completion undo uses the same stored entry");
   Check(execute("calendar.complete",new Dictionary<string,object>{{"id",calendarId},{"done","false"}}).State=="failed"&&execute("calendar.complete",new Dictionary<string,object>{{"id","act_list:provider"},{"done",true}}).State=="failed","Calendar rejects ambiguous completion and provider entries");
   int calendarCount=new CalendarStore(root).Read().Count;Check(execute("calendar.add",new Dictionary<string,object>{{"title","무효"},{"due","2030-01-02T18:30:00"}}).State=="failed"&&new CalendarStore(root).Read().Count==calendarCount,"Calendar rejects ambiguous timezone without writes");
   Check(execute("calendar.refresh",new Dictionary<string,object>()).Action=="hoyolab_login","Calendar exposes typed login prerequisite");
   using(var db=new LocalDataService(root))db.SetSecret("hoyolab","synthetic-secret");execute("daily.disconnect",new Dictionary<string,object>());using(var db=new LocalDataService(root))Check(string.IsNullOrEmpty(db.GetSecret("hoyolab")),"Disconnect removes only canonical secret");Check(Equals(AppPreferences.Read(root)["resinMonitor"],false),"Disconnect disables monitoring");
   Check(ApplicationOperations.Names.Length==ApplicationOperations.Names.Distinct().Count(),"Operation catalog IDs unique");
  }finally{if(Directory.Exists(root))Directory.Delete(root,true);}
 }
}

