using System;
using System.Collections.Generic;
using System.Linq;
internal static class CharacterBuildTests {
 static void Check(bool condition,string message){if(!condition)throw new Exception(message);}
 internal static void Run(string root){
  var character=CatheryneTools.Json().Deserialize<Dictionary<string,object>>(@"{""key"":""Faruzan"",""level"":90,""ascension"":6,""constellation"":6,""talent"":{""auto"":1,""skill"":9,""burst"":9}}");
  var weapon=CatheryneTools.Json().Deserialize<Dictionary<string,object>>(@"{""key"":""FavoniusWarbow"",""level"":90,""ascension"":6,""refinement"":1,""location"":""Faruzan""}");
  var gear=new List<Dictionary<string,object>>();string[] slots={"flower","plume","sands","goblet","circlet"},mains={"hp","atk","enerRech_","anemo_dmg_","critRate_"};
  for(int i=0;i<5;i++){var item=CatheryneTools.Json().Deserialize<Dictionary<string,object>>(@"{""rarity"":5,""level"":20,""substats"":[{""key"":""critRate_"",""value"":8.6},{""key"":""critDMG_"",""value"":7.8},{""key"":""atk_"",""value"":5.8},{""key"":""eleMas"",""value"":23}]}");item["setKey"]="TenacityOfTheMillelith";item["slotKey"]=slots[i];item["mainStatKey"]=mains[i];item["location"]="Faruzan";gear.Add(item);}
  var snapshot=new Dictionary<string,object>{{"characters",new[]{character}},{"weapons",new[]{weapon}},{"artifacts",gear}};
  var criterion=CharacterBuild.Read(root,character);var score=CharacterBuild.Evaluate(snapshot,character,criterion);Check(score.Total.HasValue&&score.Parts.Sum(x=>x.Maximum)==100&&score.Total<=100,"Complete data produces a bounded score with explicit 100-point breakdown");
  snapshot["artifacts"]=gear.Concat(new[]{gear[0]}).ToArray();Check(!CharacterBuild.Evaluate(snapshot,character,criterion).Total.HasValue,"Duplicate slots remain unknown without crashing");snapshot["artifacts"]=gear;double total=score.Total.Value;var talents=CodexChat.Map(character["talent"]);talents["auto"]=10;Check(CharacterBuild.Evaluate(snapshot,character,criterion).Total==total,"Irrelevant normal attacks do not increase a support score");weapon["refinement"]=5;Check(CharacterBuild.Evaluate(snapshot,character,criterion).Total==total,"Buying refinements does not gate development readiness");
  character["level"]=80;Check(CharacterBuild.Evaluate(snapshot,character,criterion).Total<total,"Character level matters monotonically");character["level"]=90;
  talents.Remove("skill");score=CharacterBuild.Evaluate(snapshot,character,criterion);Check(!score.Total.HasValue&&score.Parts.Single(x=>x.Name=="유효 특성").Points==null,"Missing useful talent is unknown, not zero or a reweighted inflated total");talents["skill"]=9;
  gear[0]["substats"]=null;Check(!CharacterBuild.Evaluate(snapshot,character,criterion).Total.HasValue,"Missing substats prevents a false total");
  snapshot["artifacts"]=new object[0];score=CharacterBuild.Evaluate(snapshot,character,criterion);Check(score.Total==50,"Collected empty equipment receives real zero artifact points");snapshot["artifacts"]=null;Check(!CharacterBuild.Evaluate(snapshot,character,criterion).Total.HasValue,"Uncollected equipment remains unknown");
  character["constellation"]=5;Check(CharacterBuild.Read(root,character).Talents["skill"]==6&&CharacterBuild.Read(root,character).Sets.Contains("NoblesseOblige"),"Faruzan pre-C6 criterion differs from C6");
  character["key"]="Nilou";criterion=CharacterBuild.Read(root,character);foreach(var item in gear)item["location"]="Nilou";for(int i=0;i<5;i++){gear[i]["setKey"]=i<2?"TenacityOfTheMillelith":"VourukashasGlow";}snapshot["artifacts"]=gear;score=CharacterBuild.Evaluate(snapshot,character,criterion);Check(score.Parts.Single(x=>x.Name=="성유물 세트").Points==10,"Two plus two set alternatives count correctly");
  CharacterBuild.Save(root,"Nilou",criterion);Check(CharacterBuild.Read(root,character).Pair.Length==2,"Role criterion persists and round trips");
  character["key"]="Zhongli";criterion=CharacterBuild.Read(root,character);weapon["key"]="BlackTassel";weapon["location"]="Zhongli";Check(!CharacterBuild.Evaluate(snapshot,character,criterion).Criterion.Useful.Contains("critRate_"),"Shield support does not score crit without Favonius");weapon["key"]="FavoniusLance";Check(CharacterBuild.Evaluate(snapshot,character,criterion).Criterion.Useful.Contains("critRate_")&&!criterion.Useful.Contains("critRate_"),"Favonius adds conditional useful crit without mutating saved criterion");
  var automatic=CharacterBuild.Read(root,new Dictionary<string,object>{{"key","Xingqiu"}});Check(automatic!=null&&automatic.Automatic&&automatic.Useful.Contains("enerRech_")&&!automatic.Useful.Contains("def_"),"Maintained upstream criteria cover characters outside hand-authored roles");
  var native=CharacterBuild.Read(root,new Dictionary<string,object>{{"gameId",10000025}});Check(native!=null&&native.Useful.SequenceEqual(automatic.Useful),"GOOD and game ID resolve the same automatic criterion");
  var xingqiu=new Dictionary<string,object>{{"key","Xingqiu"},{"level",90},{"ascension",6}};xingqiu["talent"]=new Dictionary<string,object>{{"auto",1},{"skill",9},{"burst",9}};Check(automatic.Talents["auto"]==0&&automatic.Talents["burst"]==9,"Source calculation dependencies exclude unused normal attacks for Xingqiu");var empty=new Dictionary<string,object>{{"weapons",new object[0]},{"artifacts",new object[0]}};var partial=CharacterBuild.Evaluate(empty,xingqiu,automatic);Check(partial.Total==35&&partial.Parts.Sum(x=>x.Maximum)==100,"Automatic criteria use the same 100-point framework including useful talents");
  var one=CatheryneTools.Json().Deserialize<Dictionary<string,object>>(CatheryneTools.Json().Serialize(gear[1]));one["location"]="Xingqiu";empty["artifacts"]=new[]{one};var weighted=CharacterBuild.Evaluate(empty,xingqiu,automatic);var uniform=CatheryneTools.Json().Deserialize<BuildCriterion>(CatheryneTools.Json().Serialize(automatic));uniform.UsefulWeights=null;Check(weighted.Parts.Single(x=>x.Name=="성유물 유효 옵션").Points<CharacterBuild.Evaluate(empty,xingqiu,uniform).Parts.Single(x=>x.Name=="성유물 유효 옵션").Points,"Upstream stat weights affect useful-roll contribution");
  empty["artifacts"]=null;Check(!CharacterBuild.Evaluate(empty,xingqiu,automatic).Total.HasValue,"Missing account observations remain unknown in automatic evaluation");
  Check(BuildCriteriaCatalog.TalentDependencies("export const details = [{dmg:({talent})=>talent.e.x},{dmg:({talent})=>talent.a.x}];export const buffs=[{x:({talent})=>talent.q.x}];",true).SequenceEqual(new[]{"skill","burst"}),"Optional normal-attack variants do not define the default talent goal");
  Check(BuildCriteriaCatalog.TalentDependencies("export const details=[{dmg:({talent})=>talent.e.x},{dmg:({talent})=>talent.a.x}];export const defDmgIdx=1;",true).Contains("auto"),"An upstream default normal-attack scenario requires normal-attack development");
  var setGear=new List<Dictionary<string,object>>();for(int i=0;i<5;i++){var equipped=CatheryneTools.Json().Deserialize<Dictionary<string,object>>(CatheryneTools.Json().Serialize(one));equipped["slotKey"]=slots[i];equipped["setKey"]="EmblemOfSeveredFate";equipped["identity"]="unique-piece-"+i;setGear.Add(equipped);}empty["artifacts"]=setGear;
  Check(CharacterBuild.Evaluate(empty,xingqiu,automatic).Parts.Single(x=>x.Name=="성유물 세트").Points==5*(automatic.SetAffinities["EmblemOfSeveredFate"]["2"]+automatic.SetAffinities["EmblemOfSeveredFate"]["4"]),"Four-piece evaluation uses the shared set identity and both active effects");
  for(int i=0;i<5;i++)setGear[i]["setKey"]=i<2?"HeartOfDepth":i<4?"NoblesseOblige":"Instructor";Check(CharacterBuild.Evaluate(empty,xingqiu,automatic).Parts.Single(x=>x.Name=="성유물 세트").Points==10,"Automatic 2+2 counts two compatible active set effects");
  var suitable=CatheryneTools.Json().Deserialize<Dictionary<string,object>>(CatheryneTools.Json().Serialize(weapon));suitable["key"]="FavoniusSword";suitable["location"]="Xingqiu";empty["weapons"]=new[]{suitable};double suitableScore=CharacterBuild.Evaluate(empty,xingqiu,automatic).Parts.Single(x=>x.Name=="무기").Points.Value;suitable["key"]="FavoniusWarbow";Check(CharacterBuild.Evaluate(empty,xingqiu,automatic).Parts.Single(x=>x.Name=="무기").Points<suitableScore,"Wrong weapon type cannot earn the appropriate-substat points");
  var original=BuildCriteriaCatalog.Read(root);Check(original!=null&&original.Profiles.Count>=90,"Bundled upstream data works offline");
  foreach(string id in original.Profiles.Keys){var record=new Dictionary<string,object>{{"gameId",id},{"level",90},{"ascension",6},{"talent",new Dictionary<string,object>{{"auto",9},{"skill",9},{"burst",9}}}};var resolved=BuildCriteriaCatalog.Criterion(root,record);try{CharacterBuild.Validate(resolved);}catch(Exception e){throw new Exception("Invalid source criterion "+id,e);}var result=CharacterBuild.Evaluate(new Dictionary<string,object>{{"weapons",new object[0]},{"artifacts",new object[0]}},record,resolved);Check(result.Total.HasValue&&result.Parts.Sum(x=>x.Maximum)==100,"Every bundled profile has one complete 100-point criterion: "+id);}
  Check(automatic.MainWeights["sands"].Values.Max()==1,"The strongest applicable main stat reaches its full target score");Check(automatic.SetAffinities["ShimenawasReminiscence"]["4"]==0,"Normal-attack set bonuses do not benefit a default off-field role");
  var newer=CatheryneTools.Json().Deserialize<BuildCriteriaData>(CatheryneTools.Json().Serialize(original));newer.Revision="test-revision";newer.Profiles["19999999"]=new Dictionary<string,double>{{"eleMas",1}};newer.Keys["FutureCharacter"]="19999999";newer.Roles["19999999"]=new BuildRoleMetadata{Element="hydro",WeaponType="sword",Damage=1};
  newer.Profiles["19999998"]=new Dictionary<string,double>{{"eleMas",1}};newer.Roles["19999998"]=new BuildRoleMetadata{Element="hydro",WeaponType="sword",Damage=1};newer.CharacterNames["19999998"]="New Automatic Hero";
  BuildCriteriaCatalog.Load(root,true,()=>newer);Check(CharacterBuild.Read(root,new Dictionary<string,object>{{"key","FutureCharacter"}}).Useful.SequenceEqual(new[]{"eleMas"}),"New upstream characters appear without application changes");
  Check(CharacterBuild.Read(root,new Dictionary<string,object>{{"key","NewAutomaticHero"}})!=null,"A newly downloaded ID and name resolves without a GOOD mapping or compiled catalog change");
  var collision=CatheryneTools.Json().Deserialize<BuildCriteriaData>(CatheryneTools.Json().Serialize(newer));collision.CharacterNames["19999997"]="New-Automatic Hero";BuildCriteriaCatalog.Load(root,true,()=>collision);Check(CharacterBuild.Read(root,new Dictionary<string,object>{{"key","NewAutomaticHero"}})==null,"Ambiguous normalized source names are not guessed");BuildCriteriaCatalog.Load(root,true,()=>newer);
  var saved=BuildCriteriaCatalog.Load(root,true,()=>{throw new System.IO.IOException("offline");});Check(saved.Revision=="test-revision"&&saved.Error!=null&&CharacterBuild.Read(root,new Dictionary<string,object>{{"key","FutureCharacter"}})!=null,"Failed refresh preserves last validated source");
  var malformed=CatheryneTools.Json().Deserialize<BuildCriteriaData>(CatheryneTools.Json().Serialize(newer));malformed.Profiles["19999999"]["eleMas"]=double.NaN;Check(BuildCriteriaCatalog.Load(root,true,()=>malformed).Revision=="test-revision","Nonfinite weights never replace validated criteria");
  CharacterBuild.Save(root,"Xingqiu",criterion);Check(!CharacterBuild.Read(root,xingqiu).Automatic,"An explicit user criterion takes precedence over automatic defaults");
  foreach(string key in new[]{"Vesna","Vodyanitsa"}){var good=CharacterBuild.Read(root,new Dictionary<string,object>{{"key",key}});string id=GameCatalog.CharacterField(key,"gameId");var byId=CharacterBuild.Read(root,new Dictionary<string,object>{{"gameId",id}});Check(good!=null&&byId!=null&&good.Useful.SequenceEqual(byId.Useful),"Supplemented canonical names resolve the same maintained criterion: "+key);}
  var missingCharacter=new Dictionary<string,object>{{"key","UnknownRole"},{"level",70},{"ascension",4}};var missingScore=CharacterBuild.Evaluate(new Dictionary<string,object>(),missingCharacter,null);Check(missingScore.Parts.Sum(x=>x.Maximum)==100&&missingScore.Parts.Single(x=>x.Name=="레벨·돌파").Points>0&&missingScore.Known>0&&!missingScore.Total.HasValue,"Missing role preserves observed level points inside the common 100-point model");
  missingCharacter.Remove("ascension");missingScore=CharacterBuild.Evaluate(new Dictionary<string,object>(),missingCharacter,null);Check(missingScore.Known>0&&missingScore.Coverage==12,"Unknown ascension preserves the known level contribution without reweighting");
  var observedOnly=CharacterBuild.Evaluate(new Dictionary<string,object>(),xingqiu,automatic);Check(observedOnly.Known==35&&observedOnly.Coverage==35&&!observedOnly.Total.HasValue,"Uncollected gear does not hide known character and talent points or inflate a 100-point score");
  var orderRows=new[]{new Dictionary<string,object>{{"key","Unknown4"},{"rarity",4},{"level",90}},new Dictionary<string,object>{{"key","Unknown5Low"},{"rarity",5},{"level",1}},new Dictionary<string,object>{{"key","Unknown5High"},{"rarity",5},{"level",80}}};foreach(string kind in new[]{"characters","weapons"})Check(InventoryOrder.Sort(kind,orderRows,x=>CodexChat.S(x,"key")).Select(x=>CodexChat.S(x,"key")).SequenceEqual(new[]{"Unknown5High","Unknown5Low","Unknown4"}),"Default inventory order groups rarity before level: "+kind);
  var artifactOrder=new[]{new Dictionary<string,object>{{"setKey","TestSet"},{"rarity",5},{"slotKey","circlet"},{"level",20}},new Dictionary<string,object>{{"setKey","TestSet"},{"rarity",5},{"slotKey","flower"},{"level",0}},new Dictionary<string,object>{{"setKey","TestSet"},{"rarity",4},{"slotKey","flower"},{"level",20}}};Check(CodexChat.S(InventoryOrder.Sort("artifacts",artifactOrder,x=>"").First(),"slotKey")=="flower"&&CodexChat.S(InventoryOrder.Sort("artifacts",artifactOrder,x=>"").Last(),"rarity")=="4","Artifact order groups grade then set then natural equipment slot");
  character["key"]="UncataloguedCharacter";Check(CharacterBuild.Read(root,character)==null,"Unknown character role is not guessed from element or weapon");
 }
}
