using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Media;

// One role-specific criterion model for the inventory, comparison and AI projection.
internal sealed class BuildCriterion {
 public bool Automatic {get;set;} public Dictionary<string,double> WeaponFit {get;set;} public Dictionary<string,Dictionary<string,double>> MainWeights {get;set;} public Dictionary<string,Dictionary<string,double>> SetAffinities {get;set;} public Dictionary<string,double> UsefulWeights {get;set;} public bool FavoniusCritical {get;set;} public string Name {get;set;} public string Source {get;set;} public string Checked {get;set;}
 public int Level {get;set;} public Dictionary<string,int> Talents {get;set;}
 public string[] Useful {get;set;} public string[] Sands {get;set;} public string[] Goblet {get;set;} public string[] Circlet {get;set;}
 public string[] Pair {get;set;} public string[] Sets {get;set;} public string[] Weapons {get;set;} public double Rolls {get;set;}
}
internal sealed class BuildPart {
 public string Name {get;set;} public double Maximum {get;set;} public double? Points {get;set;} public double Known {get;set;} public double Coverage {get;set;} public string Detail {get;set;}
}
internal sealed class CharacterBuildScore {
 public BuildCriterion Criterion {get;set;} public BuildPart[] Parts {get;set;}
 public double? Total {get;set;} public double Known {get;set;} public double Coverage {get;set;}
}
internal static class CharacterBuild {
 static BuildCriterion Criterion(string name,string source,string[] useful,string[] sands,string[] goblet,string[] circlet,string[] sets,string[] weapons,params int[] talents){return new BuildCriterion{Name=name,Source=source,Checked="2026-09-30",Level=90,Talents=new Dictionary<string,int>{{"auto",talents[0]},{"skill",talents[1]},{"burst",talents[2]}},Useful=useful,Sands=sands,Goblet=goblet,Circlet=circlet,Sets=sets,Weapons=weapons,Rolls=25};}
 static BuildCriterion Support(BuildCriterion c){c.FavoniusCritical=true;return c;}
 internal static BuildCriterion Read(string root,Dictionary<string,object> character){
  var prefs=AppPreferences.Read(root);var criterion=ReadRole(root,character,prefs);object raw;if(criterion!=null&&!prefs.ContainsKey("buildCriterion."+AccountIdentity.Key(character))&&prefs.TryGetValue("artifactUsefulStats."+AccountIdentity.Key(character),out raw)&&raw is System.Collections.IEnumerable)criterion.Useful=((System.Collections.IEnumerable)raw).Cast<object>().Select(Convert.ToString).Where(BuildAnalysis.StatKeys.Contains).Distinct().ToArray();return criterion;
 }
 static BuildCriterion ReadRole(string root,Dictionary<string,object> character,Dictionary<string,object> prefs){
  string key=AccountIdentity.Key(character);object raw;
  if(prefs.TryGetValue("buildCriterion."+key,out raw)&&raw!=null){try{var custom=CatheryneTools.Json().Deserialize<BuildCriterion>(CatheryneTools.Json().Serialize(raw));Validate(custom);return custom;}catch(ArgumentException){}catch(InvalidOperationException){}}
  int rank;int.TryParse(CodexChat.S(character,"constellation"),out rank);
  string[] crit={"critRate_","critDMG_"},attack={"atk_","critRate_","critDMG_","enerRech_"},hp={"hp_","critRate_","critDMG_","enerRech_"};
  switch(key){
   case "Faruzan":return Criterion(Locale.T("바람 지원"), "https://keqingmains.com/q/faruzan-quickguide/",attack,new[]{"enerRech_","atk_"},rank>=6?new[]{"anemo_dmg_"}:BuildAnalysis.StatKeys.Concat(new[]{"anemo_dmg_"}).ToArray(),rank>=6?crit:BuildAnalysis.StatKeys,new[]{rank>=6?"TenacityOfTheMillelith":"NoblesseOblige"},new[]{"FavoniusWarbow","ElegyForTheEnd","SacrificialBow","FadingTwilight","EndOfTheLine"},0,rank>=6?9:6,9);
   case "Wanderer":return Criterion(Locale.T("바람 주력 딜러"),"https://keqingmains.com/q/wanderer-quickguide/",rank>=2?attack:new[]{"atk_","critRate_","critDMG_"},new[]{"atk_"},new[]{"anemo_dmg_","atk_"},crit,new[]{"DesertPavilionChronicle","ShimenawasReminiscence"},new[]{"TulaytullahsRemembrance","TheWidsith","LostPrayerToTheSacredWinds","SkywardAtlas"},9,8,rank>=2?9:6);
   case "Furina":return Criterion(Locale.T("물 피해·팀 지원"),"https://keqingmains.com/q/furina-quickguide/",hp,new[]{"hp_","enerRech_"},new[]{"hp_","hydro_dmg_"},crit,new[]{"GoldenTroupe"},new[]{"SplendorOfTranquilWaters","FesteringDesire","FleuveCendreFerryman","FavoniusSword","WolfFang"},0,9,9);
   case "Nahida":return Criterion(Locale.T("풀 원소 부착·지원"),"https://keqingmains.com/q/nahida-quickguide/",new[]{"eleMas","critRate_","critDMG_","enerRech_"},new[]{"eleMas"},new[]{"eleMas","dendro_dmg_"},crit.Concat(new[]{"eleMas"}).ToArray(),new[]{"DeepwoodMemories","GildedDreams"},new[]{"AThousandFloatingDreams","SacrificialFragments","MagicGuide","WanderingEvenstar"},0,9,8);
   case "Zhongli":return Support(Criterion(Locale.T("보호막 지원"),"https://keqingmains.com/q/zhongli-quickguide/",new[]{"hp_","hp"},new[]{"hp_"},new[]{"hp_"},new[]{"hp_"},new[]{"TenacityOfTheMillelith","ArchaicPetra"},new[]{"BlackTassel","FavoniusLance","StaffOfHoma"},0,9,0));
   case "RaidenShogun":return Criterion(Locale.T("원소폭발 주력 딜러"),"https://keqingmains.com/q/raiden-quickguide/",attack,new[]{"atk_","enerRech_"},new[]{"electro_dmg_","atk_"},crit,new[]{"EmblemOfSeveredFate"},new[]{"EngulfingLightning","TheCatch","StaffOfHoma","PrimordialJadeWingedSpear","WavebreakersFin"},0,9,9);
   case "Xianyun":return Support(Criterion(Locale.T("낙하 공격·회복 지원"),"https://keqingmains.com/q/xianyun-quickguide/",new[]{"atk_","atk","enerRech_"},new[]{"atk_","enerRech_"},new[]{"atk_"},new[]{"atk_"},new[]{"ViridescentVenerer","NoblesseOblige","OceanHuedClam","SongOfDaysPast"},new[]{"CranesEchoingCall","FavoniusCodex","OathswornEye","SkywardAtlas","ThrillingTalesOfDragonSlayers"},0,6,9));
   case "Shenhe":return Support(Criterion(Locale.T("얼음 피해 지원"),"https://keqingmains.com/q/shenhe-quickguide/",new[]{"atk_","atk","enerRech_"},new[]{"atk_","enerRech_"},new[]{"atk_"},new[]{"atk_"},new[]{"NoblesseOblige"},new[]{"CalamityQueller","FavoniusLance","EngulfingLightning","SkywardSpine"},0,9,9));
   case "Citlali":return Criterion(Locale.T("보호막·융해 지원"),"https://keqingmains.com/q/citlali-quickguide/",new[]{"eleMas","enerRech_"},new[]{"eleMas","enerRech_"},new[]{"eleMas"},new[]{"eleMas"},new[]{"ScrollOfTheHeroOfCinderCity","TenacityOfTheMillelith","NoblesseOblige"},new[]{"StarcallersWatch","ThrillingTalesOfDragonSlayers","WanderingEvenstar","AThousandFloatingDreams","SacrificialFragments"},0,9,6);
   case "SangonomiyaKokomi":return Criterion(Locale.T("물 부착·회복 지원"),"https://keqingmains.com/q/kokomi-quickguide/",new[]{"hp_","hp","enerRech_"},new[]{"hp_","enerRech_"},new[]{"hp_","hydro_dmg_"},new[]{"heal_"},new[]{"TenacityOfTheMillelith","OceanHuedClam"},new[]{"ThrillingTalesOfDragonSlayers","PrototypeAmber","EverlastingMoonglow","HakushinRing"},0,9,0);
   case "HuTao":return Criterion(Locale.T("증발 주력 딜러"),"https://keqingmains.com/q/hu-tao-quickguide/",new[]{"hp_","eleMas","critRate_","critDMG_"},new[]{"hp_","eleMas"},new[]{"pyro_dmg_"},crit,new[]{"CrimsonWitchOfFlames","ShimenawasReminiscence"},new[]{"StaffOfHoma","DragonsBane","BalladOfTheFjords","Deathmatch","PrimordialJadeWingedSpear"},9,9,8);
   case "Neuvillette":return Criterion(Locale.T("강공격 주력 딜러"),"https://keqingmains.com/q/neuvillette-quickguide/",hp,new[]{"hp_"},new[]{"hp_","hydro_dmg_"},crit,new[]{"MarechausseeHunter"},new[]{"TomeOfTheEternalFlow","SacrificialJade","PrototypeAmber","JadefallsSplendor"},9,6,6);
   case "KaedeharaKazuha":return Criterion(Locale.T("확산·원소 피해 지원"),"https://keqingmains.com/q/kazuha-quickguide/",new[]{"eleMas","enerRech_"},new[]{"eleMas","enerRech_"},new[]{"eleMas"},new[]{"eleMas"},new[]{"ViridescentVenerer"},new[]{"FreedomSworn","XiphosMoonlight","FavoniusSword","IronSting","SacrificialSword"},6,6,8);
   case "Nilou":var bloom=Criterion(Locale.T("풍요의 핵 지원"),"https://keqingmains.com/q/nilou-quickguide/",new[]{"hp_","hp","eleMas"},new[]{"hp_"},new[]{"hp_"},new[]{"hp_"},new string[0],new[]{"KeyOfKhajNisut","TheDockhandsAssistant","IronSting","XiphosMoonlight"},0,0,0);bloom.Pair=new[]{"TenacityOfTheMillelith","VourukashasGlow"};return bloom;
  }
  return BuildCriteriaCatalog.Criterion(root,character);
 }
 internal static void Validate(BuildCriterion c){if(c==null||string.IsNullOrWhiteSpace(c.Name)||c.Level<1||c.Level>90||c.Rolls<1||c.Rolls>45||c.Talents==null||c.Talents.Any(x=>!new[]{"auto","skill","burst"}.Contains(x.Key)||x.Value<0||x.Value>10)||c.Automatic&&(c.MainWeights==null||c.WeaponFit==null||c.SetAffinities==null||c.MainWeights.Any(x=>x.Value==null||x.Value.Values.Any(v=>double.IsNaN(v)||double.IsInfinity(v)||v<0||v>1))||c.WeaponFit.Values.Any(v=>double.IsNaN(v)||double.IsInfinity(v)||v<0||v>1)||c.SetAffinities.Any(x=>x.Value==null||x.Value.Values.Any(v=>double.IsNaN(v)||double.IsInfinity(v)||v<0||v>1)))||c.UsefulWeights!=null&&c.UsefulWeights.Any(x=>!BuildAnalysis.StatKeys.Contains(x.Key)||double.IsNaN(x.Value)||double.IsInfinity(x.Value)||x.Value<0||x.Value>1)||c.Useful==null||c.Useful.Any(x=>!BuildAnalysis.StatKeys.Contains(x))||c.Sands==null||c.Sands.Length==0||c.Goblet==null||c.Goblet.Length==0||c.Circlet==null||c.Circlet.Length==0||c.Sets==null||(c.Sets.Length==0&&(c.Pair==null||c.Pair.Length!=2))||(c.Pair!=null&&c.Pair.Length>0&&(c.Pair.Length!=2||c.Pair.Distinct().Count()!=2))||c.Weapons==null||c.Weapons.Length==0)throw new ArgumentException("평가 기준을 확인해 주세요.");}
 internal static BuildCriterion Copy(BuildCriterion c){if(c==null)return null;return new BuildCriterion{Automatic=c.Automatic,FavoniusCritical=c.FavoniusCritical,Name=c.Name,Source=c.Source,Checked=c.Checked,Level=c.Level,Rolls=c.Rolls,Talents=c.Talents==null?null:new Dictionary<string,int>(c.Talents),UsefulWeights=c.UsefulWeights==null?null:new Dictionary<string,double>(c.UsefulWeights),WeaponFit=c.WeaponFit==null?null:new Dictionary<string,double>(c.WeaponFit),MainWeights=c.MainWeights==null?null:c.MainWeights.ToDictionary(x=>x.Key,x=>new Dictionary<string,double>(x.Value)),SetAffinities=c.SetAffinities==null?null:c.SetAffinities.ToDictionary(x=>x.Key,x=>new Dictionary<string,double>(x.Value)),Useful=c.Useful==null?null:(string[])c.Useful.Clone(),Sands=c.Sands==null?null:(string[])c.Sands.Clone(),Goblet=c.Goblet==null?null:(string[])c.Goblet.Clone(),Circlet=c.Circlet==null?null:(string[])c.Circlet.Clone(),Sets=c.Sets==null?null:(string[])c.Sets.Clone(),Weapons=c.Weapons==null?null:(string[])c.Weapons.Clone(),Pair=c.Pair==null?null:(string[])c.Pair.Clone()};}
 internal static void Save(string root,string key,BuildCriterion criterion){Validate(criterion);AppPreferences.Set("buildCriterion."+key,criterion,root);}
 static double? Number(Dictionary<string,object> item,string key){double value;return double.TryParse(CodexChat.S(item,key),NumberStyles.Float,CultureInfo.InvariantCulture,out value)&&!double.IsNaN(value)&&!double.IsInfinity(value)&&value>=0?(double?)value:null;}
 static double Fraction(double current,double target){return Math.Max(0,Math.Min(1,current/target));}
 static BuildPart Part(string name,double max,double? fraction,string detail){return new BuildPart{Name=name,Maximum=max,Points=fraction.HasValue?(double?)(Fraction(fraction.Value,1)*max):null,Known=fraction.HasValue?Fraction(fraction.Value,1)*max:0,Coverage=fraction.HasValue?max:0,Detail=detail};}
 static BuildPart Components(string name,double[] maxima,double?[] fractions,string detail){var parts=maxima.Select((m,i)=>Part(name,m,fractions[i],detail)).ToArray();double known=parts.Sum(x=>x.Known),coverage=parts.Sum(x=>x.Coverage),maximum=maxima.Sum();return new BuildPart{Name=name,Maximum=maximum,Known=known,Coverage=coverage,Points=coverage==maximum?(double?)known:null,Detail=detail};}
 internal static CharacterBuildScore Evaluate(string root,Dictionary<string,object> snapshot,Dictionary<string,object> character){return Evaluate(snapshot,character,Read(root,character));}
 internal static CharacterBuildScore Evaluate(Dictionary<string,object> snapshot,Dictionary<string,object> character,BuildCriterion c){
  var result=new CharacterBuildScore{Criterion=c,Parts=new BuildPart[0]};if(c!=null)Validate(c);string key=AccountIdentity.Key(character);if(c!=null&&c.FavoniusCritical&&AccountMerge.Equipped(snapshot,"weapons",key).Any(x=>AccountIdentity.Key(x).StartsWith("Favonius",StringComparison.Ordinal))){c=Copy(c);c.Useful=c.Useful.Concat(new[]{"critRate_"}).Distinct().ToArray();c.Circlet=c.Circlet.Concat(new[]{"critRate_"}).Distinct().ToArray();if(c.UsefulWeights!=null)c.UsefulWeights["critRate_"]=1;if(c.MainWeights!=null&&c.MainWeights.ContainsKey("circlet"))c.MainWeights["circlet"]["critRate_"]=1;result.Criterion=c;}var parts=new List<BuildPart>();var targets=c==null?new KeyValuePair<string,int>[0]:c.Talents.Where(x=>x.Value>0).ToArray();
  double levelMaximum=c!=null&&targets.Length==0?35:15;int levelTarget=c==null?90:c.Level;double? level=Number(character,"level"),ascension=Number(character,"ascension");parts.Add(Components("레벨·돌파",new[]{levelMaximum*.8,levelMaximum*.2},new[]{level.HasValue?(double?)Fraction(level.Value,levelTarget):null,ascension.HasValue?(double?)Fraction(ascension.Value,6):null},"Lv. "+CodexChat.S(character,"level")+" / "+levelTarget+"   "+Locale.T("돌파")+" "+CodexChat.S(character,"ascension")+" / 6"));
  object raw;var talents=character.TryGetValue("talent",out raw)?CodexChat.Map(raw):new Dictionary<string,object>();var values=targets.Select(x=>Number(talents,x.Key)).ToArray();parts.Add(c==null?Part("유효 특성",20,null,Locale.T("평가 기준 미확인")):targets.Length==0?Part("유효 특성",0,1,""):Components("유효 특성",targets.Select(x=>20.0/targets.Length).ToArray(),targets.Select((x,i)=>values[i].HasValue?(double?)Fraction(values[i].Value,x.Value):null).ToArray(),string.Join("   ",targets.Select(x=>TalentName(x.Key)+" "+CodexChat.S(talents,x.Key)+" / "+x.Value))));
  bool weaponsKnown=snapshot.TryGetValue("weapons",out raw)&&raw!=null;var weapons=AccountMerge.Equipped(snapshot,"weapons",key);var weapon=weapons.Length==1?weapons[0]:null;double? wl=weapon==null?null:Number(weapon,"level"),wa=weapon==null?null:Number(weapon,"ascension");parts.Add(!weaponsKnown||weapons.Length>1?Part("무기",15,null,Locale.T("미수집")):weapon==null?Part("무기",15,0,Locale.T("확인된 장착 장비 없음")):Components("무기",new[]{9.0,3.0,3.0},new[]{wl.HasValue?(double?)Fraction(wl.Value,90):null,wa.HasValue?(double?)Fraction(wa.Value,6):null,c==null?(double?)null:WeaponAffinity(c,weapon)},GameCatalog.Name(AccountIdentity.Key(weapon))+"   Lv. "+CodexChat.S(weapon,"level")+" / 90"));
  bool known=snapshot.TryGetValue("artifacts",out raw)&&raw!=null;var gear=AccountMerge.Equipped(snapshot,"artifacts",key);string[] slots={"flower","plume","sands","goblet","circlet"};bool unique=gear.All(x=>slots.Contains(CodexChat.S(x,"slotKey")))&&gear.Select(x=>CodexChat.S(x,"slotKey")).Distinct().Count()==gear.Length;known=known&&unique;
  var scores=gear.Select(x=>BuildAnalysis.Score(x,c==null?new string[0]:c.Useful)).ToArray();double? rolls=c!=null&&known&&scores.All(x=>x.UsefulMinimum.HasValue)?(double?)(gear.Sum(x=>WeightedRolls(x,c))/100.0):null;
  parts.Add(Part("성유물 유효 옵션",20,rolls.HasValue?(double?)(rolls.Value/c.Rolls):null,rolls.HasValue?rolls.Value.ToString("0.0")+" / "+c.Rolls.ToString("0.0")+Locale.T(c.UsefulWeights!=null?" 가중 유효 롤":" 유효 롤"):Locale.T(c==null?"평가 기준 미확인":"부옵션 미수집")));
  double mains=0;bool mainKnown=known;foreach(string slot in new[]{"sands","goblet","circlet"}){var item=gear.FirstOrDefault(x=>CodexChat.S(x,"slotKey")==slot);if(item==null)continue;if(!item.ContainsKey("mainStatKey")||item["mainStatKey"]==null){mainKnown=false;continue;}if(c!=null)mains+=MainAffinity(c,slot,CodexChat.S(item,"mainStatKey"));}
  parts.Add(Part("성유물 주옵션",15,mainKnown&&c!=null?(double?)(mains/3):null,c==null?Locale.T("평가 기준 미확인"):mains.ToString("0.##")+" / 3"));
  bool setsKnown=known&&gear.All(x=>x.ContainsKey("setKey")&&x["setKey"]!=null);int pieces=gear.Where(x=>c!=null&&c.Sets.Contains(CodexChat.S(x,"setKey"))).GroupBy(x=>CodexChat.S(x,"setKey")).Select(x=>x.Count()).DefaultIfEmpty(0).Max();if(c!=null&&c.Pair!=null&&c.Pair.Length==2)pieces=Math.Max(pieces,c.Pair.Sum(set=>Math.Min(2,gear.Count(x=>CodexChat.S(x,"setKey")==set))));parts.Add(Part("성유물 세트",10,setsKnown&&c!=null?(double?)(c.Automatic?SetAffinity(c,gear):Fraction(pieces,4)):null,c==null?Locale.T("평가 기준 미확인"):c.Automatic?Locale.T("장착 세트의 활성 효과와 유효 속성을 비교합니다."):string.Join(" / ",c.Sets.Select(x=>GameCatalog.Name(x)))+(c.Pair!=null?"   "+string.Join(" + ",c.Pair.Select(x=>GameCatalog.Name(x))):"")+"   "+pieces+" / 4"));
  var levels=gear.Select(x=>Number(x,"level")).ToArray();parts.Add(Part("성유물 강화",5,known&&levels.All(x=>x.HasValue)?(double?)(levels.Sum(x=>Fraction(x.Value,20))/5):null,gear.Length+" / 5"));
  result.Parts=parts.ToArray();result.Known=parts.Sum(x=>x.Known);result.Coverage=parts.Sum(x=>x.Coverage);result.Total=result.Coverage>=100-1e-9?(double?)Math.Round(result.Known,1):null;return result;
 }
 static double WeightedRolls(Dictionary<string,object> item,BuildCriterion c){return c.Useful.Sum(key=>{var score=BuildAnalysis.Score(item,new[]{key});double weight;return (score.UsefulMinimum??0)*(c.UsefulWeights!=null&&c.UsefulWeights.TryGetValue(key,out weight)?weight:1);});}
 static double WeaponAffinity(BuildCriterion c,Dictionary<string,object> weapon){double value;return c.Automatic&&c.WeaponFit!=null?(c.WeaponFit.TryGetValue(AccountIdentity.Key(weapon),out value)?Fraction(value,1):0):c.Weapons.Contains(AccountIdentity.Key(weapon))?1:0;}
 static double MainAffinity(BuildCriterion c,string slot,string key){Dictionary<string,double> values;double value;return c.Automatic&&c.MainWeights!=null&&c.MainWeights.TryGetValue(slot,out values)?(values.TryGetValue(key,out value)?Fraction(value,1):0):(slot=="sands"?c.Sands:slot=="goblet"?c.Goblet:c.Circlet).Contains(key)?1:0;}
 static double SetAffinity(BuildCriterion c,Dictionary<string,object>[] gear){double score=0;foreach(var group in gear.GroupBy(x=>{string set=CodexChat.S(x,"setKey");return set.Length>0?set:AccountIdentity.Key(x);})){Dictionary<string,double> effects;if(!c.SetAffinities.TryGetValue(group.Key,out effects))continue;double two,four;effects.TryGetValue("2",out two);effects.TryGetValue("4",out four);if(group.Count()>=4)score+=.5*(two+four);else if(group.Count()>=2)score+=.5*two;}return Fraction(score,1);}
 internal static string TalentName(string key){return Locale.T(key=="auto"?"일반 공격":key=="skill"?"원소전투 스킬":"원소폭발");}
 internal static Color ColorFor(double? score){return !score.HasValue?Color.FromRgb(155,167,186):score>=85?Color.FromRgb(108,222,182):score>=65?Color.FromRgb(121,186,244):score>=40?Color.FromRgb(240,190,110):Color.FromRgb(235,133,144);}
 internal static FrameworkElement View(CharacterBuildScore score){var body=new StackPanel();body.Children.Add(Summary(score));body.Children.Add(Breakdown(score));return body;}
 internal static FrameworkElement Summary(CharacterBuildScore score){
  double? shown=score.Total??(score.Coverage>0?(double?)(Math.Floor(score.Known*10+1e-9)/10):null),percent=shown;var body=new StackPanel();var headline=new StackPanel{Orientation=Orientation.Horizontal};var value=new TextBlock{Text=shown.HasValue?(score.Total.HasValue?"":"≥ ")+shown.Value.ToString("0.#"):"—",FontSize=48,FontWeight=FontWeights.Bold,Foreground=new SolidColorBrush(ColorFor(percent)),Margin=new Thickness(0,0,8,0)};headline.Children.Add(value);headline.Children.Add(new TextBlock{Text="/ 100",FontSize=16,Foreground=Brushes.LightGray,VerticalAlignment=VerticalAlignment.Bottom,Margin=new Thickness(0,0,0,10)});body.Children.Add(headline);
  body.Children.Add(PanelUi.Meter(Locale.T("육성 점수"),!score.Total.HasValue?Locale.Format("확인 점수 · {0}점 미확인",(100-score.Coverage).ToString("0.#")):Locale.T(score.Total>=85?"목표에 근접":score.Total>=65?"육성 진행 중":"육성 보완 필요"),percent,ColorFor(percent)));
  return body;
 }
 internal static FrameworkElement Breakdown(CharacterBuildScore score){
  var breakdown=new StackPanel();foreach(var part in score.Parts)breakdown.Children.Add(PanelUi.Meter(Locale.T(part.Name),part.Maximum==0?Locale.T("해당 없음"):part.Coverage>0?(part.Points.HasValue?"":"≥ ")+(part.Points.HasValue?part.Known:Math.Floor(part.Known*10+1e-9)/10).ToString("0.#")+" / "+part.Maximum:Locale.T("미수집"),part.Coverage>0&&part.Maximum>0?(double?)(part.Known/part.Maximum*100):null,ColorFor(part.Coverage>0&&part.Maximum>0?(double?)(part.Known/part.Maximum*100):null),part.Detail,part.Detail));
  if(score.Criterion!=null){breakdown.Children.Add(PanelUi.Text(score.Criterion.Name,true));breakdown.Children.Add(PanelUi.Details(Locale.T("산출식과 기준"),PanelUi.Text((score.Criterion.Automatic?Locale.T("자동 기준은 원본의 옵션 가중치·대표 계산의 특성 사용·무기 부옵션·세트 효과에서 도출합니다. 적합성은 속성 기준의 추정이며 파티별 최적 세팅이나 조건부 효과의 실제 발동을 보장하지 않습니다. "):"")+Locale.T("성유물 50 + 레벨·돌파 15 + 유효 특성 20 + 무기 15. 유효 특성이 없는 역할에서는 특성 배점을 레벨·돌파로 합산합니다. 각 항목은 목표 대비 달성률로 계산하고 100%에서 제한합니다. 유효 롤은 선택 옵션 RV에 가중치(기본 1)를 적용한 합 ÷ 100으로 최대치 부옵션 1회를 1롤로 환산하며 반올림 범위의 하한을 사용합니다. 특성은 별자리 보너스를 제외한 레벨입니다. 별자리·전용 무기·재련 구매는 요구하지 않습니다. 미수집 항목이 있으면 확인된 점수의 하한을 ≥로 표시하며 100점으로 환산하지 않습니다. 전투 피해량이나 원충 충족 판정은 아닙니다."),true),PanelUi.Text(score.Criterion.Source+"\n"+score.Criterion.Checked,true)));}
  return PanelUi.InlineDetails(Locale.T("점수 상세"),breakdown);
 }
}
