using System;
using System.Collections.Generic;
using System.Linq;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Media;

internal static class CharacterInventory {
 static Brush Brush(string hex){return new SolidColorBrush((Color)ColorConverter.ConvertFromString(hex));}
 internal static Color Element(Dictionary<string,object> item){string e=AccountIdentity.CharacterField(item,"element");return (Color)ColorConverter.ConvertFromString(new[]{"바람","Anemo"}.Contains(e)?"#70D4B8":new[]{"물","Hydro"}.Contains(e)?"#66B4F1":new[]{"불","Pyro"}.Contains(e)?"#F19376":new[]{"번개","Electro"}.Contains(e)?"#BB9CEA":new[]{"얼음","Cryo"}.Contains(e)?"#9EDAE2":new[]{"풀","Dendro"}.Contains(e)?"#B1CC72":"#DCC082");}
 static TextBlock Label(string value,double size=14){return new TextBlock{Text=value,FontSize=size,Foreground=Brushes.White,TextWrapping=TextWrapping.Wrap,Margin=new Thickness(0,0,0,6)};}
 internal static FrameworkElement Detail(Dictionary<string,object> snapshot,Dictionary<string,object> character,string name,Action<string> plan,Action<string> ask,Action<string> review,Action refresh){
  string key=AccountIdentity.Key(character);var criterion=CharacterBuild.Read(Setup.DataFolder,character);var score=CharacterBuild.Evaluate(snapshot,character,criterion);var effective=score.Criterion;var body=new StackPanel();body.SetValue(System.Windows.Documents.TextElement.ForegroundProperty,Brushes.White);
  var hero=new Grid();hero.ColumnDefinitions.Add(new ColumnDefinition{Width=new GridLength(150)});hero.ColumnDefinitions.Add(new ColumnDefinition());var portrait=new Image{Height=150,Width=150,Stretch=Stretch.Uniform,VerticalAlignment=VerticalAlignment.Top};AccountIdentity.Portrait(portrait,character,320);hero.Children.Add(portrait);var summary=new StackPanel{Margin=new Thickness(16,0,0,0)};summary.Children.Add(Label(name,24));summary.Children.Add(Label(AccountIdentity.CharacterField(character,"element")+"   Lv. "+CodexChat.S(character,"level")+"   C"+CodexChat.S(character,"constellation")+"   "+Locale.T("돌파")+" "+CodexChat.S(character,"ascension"),13));summary.Children.Add(CharacterBuild.Summary(score));Grid.SetColumn(summary,1);hero.Children.Add(summary);body.Children.Add(hero);body.Children.Add(CharacterBuild.Breakdown(score));
  var talents=new System.Windows.Controls.Primitives.UniformGrid{Columns=3,Margin=new Thickness(0,8,0,16)};object raw;var talent=character.TryGetValue("talent",out raw)?CodexChat.Map(raw):new Dictionary<string,object>();foreach(string field in new[]{"auto","skill","burst"}){var t=new StackPanel();t.Children.Add(Label(CharacterBuild.TalentName(field),12));string value=CodexChat.S(talent,field);t.Children.Add(Label(value.Length==0?Locale.T("미수집"):value,23));talents.Children.Add(t);}body.Children.Add(talents);
  if(talent.Count<3&&character.TryGetValue("observedSkills",out raw))body.Children.Add(PanelUi.Details(Locale.T("HoYoLAB 표시 특성"),PanelUi.Text(string.Join("\n",CodexChat.Items(raw).Select(x=>CodexChat.S(x,"name")+"   "+CodexChat.S(x,"level"))),true)));
  if(character.TryGetValue("finalStats",out raw)&&CodexChat.Map(raw).Count>0){var stats=new System.Windows.Controls.Primitives.UniformGrid{Columns=2};foreach(var stat in CodexChat.Map(raw)){var row=PanelUi.Row(GameCatalog.Name(stat.Key),Label(Convert.ToDouble(stat.Value).ToString("0.##")+(stat.Key.EndsWith("_")?"%":""),14));row.Margin=new Thickness(0,0,16,8);stats.Children.Add(row);}body.Children.Add(PanelUi.Details(Locale.T("능력치"),stats));}
  var planning=PanelUi.Button(Locale.T("육성 계획"));planning.Click+=(s,e)=>{if(plan!=null)plan(key);};var guide=PanelUi.Button(Locale.T("공략 보기 ↗"));guide.Click+=(s,e)=>System.Diagnostics.Process.Start(new System.Diagnostics.ProcessStartInfo("https://keqingmains.com/?s="+Uri.EscapeDataString(AccountIdentity.Name(character,null,"en"))){UseShellExecute=true});var question=PanelUi.Button(Locale.T("공략 질문"));question.Click+=(s,e)=>{if(ask!=null)ask(Locale.Format("{0} (계정 식별자: {1})의 build_analysis와 역할별 평가 기준을 확인해 개선 순서를 알려줘. 최신 KQM 자료와 보유 장비를 검토하고 미수집 정보를 추측하지 마.",name,key));};var compare=PanelUi.Button(Locale.T("육성 비교"));compare.Click+=(s,e)=>{if(review!=null)review(key);};body.Children.Add(PanelUi.Actions(planning,guide,question,compare));
  body.Children.Add(PanelUi.Details(Locale.T("평가 기준"),()=>Editor(character,criterion,refresh)));
  foreach(string kind in new[]{"weapons","artifacts"}){bool known=snapshot.TryGetValue(kind,out raw)&&raw!=null;var equipped=AccountMerge.Equipped(snapshot,kind,key);var gearBody=new WrapPanel();foreach(var item in equipped){string asset=AccountIdentity.Key(item)+(kind=="artifacts"?":"+CodexChat.S(item,"slotKey"):"");var content=new StackPanel();var image=new Image{Height=48,Width=48,HorizontalAlignment=HorizontalAlignment.Left};AccountIdentity.Portrait(image,item);content.Children.Add(image);var gearName=Label(AccountIdentity.Name(item,null),14);if(kind=="artifacts")gearName.Height=36;content.Children.Add(gearName);content.Children.Add(Label("Lv. "+CodexChat.S(item,"level")+(kind=="weapons"?"   R"+CodexChat.S(item,"refinement")+"   "+Locale.T("돌파")+" "+CodexChat.S(item,"ascension"):""),12));
   if(kind=="artifacts"){var main=Label(GameCatalog.Name(CodexChat.S(item,"mainStatKey")),14);main.Height=36;content.Children.Add(main);object stats;if(item.TryGetValue("substats",out stats))foreach(var stat in CodexChat.Items(stats)){bool useful=effective!=null&&effective.Useful.Contains(CodexChat.S(stat,"key"));var row=PanelUi.Row(GameCatalog.Name(CodexChat.S(stat,"key")),Label(CodexChat.S(stat,"value")+(CodexChat.S(stat,"key").EndsWith("_")?"%":""),13));row.Margin=new Thickness(0,0,0,5);foreach(var label in ((StackPanel)row.Children[0]).Children.OfType<TextBlock>()){label.FontSize=11;label.Foreground=Brushes.LightGray;}if(useful)row.Children.OfType<FrameworkElement>().Last().SetValue(TextBlock.ForegroundProperty,Brush("#F1CC77"));content.Children.Add(row);}var quality=BuildAnalysis.Score(item,effective==null?new string[0]:effective.Useful);content.Tag=quality;}
   var extra=new StackPanel();foreach(var field in new[]{new[]{"rarity","등급"},new[]{"slotKey","부위"},new[]{"lock","잠금"}}){object value;if(item.TryGetValue(field[0],out value)&&value!=null)extra.Children.Add(PanelUi.Row(Locale.T(field[1]),Label(field[0]=="lock"?Locale.T(Equals(value,true)?"잠김":"해제"):GameCatalog.Name(Convert.ToString(value)),12)));}if(content.Tag is ArtifactScore)extra.Children.Add(BuildAnalysis.ScoreView((ArtifactScore)content.Tag));if(extra.Children.Count>0)content.Children.Add(PanelUi.InlineDetails(Locale.T("장비 상세"),extra));if(kind=="weapons"){content.Children.Remove(image);var horizontal=new Grid();horizontal.ColumnDefinitions.Add(new ColumnDefinition{Width=new GridLength(64)});horizontal.ColumnDefinitions.Add(new ColumnDefinition());horizontal.Children.Add(image);Grid.SetColumn(content,1);horizontal.Children.Add(content);var weaponCard=new Border{Child=horizontal,Padding=new Thickness(12),Margin=new Thickness(0,0,0,8),Background=Brush("#293138"),CornerRadius=PanelUi.Corners};gearBody.Children.Add(weaponCard);continue;}var card=new Border{Child=content,Padding=new Thickness(12),Margin=new Thickness(0,0,8,8),Width=kind=="artifacts"?158:double.NaN,MinWidth=148,Background=Brush("#293138"),CornerRadius=PanelUi.Corners};gearBody.Children.Add(card);
  }if(kind=="artifacts")gearBody.SizeChanged+=(s,e)=>{int columns=Math.Min(5,Math.Max(1,(int)((gearBody.ActualWidth+8)/166)));foreach(FrameworkElement card in gearBody.Children)card.Width=Math.Max(148,(gearBody.ActualWidth-8*columns)/columns);};body.Children.Add(PanelUi.Section(Locale.T(kind=="weapons"?"무기":"성유물"),!known?(UIElement)PanelUi.Text(Locale.T("미수집"),true):equipped.Length==0?(UIElement)PanelUi.Text(Locale.T("확인된 장착 장비 없음"),true):gearBody));}
  return body;
 }
 static FrameworkElement Editor(Dictionary<string,object> character,BuildCriterion criterion,Action refresh){
  var c=criterion??new BuildCriterion{Name="",Level=90,Rolls=25,Talents=new Dictionary<string,int>(),Useful=new string[0],Sands=new string[0],Goblet=new string[0],Circlet=new string[0],Sets=new string[0],Weapons=new string[0]};var body=new StackPanel();var name=new TextBox{Text=c.Name};body.Children.Add(PanelUi.InputField(Locale.T("역할"),name));var level=new TextBox{Text=c.Level.ToString()};body.Children.Add(PanelUi.InputField(Locale.T("목표 레벨"),level));var talentFields=new Dictionary<string,TextBox>();var talentRow=new System.Windows.Controls.Primitives.UniformGrid{Columns=3};foreach(string key in new[]{"auto","skill","burst"}){int target;c.Talents.TryGetValue(key,out target);var field=new TextBox{Text=target.ToString(),Margin=new Thickness(0,0,8,0)};talentFields[key]=field;talentRow.Children.Add(PanelUi.InputField(CharacterBuild.TalentName(key),field));}body.Children.Add(talentRow);talentRow.ToolTip=Locale.T("평가에서 제외할 특성은 0으로 설정합니다.");
  var options=new Dictionary<string,List<CheckBox>>();foreach(string group in new[]{"Useful","Sands","Goblet","Circlet"}){string[] selected=group=="Useful"?c.Useful:group=="Sands"?c.Sands:group=="Goblet"?c.Goblet:c.Circlet;var checks=new List<CheckBox>();var row=new WrapPanel();var available=group=="Useful"?BuildAnalysis.StatKeys:BuildAnalysis.StatKeys.Concat(new[]{"anemo_dmg_","hydro_dmg_","pyro_dmg_","electro_dmg_","cryo_dmg_","dendro_dmg_","geo_dmg_","physical_dmg_","heal_"}).ToArray();foreach(var stat in available){var check=new CheckBox{Content=GameCatalog.Name(stat),Tag=stat,IsChecked=selected.Contains(stat),Margin=new Thickness(0,0,12,8)};row.Children.Add(check);checks.Add(check);}options[group]=checks;body.Children.Add(PanelUi.Details(Locale.T(group=="Useful"?"유효 부옵션":group=="Sands"?"시계 주옵션":group=="Goblet"?"성배 주옵션":"왕관 주옵션"),row));}
  var rolls=new TextBox{Text=c.Rolls.ToString()};body.Children.Add(PanelUi.InputField(Locale.T("목표 유효 롤 수"),rolls));
  var all=GameCatalog.AssetKeys().ToArray();var sets=all.Where(x=>x.Contains(":" )).Select(x=>x.Split(':')[0]).Distinct().OrderBy(x=>GameCatalog.Name(x)).ToArray();var weapons=all.Where(x=>!x.Contains(":")&&GameCatalog.CharacterField(x,"rarity")=="").OrderBy(x=>GameCatalog.Name(x)).ToArray();
  var setChecks=new List<CheckBox>();var weaponChecks=new List<CheckBox>();foreach(bool set in new[]{true,false}){var row=new WrapPanel();foreach(string key in set?sets:weapons){var check=new CheckBox{Content=GameCatalog.Name(key),Tag=key,IsChecked=(set?c.Sets:c.Weapons).Contains(key),Margin=new Thickness(0,0,12,8)};row.Children.Add(check);(set?setChecks:weaponChecks).Add(check);}body.Children.Add(PanelUi.Details(Locale.T(set?"추천 4세트":"적합한 무기"),row));}
  var pair=new List<ComboBox>();var pairRow=new System.Windows.Controls.Primitives.UniformGrid{Columns=2};for(int i=0;i<2;i++){var choice=new ComboBox{Margin=new Thickness(0,0,8,0)};choice.Items.Add(new ComboBoxItem{Content=Locale.T("없음"),Tag=""});foreach(string key in sets)choice.Items.Add(new ComboBoxItem{Content=GameCatalog.Name(key),Tag=key});choice.SetResourceReference(FrameworkElement.StyleProperty,"OptionsCombo");choice.SelectedIndex=0;if(c.Pair!=null&&c.Pair.Length==2)choice.SelectedItem=choice.Items.OfType<ComboBoxItem>().FirstOrDefault(x=>(string)x.Tag==c.Pair[i])??choice.Items[0];pair.Add(choice);pairRow.Children.Add(choice);}body.Children.Add(PanelUi.Details(Locale.T("2세트 조합"),pairRow));var source=new TextBox{Text=c.Source??""};body.Children.Add(PanelUi.InputField(Locale.T("참고 자료"),source));var status=PanelUi.Text("",true);var save=PanelUi.Button(Locale.T("기준 저장"));save.Click+=(s,e)=>{try{var value=new BuildCriterion{FavoniusCritical=c.FavoniusCritical,Name=name.Text.Trim(),Level=int.Parse(level.Text),Rolls=double.Parse(rolls.Text),Talents=talentFields.ToDictionary(x=>x.Key,x=>int.Parse(x.Value.Text)),Useful=options["Useful"].Where(x=>x.IsChecked==true).Select(x=>(string)x.Tag).ToArray(),Sands=options["Sands"].Where(x=>x.IsChecked==true).Select(x=>(string)x.Tag).ToArray(),Goblet=options["Goblet"].Where(x=>x.IsChecked==true).Select(x=>(string)x.Tag).ToArray(),Circlet=options["Circlet"].Where(x=>x.IsChecked==true).Select(x=>(string)x.Tag).ToArray(),Pair=pair.Select(x=>(string)((ComboBoxItem)x.SelectedItem).Tag).Where(x=>x.Length>0).ToArray(),Sets=setChecks.Where(x=>x.IsChecked==true).Select(x=>(string)x.Tag).ToArray(),Weapons=weaponChecks.Where(x=>x.IsChecked==true).Select(x=>(string)x.Tag).ToArray(),Source=source.Text.Trim(),Checked=DateTime.Now.ToString("yyyy-MM-dd")};CharacterBuild.Save(Setup.DataFolder,AccountIdentity.Key(character),value);refresh();}catch(Exception error){status.Text=Locale.T(error is FormatException?"숫자를 확인해 주세요.":"평가 기준을 확인해 주세요.");}};body.Children.Add(PanelUi.Actions(save));body.Children.Add(status);return body;
 }
}
