using System;
using System.IO;
using System.Linq;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Media;
using System.Windows.Media.Imaging;
internal static class ChatAttachmentTests {
 static void Check(bool value,string reason){if(!value)throw new Exception("Chat attachments: "+reason);}
 internal static void Run(){
  string root=Path.Combine(Path.GetTempPath(),"chat-images-test-"+Guid.NewGuid().ToString("N"));Directory.CreateDirectory(root);
  try{
   byte[] pixels=new byte[80*240*4];for(int i=0;i<pixels.Length;i+=4){pixels[i]=70;pixels[i+1]=130;pixels[i+2]=220;pixels[i+3]=255;}var image=BitmapSource.Create(80,240,96,96,PixelFormats.Bgra32,null,pixels,320);image.Freeze();
   string file=Path.Combine(root,"portrait.png");var encoder=new PngBitmapEncoder();encoder.Frames.Add(BitmapFrame.Create(image));using(var stream=File.Create(file))encoder.Save(stream);
   object[] input=CodexChat.PrepareInput("Look at this",new[]{file});var snapshots=ChatAttachments.Snapshot(input,root);ChatAttachments.Record(root,"thread","turn-one",snapshots);var sent=CodexChat.ReadUserContent(input,snapshots);var restored=CodexChat.ReadUserContent(CatheryneTools.Json().DeserializeObject(CatheryneTools.Json().Serialize(input)),ChatAttachments.ForTurn(root,"thread","turn-one"));
   Check(sent.Attachments.Count==1&&sent.Attachments[0].IsImage&&sent.Attachments[0].Name=="portrait.png"&&restored.Attachments[0].Source==sent.Attachments[0].Source,"image identity and source survive serialized history");
   Check(sent.Attachments[0].Source!=file&&CodexChat.S(CodexChat.Items(input).Last(),"path")==file&&ChatAttachments.Snapshot(input,root)[0].Source==sent.Attachments[0].Source,"image snapshots preserve the model's original capture path and reuse their archive");
   byte[] alternate=(byte[])pixels.Clone();alternate[0]=180;var changed=BitmapSource.Create(80,240,96,96,PixelFormats.Bgra32,null,alternate,320);var newer=new PngBitmapEncoder();newer.Frames.Add(BitmapFrame.Create(changed));using(var stream=File.Create(file))newer.Save(stream);var changedSnapshots=ChatAttachments.Snapshot(input,root);ChatAttachments.Record(root,"thread","turn-two",changedSnapshots);Check(changedSnapshots[0].Source!=snapshots[0].Source&&ChatAttachments.ForTurn(root,"thread","turn-one")[0].Source==snapshots[0].Source,"replacing the same original filename does not change an earlier turn's image");var converted=CodexChat.ReadUserContent(new[]{new System.Collections.Generic.Dictionary<string,object>{{"type","image"},{"url","https://example.invalid/encoded-image"}}},ChatAttachments.ForTurn(root,"thread","turn-one"));Check(converted.Attachments[0].Name=="portrait.png"&&converted.Attachments[0].Source==snapshots[0].Source,"history image URLs retain the archived attachment and filename");File.Delete(file);
   var decoded=ChatAttachments.Decode(restored.Attachments[0].Source,96);Check(decoded.IsFrozen&&decoded.PixelWidth==32&&decoded.PixelHeight==96,"portrait thumbnail preserves aspect ratio with a bounded decode and survives source deletion");
   File.Move(restored.Attachments[0].Source,restored.Attachments[0].Source+".moved");File.Move(restored.Attachments[0].Source+".moved",restored.Attachments[0].Source);
   var tile=ChatAttachments.Thumbnail(restored.Attachments[0],null,false);tile.Measure(new Size(400,400));tile.Arrange(new Rect(0,0,tile.DesiredSize.Width,tile.DesiredSize.Height));Check(tile.ActualWidth==ChatAttachments.MessageSize&&tile.ActualHeight==ChatAttachments.MessageSize,"transcript thumbnail has the fixed message specification");
   bool removed=false;var composer=(Grid)ChatAttachments.Composer(restored.Attachments[0],null,()=>removed=true);Check(composer.Width==ChatAttachments.ComposerSize,"composer thumbnail uses its own shared specification");composer.Children.OfType<Button>().Last().RaiseEvent(new RoutedEventArgs(Button.ClickEvent));Check(removed,"remove control does not invoke the image preview");
   var pasted=ChatAttachments.Paste(image,root);Check(File.Exists(pasted)&&ChatAttachments.Decode(pasted,96).PixelHeight==96,"clipboard snapshots use the same image storage and decoder");
   var ordered=ChatAttachments.Snapshot(CodexChat.PrepareInput("two",new[]{pasted,changedSnapshots[0].Source}),root);var convertedImages=CodexChat.ReadUserContent(new[]{new System.Collections.Generic.Dictionary<string,object>{{"type","image"},{"url","https://example.invalid/one"}},new System.Collections.Generic.Dictionary<string,object>{{"type","image"},{"url","https://example.invalid/two"}}},ordered);Check(convertedImages.Attachments.Select(x=>x.Source).SequenceEqual(ordered.Select(x=>x.Source)),"multiple converted images retain their original order");
   var clipboard=new DataObject();clipboard.SetData(DataFormats.Bitmap,image);var pastedFiles=ChatAttachments.ReadPaste(clipboard,root);Check(pastedFiles.Length==1&&ChatAttachments.Decode(pastedFiles[0],96).PixelHeight==96,"bitmap-only clipboard becomes a saved attachment");
   var pngOnly=new DataObject();pngOnly.SetData("PNG",new MemoryStream(File.ReadAllBytes(pasted)));Check(ChatAttachments.ReadPaste(pngOnly,root).Length==1,"PNG stream clipboard is supported");
   var textOnly=new DataObject(DataFormats.UnicodeText,"ordinary text");Check(!ChatAttachments.CanPaste(textOnly)&&ChatAttachments.ReadPaste(textOnly,root)==null,"plain text retains native text paste");
   var drop=new DataObject();string note=Path.Combine(root,"note.md");File.WriteAllText(note,"notes");drop.SetData(DataFormats.FileDrop,new[]{pasted,note});drop.SetData(DataFormats.UnicodeText,"paths should not enter draft");Check(ChatAttachments.ReadPaste(drop,root).SequenceEqual(new[]{pasted,note}),"file drop takes precedence and retains ordered file attachments");
   DropRouting(pasted,note,root);
   drop.SetData(DataFormats.FileDrop,new[]{pasted,Path.Combine(root,"missing.png")});bool missing=false;try{ChatAttachments.ReadPaste(drop,root);}catch(FileNotFoundException){missing=true;}Check(missing,"mixed invalid file batch is rejected before any insertion");
   string unsupported=Path.Combine(root,"unsupported.exe");File.WriteAllText(unsupported,"test");drop.SetData(DataFormats.FileDrop,new[]{unsupported});bool invalid=false;try{ChatAttachments.ReadPaste(drop,root);}catch(InvalidOperationException){invalid=true;}Check(invalid,"unsupported copied files do not silently become text");
   string inline="data:image/png;base64,"+Convert.ToBase64String(File.ReadAllBytes(pasted));var historical=CodexChat.ReadUserContent(new[]{new System.Collections.Generic.Dictionary<string,object>{{"type","image"},{"url",inline}}});Check(historical.Attachments[0].IsImage&&historical.Attachments[0].Source==inline&&ChatAttachments.Decode(inline,96).PixelHeight==96,"stored image content retains its actual image source");
   object[] retryInput=new object[]{new System.Collections.Generic.Dictionary<string,object>{{"type","text"},{"text","original question"}},new System.Collections.Generic.Dictionary<string,object>{{"type","text"},{"text","Attached file: note.md\noriginal contents"}},new System.Collections.Generic.Dictionary<string,object>{{"type","localImage"},{"path",file}}};
   string[] retryFiles=ChatAttachments.RestoreInput(retryInput,CodexChat.ReadUserContent(retryInput,snapshots),root);Check(retryFiles.Length==2&&File.ReadAllText(retryFiles[0])=="original contents"&&File.ReadAllBytes(retryFiles[1]).SequenceEqual(File.ReadAllBytes(snapshots[0].Source)),"editing restores original text attachment contents and archived images even when the source was deleted");
   ChatAttachments.Inherit(root,"thread","fork");Check(ChatAttachments.ForTurn(root,"fork","turn-one")[0].Source==snapshots[0].Source,"fork history retains the same immutable image archive");
   var latest=new System.Collections.Generic.Dictionary<string,object>{{"id","last"},{"status","interrupted"}};var prior=new System.Collections.Generic.Dictionary<string,object>{{"id","previous"},{"status","completed"}};
   Check(CodexChat.InterruptedPlan("source","last",new[]{latest,prior}).PreviousTurn=="previous"&&CodexChat.InterruptedPlan("source","last",new[]{latest}).PreviousTurn==null,"fork boundary is before the interrupted request, including the first-turn case");
   foreach(string status in new[]{"completed","failed","inProgress"}){latest["status"]=status;bool denied=false;try{CodexChat.InterruptedPlan("source","last",new[]{latest,prior});}catch(InvalidOperationException){denied=true;}Check(denied,"only an interrupted latest request is editable: "+status);}latest["status"]="interrupted";
   bool stale=false;try{CodexChat.InterruptedPlan("source","older",new[]{latest,prior});}catch(InvalidOperationException){stale=true;}Check(stale,"a stale earlier request cannot be edited");
   bool rejected=false;try{ChatAttachments.Decode("https://example.invalid/attachment.png",96);}catch(InvalidDataException){rejected=true;}Check(rejected,"remote history links do not cause automatic downloads");
   var mixed=CodexChat.ReadUserContent(new object[]{new System.Collections.Generic.Dictionary<string,object>{{"type","text"},{"text","Attached file: literal\nmessage"}},new System.Collections.Generic.Dictionary<string,object>{{"type","text"},{"text","Attached file: notes.md\ncontents"}},new System.Collections.Generic.Dictionary<string,object>{{"type","localImage"},{"path",pasted}}});Check(mixed.Text=="Attached file: literal\nmessage"&&mixed.Files.SequenceEqual(new[]{"notes.md","이미지.png"}),"text attachment names and literal user text retain their meaning");
  }finally{Directory.Delete(root,true);}
 }
 static DragEventArgs Drag(IDataObject data,DragDropEffects allowed,DependencyObject target,RoutedEvent routed){
  var args=(DragEventArgs)Activator.CreateInstance(typeof(DragEventArgs),System.Reflection.BindingFlags.Instance|System.Reflection.BindingFlags.Public|System.Reflection.BindingFlags.NonPublic,null,new object[]{data,System.Windows.DragDropKeyStates.None,allowed,target,new Point(10,10)},null);args.RoutedEvent=routed;((UIElement)target).RaiseEvent(args);return args;
 }
 static void DropRouting(string image,string note,string root){
  var owner=new Window();var input=new TextBox{Text="keep draft"};var normal=Brushes.Gray;var surface=new Border{Child=input,BorderBrush=normal};owner.Content=surface;int insertions=0,errors=0;string[] received=null;
  new ChatAttachmentDrop(owner,surface,data=>{received=ChatAttachments.ReadPaste(data,root);insertions++;return true;},error=>errors++);
  var files=new DataObject();files.SetData(DataFormats.FileDrop,new[]{image,note});files.SetData(DataFormats.UnicodeText,"do not insert paths");
  var over=Drag(files,DragDropEffects.Copy|DragDropEffects.Move,input,DragDrop.PreviewDragOverEvent);Check(over.Handled&&over.Effects==DragDropEffects.Copy&&surface.BorderBrush!=normal,"a drag over the text input offers copy and highlights the entire composer");
  var dropped=Drag(files,DragDropEffects.Copy,input,DragDrop.PreviewDropEvent);Check(dropped.Handled&&dropped.Effects==DragDropEffects.Copy&&insertions==1&&received.SequenceEqual(new[]{image,note})&&input.Text=="keep draft"&&surface.BorderBrush==normal,"file drop routes through the composer and attachment reader without replacing text");
  var move=Drag(files,DragDropEffects.Move,input,DragDrop.PreviewDropEvent);Check(move.Handled&&move.Effects==DragDropEffects.None&&insertions==1,"attachment drop never moves or removes the original files");
  var text=new DataObject(DataFormats.UnicodeText,"ordinary text");Check(!Drag(text,DragDropEffects.Copy,input,DragDrop.PreviewDropEvent).Handled,"ordinary text drag retains native editing");
  files.SetData(DataFormats.FileDrop,new[]{image,Path.Combine(root,"missing.png")});over=Drag(files,DragDropEffects.Copy,input,DragDrop.PreviewDragOverEvent);Check(over.Handled&&over.Effects==DragDropEffects.None&&surface.BorderBrush==normal,"invalid file batches do not advertise acceptance");
  dropped=Drag(files,DragDropEffects.Copy,input,DragDrop.PreviewDropEvent);Check(dropped.Handled&&dropped.Effects==DragDropEffects.None&&insertions==1&&errors==1,"invalid file batches report an error without partial attachments or path text");
  files.SetData(DataFormats.FileDrop,new[]{image});Drag(files,DragDropEffects.Copy,input,DragDrop.PreviewDragEnterEvent);Drag(files,DragDropEffects.Copy,input,DragDrop.PreviewDragLeaveEvent);Check(surface.BorderBrush==normal,"leaving the input restores its existing border");
 }

}
