using System;using System.IO;using System.Linq;using System.Collections.Generic;
internal static class CollectionHistoryTests {
 static Dictionary<string,object> M(string value){return CatheryneTools.Json().Deserialize<Dictionary<string,object>>(value);}
 static void Check(bool value,string name){if(!value)throw new Exception("Collection history: "+name);}
 internal static void Run(){
  Check(AchievementProgress.Total(M(@"{""catheryne"":{""achievementSummary"":{""achievement_num"":1234}}}"))==1234,"provider achievement total is projected separately");
  Check(!AchievementProgress.Total(M(@"{}" )).HasValue&&!AchievementProgress.Total(M(@"{""catheryne"":{""achievementSummary"":{""achievement_num"":-1}}}" )).HasValue,"missing or invalid total is never invented");
  Check(InventoryPanel.Capacity(900,900)==35&&InventoryPanel.Capacity(420,360)==6&&InventoryPanel.Capacity(0,0)==1,"page capacity fits full card rows in wide and split layouts");

  var achievementRows=new[]{new AchievementRow{Id=8001,Category=0,Theme="World",State=2},new AchievementRow{Id=8002,Category=0,Theme="World",State=0},new AchievementRow{Id=8100,Category=1,Theme="Travails",State=0}};
  var themeData=M(@"{""catheryne"":{""achievementSummary"":{""achievement_num"":1438,""list"":[{""id"":""0"",""name"":""천지만물"",""finish_num"":760,""percentage"":76,""show_percent"":false,""icon"":""https://act-webstatic.hoyoverse.com/theme.png""},{""id"":""1"",""name"":""속세 순유"",""finish_num"":1,""percentage"":100,""show_percent"":true},{""id"":""999"",""name"":""Future"",""finish_num"":2,""percentage"":50,""show_percent"":true}]}}}");
  var projected=AchievementProgress.Themes(themeData,achievementRows);Check(projected.Count==3&&projected[0].OfficialFinish==760&&projected[0].Verified==1&&projected[0].HasIcon&&!projected[0].ShowPercent,"official category count, image and count presentation are preserved");Check(projected[1].Percent==100&&projected[1].Verified==0&&achievementRows[2].State==0,"complete theme aggregate never invents completed achievement IDs");Check(projected[2].CatalogCount==0&&projected[2].OfficialFinish==2,"new official themes survive before the public catalog catches up");
  var before=M(@"{""characters"":[{""key"":""Wanderer"",""level"":80,""talent"":{""auto"":8}}],""weapons"":[{""key"":""FavoniusWarbow"",""level"":80,""location"":""Wanderer""}],""materialInventory"":[{""itemId"":""202"",""name"":""Mora"",""quantity"":20,""observedAt"":""2026-09-30T00:00:00Z"",""source"":""fixture""}]}");
  var after=M(@"{""characters"":[{""key"":""Wanderer"",""level"":90,""talent"":{""auto"":10}}],""weapons"":[{""key"":""FavoniusWarbow"",""level"":90,""location"":""Wanderer""}],""materialInventory"":[{""itemId"":""202"",""name"":""Mora"",""quantity"":25,""observedAt"":""2026-09-30T00:00:00Z"",""source"":""fixture""}]}");var changes=CollectionHistory.Changes(before,after);Check(changes.Count==3&&changes.Any(x=>CodexChat.S(x,"text").Contains("80 → 90"))&&changes.Any(x=>CodexChat.S(x,"text").Contains("20 → 25")),"levels, talents, equipment and counts produce actual differences");
  Check(CollectionHistory.Changes(after,after).Count==0,"unchanged observations have no fabricated differences");Check(CollectionHistory.Changes(after,M(@"{""characters"":[{""key"":""Wanderer"",""icon"":""new.png""}]}" )).Count==0,"missing fields and cosmetic metadata are not changes");
  string root=Path.Combine(Path.GetTempPath(),"catheryne-history-"+Guid.NewGuid().ToString("N"));Directory.CreateDirectory(root);try{
   var recent=M(@"{""characters"":[{""key"":""Wanderer"",""level"":90}],""weapons"":[],""artifacts"":[],""catheryne"":{""coverage"":{""characters"":""characters"",""weapons"":""equipped"",""artifacts"":""equipped""},""achievementSummary"":{""achievement_num"":100}}}");CollectionHistory.Record(root,new Dictionary<string,object>(),recent);
   var checks=CollectionHistory.Checks(root);Check(CodexChat.S(MaterialInventory.Map(checks,"weapons"),"scope")=="equipped","fresh equipped observations never become full inventory");Check(CollectionHistory.Due(root,DateTime.UtcNow).SequenceEqual(new[]{"materials"}),"recent API checks clear their freshness without requiring a full scan");
   string prior=CodexChat.S(MaterialInventory.Map(checks,"characters"),"observedAt");CollectionHistory.Record(root,new Dictionary<string,object>(),M(@"{""materialInventory"":[],""catheryne"":{""materialObservedAt"":""2020-01-01T00:00:00Z""}}"));checks=CollectionHistory.Checks(root);Check(CodexChat.S(MaterialInventory.Map(checks,"characters"),"observedAt")==prior,"material checks never refresh unrelated characters");Check(CollectionHistory.Due(root,DateTime.UtcNow).Contains("materials"),"importing an old observation does not make it current");
   object raw;Check(CollectionHistory.Read(root).TryGetValue("events",out raw)&&CodexChat.Items(raw).Count()==2,"change history persists across views");
  }finally{Directory.Delete(root,true);}
 }
}
