using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Media;

internal static class EndgamePanel {
 internal static string Title(string mode){return Locale.T(mode=="abyss"?"나선비경":"지맥 제압전");}
 static Dictionary<string,object> D(object v){return CodexChat.Map(v);}
 static string S(Dictionary<string,object> d,string k){return CodexChat.S(d,k);}
 internal static string SlotName(string mode,int slot){return mode=="abyss"?Locale.T(slot==1?"전반":"후반"):Locale.Format("전장 {0}",slot);}
 static TextBox Input(string text=""){return new TextBox{Text=text,MinHeight=36,Padding=new Thickness(10,7,10,7),FontSize=13};}
 static ComboBox Combo(IEnumerable<string> items,int index=0){var c=new ComboBox{MinHeight=36};c.SetResourceReference(FrameworkElement.StyleProperty,"OptionsCombo");foreach(string item in items)c.Items.Add(item);c.SelectedIndex=c.Items.Count>0?Math.Min(index,c.Items.Count-1):-1;return c;}
 internal static string GoalDisplay(string value){foreach(string preset in new[]{"12층 9별","안정적인 클리어"})if(value==preset||value==Locale.T(preset,true))return Locale.T(preset);return value;}
 static int generation;
 static Dictionary<string,object> Enemy(Dictionary<string,object> season,int slot){var enemies=D(season!=null&&season.ContainsKey("enemies")?season["enemies"]:null);string key=new[]{"top","middle","bottom"}[slot-1];return D(enemies.ContainsKey(key)?enemies[key]:null);}
 static string EnemyName(Dictionary<string,object> enemy){return GameCatalog.EnemyName(enemy);}
 static FrameworkElement EnemyRow(Dictionary<string,object> season,string mode,int slot){var row=new DockPanel{Margin=new Thickness(0,0,0,8)};var enemy=mode=="stygian"?Enemy(season,slot):new Dictionary<string,object>();if(S(enemy,"asset")!=""){var image=new Image{Width=38,Height=38,Stretch=Stretch.Uniform,Margin=new Thickness(0,0,10,0),ToolTip=S(enemy,"enemy_name")};GameCatalog.EnemyPortrait(image,S(enemy,"asset"));DockPanel.SetDock(image,Dock.Left);row.Children.Add(image);}var text=PanelUi.Text(SlotName(mode,slot)+(EnemyName(enemy)==""?"":" · "+EnemyName(enemy)));text.Margin=new Thickness(0);text.VerticalAlignment=VerticalAlignment.Center;text.ToolTip=S(enemy,"enemy_name");row.Children.Add(text);return row;}
 internal static IEnumerable<UIElement> SeasonEnemies(Dictionary<string,object> season,string mode,Dictionary<string,object> catalog=null){
  var enemies=D(season.ContainsKey("enemies")?season["enemies"]:null);
  for(int slot=1;slot<=(mode=="stygian"?3:2);slot++){
   var group=new WrapPanel{Margin=new Thickness(0,0,mode=="abyss"?12:0,0)};
   if(mode=="abyss"){var label=PanelUi.Text(SlotName(mode,slot),true);label.Margin=new Thickness(0,0,8,0);label.VerticalAlignment=VerticalAlignment.Center;group.Children.Add(label);}
   Action<Dictionary<string,object>,string> add=(enemy,location)=>{string asset=S(enemy,"asset");if(asset.Length==0)return;string raw=S(enemy,"enemy_name");if(raw.Length==0)raw=S(enemy,"name");string name=GameCatalog.EnemyName(enemy,catalog);var image=new Image{Width=26,Height=26,Stretch=Stretch.Uniform,Margin=new Thickness(0,0,12,0),ToolTip=new TextBlock{Text=location+" · "+name+(name!=raw?"\n"+raw:""),TextWrapping=TextWrapping.Wrap,MaxWidth=320}};System.Windows.Automation.AutomationProperties.SetName(image,location+" · "+name);GameCatalog.EnemyPortrait(image,asset);group.Children.Add(image);};
   if(mode=="stygian")add(Enemy(season,slot),SlotName(mode,slot));
   else{object rows;if(enemies.TryGetValue(slot==1?"top":"bottom",out rows))foreach(var chamber in CodexChat.Items(rows)){object contents;if(chamber.TryGetValue("enemies",out contents))foreach(var enemy in CodexChat.Items(contents))add(enemy,SlotName(mode,slot)+" · "+Locale.Format("{0}번 방",chamber["chamber"]));}}
   if(group.Children.OfType<Image>().Any())yield return group;
  }
 }
 internal static FrameworkElement Party(Dictionary<string,object>[] members,string heading,double? rate=null,double? share=null,FrameworkElement enemyHeading=null){
  members=PartyRoles.Order(members);var body=new StackPanel();var header=new DockPanel{Margin=new Thickness(0,0,0,10)};
  if(rate.HasValue){var value=PanelUi.Text(Locale.Format("픽률 {0}%",rate.Value.ToString("0.0",CultureInfo.CurrentCulture)),true);value.Margin=new Thickness(10,0,0,0);value.VerticalAlignment=VerticalAlignment.Center;DockPanel.SetDock(value,Dock.Right);header.Children.Add(value);}var title=enemyHeading??PanelUi.Text(heading);title.Margin=new Thickness(0);header.Children.Add(title);body.Children.Add(header);
  var memberDetails=new Dictionary<string,Expander>();var details=PanelUi.Details(Locale.T("파티 상세"),()=>{
   var detailBody=new StackPanel();if(rate.HasValue)detailBody.Children.Add(PanelUi.Meter(Locale.T("파티 픽률"),rate.Value.ToString("0.0",CultureInfo.CurrentCulture)+"%",rate,Color.FromRgb(111,201,171)));
   if(share.HasValue)detailBody.Children.Add(PanelUi.Meter(Locale.T("전장 사용 비중"),share.Value.ToString("0.0",CultureInfo.CurrentCulture)+"%",share,Color.FromRgb(142,190,230)));
   if(members.All(m=>m.ContainsKey("buildKnown")&&m.ContainsKey("buildCoverage"))){double known=members.Average(m=>Convert.ToDouble(m["buildKnown"])),coverage=members.Average(m=>Convert.ToDouble(m["buildCoverage"]));detailBody.Children.Add(PanelUi.Meter(Locale.T("육성 상태"),Locale.Format("확인된 육성 {0}/{1}",known.ToString("0.0",CultureInfo.CurrentCulture),coverage.ToString("0.0",CultureInfo.CurrentCulture)),known,Color.FromRgb(213,190,139),Locale.T("육성 점수는 화력이나 클리어 확률이 아닙니다.")));}
   if(!EndgamePlanning.GearVerified(members))detailBody.Children.Add(PanelUi.Text(Locale.T("장비 개체 정보 부족 · 장비 중복 확인 필요"),true));
   foreach(var member in members){var character=D(member["character"]);var item=PanelUi.Details(AccountIdentity.Name(character),()=>{var info=new StackPanel();if(member.ContainsKey("buildCoverage")&&Convert.ToDouble(member["buildCoverage"])<100)info.Children.Add(PanelUi.Text(Locale.T("육성 자료 미확인"),true));info.Children.Add(MemberDetails(member));return info;});memberDetails[AccountIdentity.Key(character)]=item;detailBody.Children.Add(item);}return detailBody;
  });
  body.Children.Add(InventoryCard.Party(members.Select(m=>D(m["character"])).ToArray(),character=>{details.IsExpanded=true;foreach(var item in memberDetails)item.Value.IsExpanded=item.Key==AccountIdentity.Key(character);}));body.Children.Add(details);return body;
 }
 internal static StackPanel Plans(Dictionary<string,object> rec,string mode,Action<int> select,Dictionary<string,object> season=null,Action<int> consult=null){
  var list=new StackPanel();if(!rec.ContainsKey("options"))return list;
  foreach(var plan in CodexChat.Items(rec["options"])){
   int option=Convert.ToInt32(plan["option"]);Func<UIElement> create=()=>{var body=new StackPanel();foreach(var slot in CodexChat.Items(plan["slots"])){int number=Convert.ToInt32(slot["Slot"]);body.Children.Add(Party(CodexChat.Items(slot["Members"]).ToArray(),SlotName(mode,number),Convert.ToDouble(slot["UsageRate"]),Convert.ToDouble(slot["SlotShare"]),mode=="stygian"?EnemyRow(season,mode,number):null));}
    var pick=PanelUi.Button(Locale.T("이 편성 저장…"));pick.Click+=(sender,e)=>select(option);var chat=PanelUi.Button(Locale.T("AI 상담"));chat.IsEnabled=consult!=null;chat.Click+=(sender,e)=>{if(consult!=null)consult(option);};body.Children.Add(PanelUi.FooterActions(new[]{1,1},pick,chat));return body;};list.Children.Add(option==1?(FrameworkElement)PanelUi.Section(Locale.Format("추천 {0}",option),create()):PanelUi.Details(Locale.Format("추천 {0}",option),create));
  }return list;
 }
 static FrameworkElement MemberDetails(Dictionary<string,object> member){var body=new StackPanel();if(member.Count==0){body.Children.Add(PanelUi.Text(Locale.T("없음"),true));return body;}var character=D(member["character"]);body.Children.Add(PanelUi.Text("Lv."+S(character,"level")+" · C"+S(character,"constellation"),true));foreach(string section in new[]{"weapons","artifacts"})foreach(var item in CodexChat.Items(member[section])){body.Children.Add(PanelUi.Text(AccountIdentity.Name(item)+" · Lv."+S(item,"level")+(S(item,"refinement")==""?"":" · R"+S(item,"refinement")),true));string stat=S(item,"mainStatKey");if(stat!="")body.Children.Add(PanelUi.Text(GameCatalog.Name(stat)+(S(item,"mainStatValue")==""?"":" "+S(item,"mainStatValue")),true));object subs;if(item.TryGetValue("substats",out subs))body.Children.Add(PanelUi.Text(string.Join(" · ",CodexChat.Items(subs).Select(x=>GameCatalog.Name(S(x,"key"))+" "+S(x,"value"))),true));}return body;}
 internal static void Show(Window window,DetailPanel detail,string mode,Action<string> ask,bool autoPrepare=true,string dataRoot=null){
  int request=++generation;string root=dataRoot??Setup.DataFolder;var service=new EndgameService(root);var body=new StackPanel();var work=new PanelWorkIndicator();body.Children.Add(work.View);var controls=new StackPanel();body.Children.Add(controls);var goal=Input(mode=="abyss"?Locale.T("12층 9별"):Locale.T("안정적인 클리어"));var difficulty=Combo(Enumerable.Range(1,6).Select(n=>PartyRoles.Difficulty(n)),4);var refreshAccount=new CheckBox{Content=Locale.T("추천 전에 계정 최신화"),Margin=new Thickness(0,0,0,16)};
  string originalGoal=goal.Text,displayedGoal=goal.Text;Action<string> restoreGoal=value=>{originalGoal=value;goal.Text=GoalDisplay(value);displayedGoal=goal.Text;};Func<string> goalValue=()=>goal.Text==displayedGoal?originalGoal:goal.Text;
  goal.ToolTip=Locale.T("저장과 AI 상담에 사용할 메모입니다. 층·별 수·클리어 시간에 따른 추천 필터로 적용되지 않습니다.");System.Windows.Automation.AutomationProperties.SetHelpText(goal,Convert.ToString(goal.ToolTip));difficulty.ToolTip=Locale.T("난이도 1~3은 파티 간 재사용을 허용하고, 4~6은 캐릭터·무기·성유물 중복을 제한합니다. 난이도별 클리어 가능성을 계산하지 않습니다.");
  var recommend=PanelUi.Button(Locale.T("파티 추천"));PanelUi.PrimaryAction(recommend,true);var preparation=PanelUi.Details(Locale.T("출전 설정"),mode=="stygian"?PanelUi.InputField(Locale.T("난이도"),difficulty):PanelUi.Text(Locale.T("12층 · 전반 / 후반"),true),PanelUi.InputField(Locale.T("목표 메모"),goal),refreshAccount,PanelUi.Actions(recommend));bool preparationInitialized=false;var preparationSummary=PanelUi.Text("",true);Action showPreparation=()=>preparationSummary.Text=mode=="stygian"?PartyRoles.Difficulty(difficulty.SelectedIndex+1):Locale.T("12층 · 전반 / 후반");difficulty.SelectionChanged+=(sender,e)=>showPreparation();showPreparation();controls.Children.Add(preparationSummary);controls.Children.Add(preparation);
  var seasonText=PanelUi.Text(Locale.T("불러오는 중…"));var seasonOverview=new WrapPanel();var seasonTime=new ContentControl();string displayedSeason="";Dictionary<string,object> enemyCatalog=null;bool saveFeedback=false;
  body.Children.Insert(0,PanelUi.SeasonHeader(seasonText,seasonOverview,seasonTime));
  Action<Dictionary<string,object>> showSeason=updated=>{
   var season=D(updated["season"]);object raw;var schedule=updated.TryGetValue("schedule",out raw)&&raw!=null?CatheryneTools.Json().Deserialize<CalendarEntry>(CatheryneTools.Json().Serialize(raw)):null;
   var start=schedule!=null&&schedule.Start.HasValue?schedule.Start.Value.ToLocalTime():DateTime.MinValue;
   seasonText.Text=start!=DateTime.MinValue?Locale.Format("{0}년 {1}월 {2}",start.Year,start.Month,Title(mode)):Title(mode);seasonText.ToolTip=S(season,"version");
   seasonTime.Content=schedule!=null?(object)CalendarPanel.Timing(schedule):PanelUi.Text(Locale.T("현재 시즌 미확인"),true);
   string stamp=Convert.ToString(updated["statisticsCurrent"])+S(season,"version")+S(season,"start")+CatheryneTools.Json().Serialize(season.ContainsKey("enemies")?season["enemies"]:null)+(enemyCatalog==null?"":S(enemyCatalog,"revision")+S(D(enemyCatalog["supplement"]),"revision"));if(stamp==displayedSeason)return;displayedSeason=stamp;
   seasonOverview.Children.Clear();if(Equals(updated["statisticsCurrent"],true))foreach(UIElement item in SeasonEnemies(season,mode,enemyCatalog))seasonOverview.Children.Add(item);else seasonOverview.Children.Add(PanelUi.Text(Locale.T("현재 시즌 미확인"),true));
  };
  var plans=new StackPanel();controls.Children.Add(plans);var bestHistory=new StackPanel();controls.Children.Add(bestHistory);var selected=PanelUi.Text("",true);int option=0;var label=Input();var rotation=Input();rotation.AcceptsReturn=true;rotation.TextWrapping=TextWrapping.Wrap;rotation.MinHeight=68;var save=PanelUi.Button(Locale.T("편성 저장"));var saveArea=new StackPanel();saveArea.Children.Add(selected);saveArea.Children.Add(PanelUi.InputField(Locale.T("편성 이름"),label));saveArea.Children.Add(PanelUi.InputField(Locale.T("사이클 메모"),rotation));saveArea.Children.Add(save);var saveForm=PanelUi.Details(Locale.T("편성 저장"),saveArea);controls.Children.Add(saveForm);
  var roster=new Dictionary<string,object>[0];var manualBody=new StackPanel();var manualChoices=new List<ComboBox[]>();for(int s=1;s<=(mode=="abyss"?2:3);s++){manualBody.Children.Add(PanelUi.Text(SlotName(mode,s)));var choices=Enumerable.Range(0,4).Select(i=>Combo(roster.Select(c=>AccountIdentity.Name(c)),i)).ToArray();foreach(var choice in choices){choice.Margin=new Thickness(0,0,0,8);manualBody.Children.Add(choice);}manualChoices.Add(choices);}var manual=PanelUi.Button(Locale.T("직접 편성 저장"));manualBody.Children.Add(manual);saveArea.Children.Add(PanelUi.Details(Locale.T("직접 편성"),manualBody));
  var saved=new StackPanel();controls.Children.Add(saved);var stats=PanelUi.Text(Locale.T("픽률은 해당 파티 전체를 보유한 표본 중 사용한 비율입니다. 전장 사용 비중은 그 파티가 출전한 위치의 분포입니다. 난이도·서버·전체 표본 수·돌파 수준은 미확인입니다. 추천은 픽률과 전장 비중, 내 육성을 함께 반영하며 전투 기믹과 사이클은 별도 확인이 필요합니다. 캐릭터·장비 중복을 검사한 상위 100개 후보 안에서 조합합니다."),true);controls.Children.Add(PanelUi.Details(Locale.T("추천 근거"),stats,PanelUi.LinkRow("",Locale.T("통계 원문"),EndgameKnowledge.Source,error=>work.Finish(error.Message))));
  Dictionary<string,object> state=null;bool busy=false,refreshPending=false;string activeBuild="";Func<Task> load=null;Action<Dictionary<string,object>> showPlans=null;Func<Task> refresh=null;Func<string,Dictionary<string,object>,Task> run=async(command,p)=>{
   if(busy||state==null||request!=generation)return;busy=true;bool preparing=command=="refresh";if(preparing){recommend.IsEnabled=save.IsEnabled=manual.IsEnabled=false;}else controls.IsEnabled=false;work.Begin(Locale.T("편성 자료 확인 중"));Exception failure=null;try{try{if(!preparing&&command!="compare"){p["expected_revision"]=state==null?0:state["revision"];p["event_id"]=Guid.NewGuid().ToString("N");}var result=await Task.Run(()=>{var response=D(service.Run(command,mode,p));return response;});if(request!=generation||!detail.IsShowing(mode))return;if(command=="refresh"){state=result;showSeason(state);showPlans(state);}else{if(command=="save_build")activeBuild=S(result,"id");await load();if(command=="save_build"){var button=p.ContainsKey("option")?save:manual;button.Content=PanelUi.Completion(Locale.T("편성 저장됨"));System.Windows.Automation.AutomationProperties.SetName(button,Locale.T("편성 저장됨"));button.ToolTip=S(result,"label");selected.Text=Locale.Format("{0} 저장됨",S(result,"label"));saveFeedback=true;}}work.Finish();}catch(Exception e){failure=e;}if(failure!=null){try{if(preparing){state=await Task.Run(()=>D(service.Run("status",mode,new Dictionary<string,object>())));showSeason(state);showPlans(state);}else await load();}catch{}work.Finish(failure.Message);}}finally{busy=false;controls.IsEnabled=true;recommend.IsEnabled=manual.IsEnabled=true;save.IsEnabled=option>0&&state!=null&&!Equals(state["recommendationStale"],true);}if(refreshPending){refreshPending=false;await refresh();}
  };
  string displayedRecommendation="";
  showPlans=updated=>{var season=D(updated["season"]);string nextId=Equals(updated["recommendationStale"],true)?"":S(D(updated["recommendation"]),"id");if(preparationInitialized&&nextId==displayedRecommendation)return;if(nextId!=displayedRecommendation){displayedRecommendation=nextId;option=0;selected.Text="";}var rec=D(updated["recommendation"]);bool stale=Equals(updated["recommendationStale"],true);bool hasRecommendation=rec.ContainsKey("options")&&CodexChat.Items(rec["options"]).Any();recommend.Content=Locale.T(hasRecommendation?"추천 갱신":"파티 추천");if(!preparationInitialized){preparationInitialized=true;if(rec.Count>0){restoreGoal(S(rec,"goal"));if(mode=="stygian")difficulty.SelectedIndex=Convert.ToInt32(rec["difficulty"])-1;}preparation.IsExpanded=!autoPrepare&&(!hasRecommendation||stale);}save.IsEnabled=option>0&&!stale;plans.Children.Clear();if(!stale)plans.Children.Add(Plans(rec,mode,n=>{option=n;selected.Text=Locale.Format("추천 {0} 선택됨",n);label.Text=Locale.Format("추천 {0}",n);restoreGoal(S(rec,"goal"));save.IsEnabled=true;if(mode=="stygian")difficulty.SelectedIndex=Convert.ToInt32(rec["difficulty"])-1;saveForm.IsExpanded=true;label.Dispatcher.BeginInvoke(new Action(()=>{label.Focus();label.BringIntoView();}));},season,n=>ask(Locale.Format("catheryne_endgame의 mode={0}, command=status로 현재 추천 id={1}, option={2}을 확인하고 이번 시즌 적 기믹에 맞는지, 캐릭터 역할·원충·생존·사이클과 대체안을 검토해 주세요. 카드 좌석 순서를 스킬 사용 순서로 단정하지 말고 실제 로테이션을 제안해 주세요. 목표: {3}. 게임 플레이는 제가 합니다.",mode,S(rec,"id"),n,GoalDisplay(S(rec,"goal"))))));if(rec.ContainsKey("options")&&!CodexChat.Items(rec["options"]).Any())plans.Children.Add(PanelUi.Text(Locale.T("보유 캐릭터로 중복 없는 통계 파티 조합을 찾지 못했습니다. 직접 편성을 사용할 수 있습니다."),true));};
  refresh=async()=>{if(request!=generation||!detail.IsShowing(mode))return;if(busy){refreshPending=true;return;}await run("refresh",new Dictionary<string,object>{{"difficulty",mode=="abyss"?0:difficulty.SelectedIndex+1},{"goal",goalValue()}});};
  load=async()=>{
   var loaded=await Task.Run(()=>{var data=D(service.Run("status",mode,new Dictionary<string,object>()));Dictionary<string,object> pointer;var characters=AccountMerge.Inventory(new CatheryneTools(root).AccountSnapshot(out pointer),"characters").OrderBy(c=>AccountIdentity.Name(c)).ToArray();return Tuple.Create(data,characters,GameDataCatalog.Read(root).Game,S(AppPreferences.Read(root),"resinServer"));});if(request!=generation||!detail.IsShowing(mode))return;state=loaded.Item1;enemyCatalog=loaded.Item3;var updatedRoster=loaded.Item2;foreach(var choices in manualChoices)foreach(var choice in choices){string prior=choice.SelectedIndex>=0&&choice.SelectedIndex<roster.Length?AccountIdentity.Key(roster[choice.SelectedIndex]):"";choice.Items.Clear();foreach(var character in updatedRoster)choice.Items.Add(AccountIdentity.Name(character));int index=Array.FindIndex(updatedRoster,c=>AccountIdentity.Key(c)==prior);choice.SelectedIndex=index>=0?index:(updatedRoster.Length>0?0:-1);}roster=updatedRoster;var season=D(state["season"]);showSeason(state);showPlans(state);
   bestHistory.Children.Clear();var best=D(state["personalBest"]);if(mode=="stygian"&&best.ContainsKey("combinations")){foreach(var record in CodexChat.Items(best["combinations"]))bestHistory.Children.Add(PanelUi.Text(PartyRoles.Difficulty(Convert.ToInt32(record["difficulty"]))+" · "+Locale.Format("기록 합계 {0}초",record["seconds"])+" · "+Locale.T(Equals(record["equipmentVerified"],true)?"기록상 중복 없음":"장비 중복 미확인"),true));}else if(mode=="abyss"&&best.ContainsKey("chambers")){var recorded=CodexChat.Items(best["chambers"]).Where(c=>c["stars"]!=null).ToArray();if(recorded.Length>0)bestHistory.Children.Add(PanelUi.Text(string.Join(" · ",recorded.Select(c=>Locale.Format("{0}번 방 · 별 {1}개",c["chamber"],c["stars"]))),true));}saved.Children.Clear();var builds=EndgameService.Items(state,"builds").Select(D).Reverse().ToArray();if(builds.Length==0)return;var list=Combo(builds.Select(b=>S(b,"label")+" · "+S(b,"version")+(mode=="stygian"?" · "+PartyRoles.Difficulty(Convert.ToInt32(b["difficulty"])):"")));int selectedIndex=Array.FindIndex(builds,b=>S(b,"id")==activeBuild);if(selectedIndex>=0)list.SelectedIndex=selectedIndex;var selectedBody=new StackPanel();var compareTo=Combo(new[]{Locale.T("비교 대상 선택")}.Concat(builds.Select(b=>S(b,"label"))));var compare=PanelUi.Button(Locale.T("편성 비교"));var comparison=new StackPanel();
   Action showBuild=()=>{
    selectedBody.Children.Clear();if(list.SelectedIndex<0)return;var build=builds[list.SelectedIndex];activeBuild=S(build,"id");foreach(var slot in CodexChat.Items(build["slots"]))selectedBody.Children.Add(Party(CodexChat.Items(slot["members"]).ToArray(),SlotName(mode,Convert.ToInt32(slot["slot"])),slot.ContainsKey("usageRate")?(double?)Convert.ToDouble(slot["usageRate"]):null,slot.ContainsKey("slotShare")?(double?)Convert.ToDouble(slot["slotShare"]):null,mode=="stygian"&&S(build,"version")==S(season,"version")?EnemyRow(season,mode,Convert.ToInt32(slot["slot"])):null));if(S(build,"rotation")!="")selectedBody.Children.Add(PanelUi.Text(S(build,"rotation"),true));    var slotInput=Combo(Enumerable.Range(1,3).Select(n=>mode=="abyss"?Locale.Format("{0}번 방",n):SlotName(mode,n)));var outcome=Combo(new[]{Locale.T("성공"),Locale.T("실패")});var seconds=Input();var stars=Combo(new[]{Locale.T("미확인")}.Concat(Enumerable.Range(0,4).Select(n=>Locale.Format("별 {0}개",n))));var evidence=Input();var confirmed=new CheckBox{Content=Locale.T("저장한 편성과 장비로 플레이함"),Margin=new Thickness(0,0,0,16)};var record=PanelUi.Button(Locale.T("결과 기록"));var recordBody=new StackPanel();recordBody.Children.Add(slotInput);recordBody.Children.Add(PanelUi.InputField(Locale.T("결과"),outcome));recordBody.Children.Add(PanelUi.InputField(mode=="abyss"?Locale.T("방 전체 소요 시간(초) · 선택"):Locale.T("소요 시간(초) · 선택"),seconds));if(mode=="abyss")recordBody.Children.Add(PanelUi.InputField(Locale.T("획득한 별"),stars));recordBody.Children.Add(PanelUi.InputField(Locale.T("결과 메모"),evidence));recordBody.Children.Add(confirmed);recordBody.Children.Add(record);selectedBody.Children.Add(PanelUi.Details(Locale.T("결과 기록"),recordBody));record.Click+=async(sender,e)=>{var p=new Dictionary<string,object>{{"build_id",build["id"]},{"slot",slotInput.SelectedIndex+1},{"result",outcome.SelectedIndex==0?"clear":"failed"},{"evidence",evidence.Text},{"build_confirmed",confirmed.IsChecked==true}};double time;if(seconds.Text.Trim().Length>0){if(!double.TryParse(seconds.Text,NumberStyles.Float,CultureInfo.CurrentCulture,out time)){work.Finish(Locale.T("입력 수치의 범위를 확인해 주세요."));return;}p["seconds"]=time;}if(mode=="abyss"&&outcome.SelectedIndex==0&&stars.SelectedIndex>0)p["stars"]=stars.SelectedIndex-1;await run("record",p);};
    var history=new StackPanel();foreach(var row in EndgameService.Items(state,"attempts").Select(D).Where(a=>S(a,"buildId")==S(build,"id")).Reverse().Take(12))history.Children.Add(PanelUi.Text((mode=="abyss"?Locale.Format("{0}번 방",row["slot"]):SlotName(mode,Convert.ToInt32(row["slot"])))+" · "+Locale.T(S(row,"result")=="clear"?"성공":"실패")+(row["seconds"]==null?"":" · "+row["seconds"]+"s")+(row["stars"]==null?"":" · "+Locale.Format("별 {0}개",row["stars"]))+" · "+S(row,"evidence"),true));selectedBody.Children.Add(history);
    var chat=PanelUi.Button(Locale.T("AI와 검토"));chat.Click+=(sender,e)=>ask(Locale.Format("catheryne_endgame의 mode={0}, command=status로 저장된 편성을 확인하고 build_id={1}의 픽률·육성·장비와 이번 시즌 적 기믹, 원충·사이클을 검토해 주세요. 목표: {2}. 필요하다면 대체 편성을 직접 저장해 주세요. 게임 플레이는 제가 합니다.",mode,S(build,"id"),GoalDisplay(S(build,"goal"))));selectedBody.Children.Add(chat);
   };list.SelectionChanged+=(sender,e)=>showBuild();showBuild();compare.Click+=(sender,e)=>{try{if(compareTo.SelectedIndex<1)return;var result=D(service.Run("compare",mode,new Dictionary<string,object>{{"left",builds[list.SelectedIndex]["id"]},{"right",builds[compareTo.SelectedIndex-1]["id"]}}));comparison.Children.Clear();foreach(var slot in CodexChat.Items(result["slots"])){var a=D(slot["left"]);var b=D(slot["right"]);comparison.Children.Add(PanelUi.Text((mode=="abyss"?Locale.Format("{0}번 방",slot["slot"]):SlotName(mode,Convert.ToInt32(slot["slot"])))+" · "+Locale.T(Equals(slot["changed"],true)?"편성 또는 장비 변경":"편성·장비 동일")));comparison.Children.Add(PanelUi.Text(Locale.Format("성공 {0}/{1} → {2}/{3} · 최고 기록 {4} → {5}",a["clears"],a["attempts"],b["clears"],b["attempts"],a["bestSeconds"]==null?Locale.T("미확인"):a["bestSeconds"]+"s",b["bestSeconds"]==null?Locale.T("미확인"):b["bestSeconds"]+"s"),true));}foreach(var change in CodexChat.Items(result["changes"])){var changes=new StackPanel();changes.Children.Add(PanelUi.Text(Locale.T("이전"),true));changes.Children.Add(MemberDetails(D(change["before"])));changes.Children.Add(PanelUi.Text(Locale.T("이후"),true));changes.Children.Add(MemberDetails(D(change["after"])));comparison.Children.Add(PanelUi.Details(SlotName(mode,Convert.ToInt32(change["slot"]))+" · "+S(change,"name"),changes));}if(Equals(result["rotationChanged"],true))comparison.Children.Add(PanelUi.Text(Locale.T("사이클 메모 변경"),true));}catch(Exception error){work.Finish(error.Message);}};
   saved.Children.Add(PanelUi.Section(Locale.T("저장한 편성"),list,selectedBody,PanelUi.Details(Locale.T("편성 비교"),compareTo,compare,comparison)));
  };
  recommend.Click+=async(sender,e)=>{option=0;save.IsEnabled=false;selected.Text="";await run("recommend",new Dictionary<string,object>{{"difficulty",mode=="abyss"?0:difficulty.SelectedIndex+1},{"goal",goalValue()},{"refresh_account",refreshAccount.IsChecked==true}});};
  Func<Dictionary<string,object>> saveParams=()=>new Dictionary<string,object>{{"label",label.Text},{"rotation",rotation.Text},{"goal",goalValue()},{"difficulty",mode=="abyss"?0:difficulty.SelectedIndex+1}};
  Action resetSave=()=>{if(saveFeedback)selected.Text=option>0?Locale.Format("추천 {0} 선택됨",option):"";saveFeedback=false;save.Content=Locale.T("편성 저장");manual.Content=Locale.T("직접 편성 저장");save.ToolTip=manual.ToolTip=null;System.Windows.Automation.AutomationProperties.SetName(save,Locale.T("편성 저장"));System.Windows.Automation.AutomationProperties.SetName(manual,Locale.T("직접 편성 저장"));};
  label.TextChanged+=(sender,e)=>resetSave();rotation.TextChanged+=(sender,e)=>resetSave();goal.TextChanged+=(sender,e)=>resetSave();difficulty.SelectionChanged+=(sender,e)=>resetSave();foreach(var choices in manualChoices)foreach(var choice in choices)choice.SelectionChanged+=(sender,e)=>resetSave();
  save.Click+=async(sender,e)=>{var p=saveParams();p["option"]=option;await run("save_build",p);};manual.Click+=async(sender,e)=>{if(roster.Length==0){work.Finish(Locale.T("캐릭터 자료를 먼저 수집해 주세요."));return;}var p=saveParams();p["slots"]=manualChoices.Select((choices,i)=>new{slot=i+1,team=choices.Select(c=>AccountIdentity.Key(roster[c.SelectedIndex])).ToArray()}).ToArray();await run("save_build",p);};
  var difficultyTimer=new System.Windows.Threading.DispatcherTimer{Interval=TimeSpan.FromMilliseconds(250)};difficultyTimer.Tick+=async(sender,e)=>{difficultyTimer.Stop();if(autoPrepare&&body.IsVisible)await refresh();};difficulty.SelectionChanged+=(sender,e)=>{if(autoPrepare&&state!=null){difficultyTimer.Stop();difficultyTimer.Start();}};body.Unloaded+=(sender,e)=>difficultyTimer.Stop();
  var sourceTimer=new System.Windows.Threading.DispatcherTimer{Interval=TimeSpan.FromMinutes(1)};sourceTimer.Tick+=async(sender,e)=>{if(autoPrepare&&body.IsVisible&&detail.IsShowing(mode))await refresh();};body.Loaded+=(sender,e)=>{if(autoPrepare)sourceTimer.Start();};body.Unloaded+=(sender,e)=>sourceTimer.Stop();body.IsVisibleChanged+=(sender,e)=>{if(autoPrepare&&body.IsVisible)sourceTimer.Start();else sourceTimer.Stop();};recommend.IsEnabled=save.IsEnabled=manual.IsEnabled=false;detail.Show(mode,Title(mode),body,owner:mode=="abyss"?"Abyss":"Stygian");work.Begin(Locale.T("편성 자료 확인 중"));recommend.Dispatcher.BeginInvoke(new Action(async()=>{try{await load();if(request!=generation||!detail.IsShowing(mode))return;work.Finish();recommend.IsEnabled=manual.IsEnabled=true;if(autoPrepare&&state!=null)await refresh();}catch(Exception error){work.Finish(error.Message);}}));
 }
}
