using System;using System.Collections.Generic;using System.IO;using System.Linq;
internal static class GameDataTests {
 static void Check(bool value,string reason){if(!value)throw new Exception("Public data: "+reason);}
 static void Reject(Action action,string reason){try{action();}catch(ArgumentException){return;}catch(InvalidDataException){return;}catch(IOException){return;}throw new Exception("Public data accepted: "+reason);}
 static Dictionary<string,object> D(object row){return CodexChat.Map(row);}
 static Dictionary<string,object> Clone(Dictionary<string,object> row){return CatheryneTools.Json().Deserialize<Dictionary<string,object>>(CatheryneTools.Json().Serialize(row));}
 internal static void Run(){
  var seed=GameDataCatalog.Read(Path.Combine(Path.GetTempPath(),"catalog-empty-"+Guid.NewGuid().ToString("N")));var raw=new Dictionary<string,object>{{"schema",2},{"game",Clone(seed.Game)},{"hoyolab",Clone(seed.Hoyo)},{"materials",new Dictionary<string,object>{{"schema",1},{"materials",seed.Materials}}},{"scores",Clone(seed.Scores)}};
  string go=CodexChat.S(D(raw["game"]),"revision"),db=CodexChat.S(D(D(raw["game"])["supplement"]),"revision");D(D(D(raw["hoyolab"])["sources"])["optimizer"])["revision"]=go;D(D(D(raw["hoyolab"])["sources"])["database"])["revision"]=db;D(raw["materials"])["revision"]=db;D(raw["scores"])["revision"]=go;
  var bundle=GameDataCatalog.Parse(CatheryneTools.Json().Serialize(raw));Check(bundle.Hoyo.ContainsKey("talents")&&bundle.Materials.Count>=500,"one coherent snapshot for every consumer");
  var bad=Clone(raw);D(D(D(bad["hoyolab"])["sources"])["optimizer"])["revision"]=new string('f',40);Reject(()=>GameDataCatalog.Parse(CatheryneTools.Json().Serialize(bad)),"mixed sources");bad=Clone(raw);D(D(bad["game"])["weaponIds"]).Clear();Reject(()=>GameDataCatalog.Parse(CatheryneTools.Json().Serialize(bad)),"inconsistent weapon map");
  bad=Clone(raw);bad["schema"]=1;Reject(()=>GameDataCatalog.Parse(CatheryneTools.Json().Serialize(bad)),"old catalog schema");bad=Clone(raw);D(bad["game"]).Remove("enemies");Reject(()=>GameDataCatalog.Parse(CatheryneTools.Json().Serialize(bad)),"missing enemy locale catalog");
  string root=Path.Combine(Path.GetTempPath(),"catalog-activation-"+Guid.NewGuid().ToString("N"));Directory.CreateDirectory(Path.Combine(root,"cache"));try{
   string file=Path.Combine(root,"cache","game-catalog.json");File.WriteAllText(file,CatheryneTools.Json().Serialize(raw));var first=GameDataCatalog.Read(root,true);Check(first.Revision>DateTime.MinValue,"cache activated");Check(Equals(D(CatheryneTools.Json().DeserializeObject(CatheryneTools.Json().Serialize(GameDataCatalog.Status(root))))["cacheHealthy"],true),"activated cache reports valid");File.WriteAllText(file,"{broken");Check(object.ReferenceEquals(first,GameDataCatalog.Read(root,true)),"corrupt replacement keeps last validated snapshot");Check(Equals(D(CatheryneTools.Json().DeserializeObject(CatheryneTools.Json().Serialize(GameDataCatalog.Status(root))))["cacheHealthy"],false),"broken cache reports degraded and requires recovery");
  }finally{Directory.Delete(root,true);}
  var future=new[]{new Dictionary<string,object>{{"character",new Dictionary<string,object>{{"key","FutureCharacter"}}}},new Dictionary<string,object>{{"character",new Dictionary<string,object>{{"key","Skirk"}}}}};Check(object.ReferenceEquals(future,PartyRoles.Order(future)),"unverified new character role preserves source order");
  var reset=new DateTime(2026,9,30,20,0,0,DateTimeKind.Utc);var record=new Dictionary<string,object>{{"available",true},{"uid","fixture"},{"server","os_asia"},{"period",TheaterKnowledge.Period(reset.AddMinutes(-1),"os_asia")},{"checkedAt",reset.AddMinutes(-1).ToString("o")}};
  Check(TheaterKnowledge.OfficialRecordFresh(record,"fixture","os_asia",reset.AddSeconds(-1)),"official record fresh before reset");Check(!TheaterKnowledge.OfficialRecordFresh(record,"fixture","os_asia",reset),"official record expires at season boundary within six-hour cache");Check(!TheaterKnowledge.OfficialRecordFresh(record,"other","os_asia",reset.AddSeconds(-1)),"record identity separation");
  var end=new DateTime(2026,10,15,20,0,0,DateTimeKind.Utc);var season=new Dictionary<string,object>{{"start","2026-09-16T04:00:00"},{"end","2026-10-16T04:00:00"}};var knowledge=new Dictionary<string,object>{{"schema",2},{"checkedAt",end.AddMinutes(-1).ToString("o")},{"modes",new Dictionary<string,object>{{"abyss",season},{"stygian",season}}}};
  Check(EndgameKnowledge.Fresh(knowledge,end.AddSeconds(-1),"os_asia"),"statistics fresh before boundary");Check(!EndgameKnowledge.Fresh(knowledge,end,"os_asia"),"statistics cannot reuse hourly cache after rollover");
  string en="{\"1\":{\"name\":\"Theme\",\"achievements\":[{\"id\":1,\"name\":\"A\",\"desc\":\"Condition\",\"reward\":5}]}}",ko=en.Replace("Theme","Translation");Check(AchievementCatalog.Merge(en,ko).Count==1,"paired achievement translations");Reject(()=>AchievementCatalog.Merge(en,ko.Replace("\"reward\":5","\"reward\":10")),"conflicting achievement reward");
  var anchor=new[]{new PrimoVersion{Version="6.0",Start="2025-09-10T06:00:00"}};var dates=PrimogemService.ParseVersionDates("# Version Luna I Update Details\nUpdate maintenance begins <t>2025/09/10 06:00</t>",anchor);Check(dates.Count==1&&dates[0].Version=="6.0","marketing names use published date identity");Check(PrimogemService.ParseVersionDates("# Version Future IX Update Details\nUpdate maintenance begins <t>2027/09/10 06:00</t>").Count==0,"unknown version labels are never guessed");Reject(()=>PrimogemService.ParseVersionDates("# Version 7.1 Update Details\nUpdate maintenance begins <t>2026/09/23 06:00</t>\n# Version 7.1 Update Maintenance\nUpdate maintenance begins <t>2026/09/24 06:00</t>"),"conflicting version dates");
 }
}
