using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
internal static class HoyoAccountTests {
 static Dictionary<string,object> Map(string json){return CatheryneTools.Json().Deserialize<Dictionary<string,object>>(json);}
 static void Check(bool pass,string message){if(!pass)throw new Exception("HoYoLAB: "+message);}
 static void Reject(Action action,string message){bool threw=false;try{action();}catch{threw=true;}Check(threw,message);}
 static Dictionary<string,object> Fixture(){return Map(@"{""list"":[{""base"":{""id"":10000075,""level"":90,""actived_constellation_num"":3},""weapon"":{""id"":14512,""level"":90,""promote_level"":6,""affix_level"":1},""relics"":[{""id"":27544,""pos"":1,""rarity"":5,""level"":20,""main_property"":{""property_type"":2,""value"":""4780""},""sub_property_list"":[{""property_type"":20,""value"":""14.0%""},{""property_type"":22,""value"":""11.7%""}]}],""skills"":[{""name"":""Yuuban Meigen"",""skill_type"":1,""level"":10},{""name"":""Hanega: Song of the Wind"",""skill_type"":1,""level"":10},{""name"":""Kyougen: Five Ceremonial Plays"",""skill_type"":1,""level"":13}]}]}");}
 static Dictionary<string,object> Convert(){return HoyoAccountConverter.Convert(Fixture(),"800000001","os_asia",Map(@"{""achievement_num"":1427,""list"":[{""id"":""0"",""finish_num"":754}]}"),HoyoAccountConverter.Catalog());}
 static void VerifyExistingNewCharacters(){
  var catalog=HoyoAccountConverter.Catalog();var existing=Map(@"{""format"":""GOOD"",""characters"":[{""key"":""Vodyanitsa"",""level"":70,""ascension"":4,""talent"":{""auto"":1,""skill"":1,""burst"":1}},{""key"":""Vesna"",""level"":70,""ascension"":4}]}");
  var details=Fixture();var rows=new List<object>(CodexChat.Items(details["list"]));
  rows.Add(Map(@"{""base"":{""id"":10000140,""level"":90,""actived_constellation_num"":3},""skills"":[{""name"":""Psyshkhwe Arietta"",""skill_type"":1,""level"":6},{""name"":""Rechitativ: Sonorous Dawn"",""skill_type"":1,""level"":11},{""name"":""Koda: Sink With Thee"",""skill_type"":1,""level"":8}]}"));
  rows.Add(Map(@"{""base"":{""id"":10000143,""level"":88,""actived_constellation_num"":0},""skills"":[{""name"":""Vila Blade Dance"",""skill_type"":1,""level"":2},{""name"":""The Art of Victory"",""skill_type"":1,""level"":8},{""name"":""For the Tsaritsa!"",""skill_type"":1,""level"":8}]}"));details["list"]=rows;
  var converted=HoyoAccountConverter.Convert(details,"800000001","os_asia",new Dictionary<string,object>(),catalog,existing);var merged=AccountMerge.Merge(existing,converted);var chars=CodexChat.Items(merged["characters"]).ToArray();
  var vody=chars.Single(x=>CodexChat.S(x,"key")=="Vodyanitsa");var vesna=chars.Single(x=>CodexChat.S(x,"key")=="Vesna");
  Check(ConvertInt(vody["level"])==90&&ConvertInt(vesna["level"])==88,"verified numeric IDs update existing new characters without inventing keys");
  Check(ConvertInt(CodexChat.Map(vody["talent"])["skill"])==8&&ConvertInt(CodexChat.Map(vesna["talent"])["skill"])==8,"new character talents and constellation boosts are normalized");
  Check(!vody.ContainsKey("ascension")&&!vesna.ContainsKey("ascension"),"old ascension incompatible with new level does not survive");
  var repeated=AccountMerge.Merge(merged,converted);Check(CodexChat.Items(repeated["characters"]).Count()==3,"repeat refresh does not duplicate new characters");
  var unsupported=HoyoAccountConverter.Convert(details,"800000001","os_asia",new Dictionary<string,object>(),catalog);Check(CodexChat.Items(unsupported["characters"]).Count()==3&&CodexChat.Items(unsupported["characters"]).Count(x=>!x.ContainsKey("key")&&x.ContainsKey("gameId"))==2,"first-time characters use game IDs without guessed GOOD keys");
  var ambiguous=Map(@"{""characters"":[{""key"":""Vodyanitsa""},{""key"":""vodyanitsa""}]}");var rejected=HoyoAccountConverter.Convert(details,"800000001","os_asia",new Dictionary<string,object>(),catalog,ambiguous);Check(CodexChat.Items(rejected["characters"]).Count()==3&&!CodexChat.Items(rejected["characters"]).Single(x=>CodexChat.S(x,"gameId")=="10000140").ContainsKey("key"),"ambiguous GOOD identity remains native");
 }
 static void VerifyNativeItems(){
  var catalog=HoyoAccountConverter.Catalog();var raw=Fixture();var row=CodexChat.Items(raw["list"]).Single();var basis=CodexChat.Map(row["base"]);basis["id"]=19999999;basis["name"]="Future Hero";var weapon=CodexChat.Map(row["weapon"]);weapon["id"]=999999;weapon["name"]="Future Bow";
  var localized=Map(CatheryneTools.Json().Serialize(raw));var local=CodexChat.Items(localized["list"]).Single();CodexChat.Map(local["base"])["name"]="새 영웅";CodexChat.Map(local["weapon"])["name"]="새 활";
  var native=HoyoAccountConverter.Convert(raw,"800000001","os_asia",new Dictionary<string,object>(),catalog,null,localized);
  var character=CodexChat.Items(native["characters"]).Single();Check(AccountIdentity.Key(character)=="game:19999999"&&AccountIdentity.Name(character,null,"ko")=="새 영웅","official game ID and localized name need no release mapping");
  Check(AccountIdentity.Name(AccountMerge.Equipped(native,"weapons","game:19999999").Single(),null,"ko")=="새 활","native weapon appears on native owner");
  var again=AccountMerge.Merge(native,native);Check(CodexChat.Items(again["characters"]).Count()==1&&CodexChat.Items(again["weapons"]).Count()==1,"native repeat refresh is idempotent");
  basis["level"]=95;weapon["refinement"]=2;var refreshed=HoyoAccountConverter.Convert(raw,"800000001","os_asia",new Dictionary<string,object>(),catalog,native,localized);again=AccountMerge.Merge(again,refreshed);Check(ConvertInt(CodexChat.Items(again["characters"]).Single()["level"])==95,"existing native character receives changed level");
  var exported=AccountIdentity.Export(again);Check(CodexChat.S(exported,"format")=="GOOD"&&!CodexChat.Items(exported["characters"]).Any()&&!CodexChat.Items(exported["weapons"]).Any()&&!CodexChat.Items(exported["artifacts"]).Any(),"GOOD root has no unsupported identities or native owners");
  var restored=AccountIdentity.Import(Map(CatheryneTools.Json().Serialize(exported)));Check(CodexChat.Items(restored["characters"]).Count()==1&&AccountMerge.Equipped(restored,"weapons","game:19999999").Length==1,"native extension preserves export and import roundtrip");
  var nextCatalog=Map(CatheryneTools.Json().Serialize(catalog));CodexChat.Map(nextCatalog["characters"])["19999999"]="FutureHero";var supported=HoyoAccountConverter.Convert(raw,"800000001","os_asia",new Dictionary<string,object>(),nextCatalog,native,localized);var stable=AccountMerge.Merge(native,supported);Check(AccountIdentity.Key(CodexChat.Items(stable["characters"]).Single())=="game:19999999"&&AccountMerge.Equipped(stable,"weapons","game:19999999").Length==1,"later GOOD support preserves existing goal and equipment identity");
  var promoted=Map(CatheryneTools.Json().Serialize(refreshed));CodexChat.Items(promoted["characters"]).Single()["key"]="FutureHero";CodexChat.Items(promoted["characters"]).Single().Remove("identity");promoted.Remove("weapons");promoted.Remove("artifacts");promoted["catheryne"]=new Dictionary<string,object>();var promotion=AccountMerge.Merge(native,promoted);Check(CodexChat.Items(promotion["characters"]).Count()==1&&AccountMerge.Equipped(promotion,"weapons","FutureHero").Length==1,"new GOOD key preserves game identity and equipment ownership");
  var known=Convert();var replacement=Fixture();CodexChat.Map(CodexChat.Items(replacement["list"]).Single()["weapon"])["id"]=999999;var incoming=HoyoAccountConverter.Convert(replacement,"800000001","os_asia",new Dictionary<string,object>(),catalog,known);var equipped=AccountMerge.Merge(known,incoming);Check(CodexChat.Items(equipped["weapons"]).Count()==2&&CodexChat.S(AccountMerge.Equipped(equipped,"weapons","Wanderer").Single(),"gameId")=="999999","new unmapped weapon replaces old equipped observation");
  Check(CodexChat.Items(equipped["weapons"]).Single(x=>x.ContainsKey("key"))["location"]==null,"old weapon remains owned with stale owner cleared");
  equipped=AccountMerge.Merge(equipped,incoming);Check(CodexChat.Items(equipped["weapons"]).Count()==2,"repeated new weapon does not inflate inventory");
  Reject(()=>AccountIdentity.Import(Map(@"{""format"":""GOOD"",""characters"":[3]}")),"malformed native rows rejected");
  Reject(()=>AccountIdentity.Import(Map(@"{""format"":""GOOD"",""characters"":[{""gameId"":0}]}")),"invalid game identity rejected");
  Reject(()=>AccountIdentity.Import(Map(@"{""format"":""GOOD"",""catheryne"":{""nativeItems"":{""format"":[]}}}")),"native extension cannot overwrite format");
 }
 static void VerifySwapsAndCurrentInventory(){
  var old=Map(@"{""format"":""GOOD"",""weapons"":[{""key"":""DullBlade"",""level"":20,""ascension"":0,""refinement"":1,""location"":""Amber""},{""key"":""SilverSword"",""level"":40,""ascension"":1,""refinement"":2,""location"":""Jean""}]}");
  var incoming=Map(CatheryneTools.Json().Serialize(old));var rows=CodexChat.Items(incoming["weapons"]).ToArray();rows[0]["location"]="Jean";rows[1]["location"]="Amber";incoming["catheryne"]=Map(@"{""coverage"":{""weapons"":""equipped""},""equipmentObserved"":{""weapons"":[""Jean"",""Amber""]}}");
  var swapped=AccountMerge.Merge(old,incoming);Check(CodexChat.Items(swapped["weapons"]).Count()==2&&CodexChat.S(AccountMerge.Equipped(swapped,"weapons","Amber").Single(),"key")=="SilverSword"&&CodexChat.S(AccountMerge.Equipped(swapped,"weapons","Jean").Single(),"key")=="DullBlade","exchange updates both owners without adding an instance");
  rows[1]["key"]="DullBlade";CodexChat.Items(old["weapons"]).Last()["key"]="DullBlade";swapped=AccountMerge.Merge(old,incoming);Check(CodexChat.Items(swapped["weapons"]).Count()==2&&ConvertInt(AccountMerge.Equipped(swapped,"weapons","Amber").Single()["level"])==40&&ConvertInt(AccountMerge.Equipped(swapped,"weapons","Jean").Single()["level"])==20,"same weapon type exchange tracks observed states and multiplicity");
  var statFixture=Fixture();CodexChat.Items(statFixture["list"]).Single()["selected_properties"]=Map(@"{""rows"":[{""property_type"":2000,""final"":""63721""},{""property_type"":20,""final"":""33.4%""}]}")["rows"];var measured=HoyoAccountConverter.Convert(statFixture,"800000001","os_asia",new Dictionary<string,object>(),HoyoAccountConverter.Catalog());var finalStats=CodexChat.Map(CodexChat.Items(measured["characters"]).Single()["finalStats"]);Check(System.Convert.ToDouble(finalStats["hp"])==63721&&System.Convert.ToDouble(finalStats["critRate_"])==33.4,"observed final stats retain their percent units");
  var good=Convert();var changed=Convert();CodexChat.Items(changed["weapons"]).Single()["refinement"]=5;var pending=AccountMerge.Merge(good,changed);Check(CodexChat.Items(pending["weapons"]).Count()==1&&AccountMerge.Inventory(pending,"weapons").Any(x=>CodexChat.S(x,"inventoryMatch")=="unresolved"&&ConvertInt(x["refinement"])==5),"current unresolved observation is visible in inventory without increasing known inventory");
  var unsupported=Fixture();CodexChat.Items(CodexChat.Items(unsupported["list"]).Single()["skills"]).First()["name"]="Updated Unknown Skill";var converted=HoyoAccountConverter.Convert(unsupported,"800000001","os_asia",new Dictionary<string,object>(),HoyoAccountConverter.Catalog(),good);var latest=AccountMerge.Merge(good,converted);var character=CodexChat.Items(latest["characters"]).Single();Check(!CodexChat.Map(character["talent"]).ContainsKey("auto")&&character.ContainsKey("hoyolab")&&CodexChat.Items(character["observedSkills"]).Count()==3,"new raw skills are retained and an old unverified base talent is not shown as current");
  var artifact=CodexChat.Items(unsupported["list"]).Single();var relic=CodexChat.Items(artifact["relics"]).Single();relic["set"]=Map(@"{""id"":999,""name"":""Future Set""}");var localized=Map(CatheryneTools.Json().Serialize(unsupported));CodexChat.Map(CodexChat.Items(CodexChat.Items(localized["list"]).Single()["relics"]).Single()["set"])["name"]="새 세트";converted=HoyoAccountConverter.Convert(unsupported,"800000001","os_asia",new Dictionary<string,object>(),HoyoAccountConverter.Catalog(),good,localized);Check(AccountIdentity.SetName(CodexChat.Items(converted["artifacts"]).Single())==(Locale.IsEnglish?"Future Set":"새 세트"),"artifact set names come from current official response");
  string icon="https://act-webstatic.hoyoverse.com/item.png";Check(GameCatalog.PortraitUrls("Wanderer",icon).First()==icon&&GameCatalog.PortraitUrls("game:99999",icon).Length==1,"official images are primary even without a catalog key");Check(GameCatalog.PortraitUrls("game:99999","https://example.com/icon.png").Length==0,"portrait fetching stays on verified source hosts");
 }
 internal static void Run(){
  VerifyExistingNewCharacters();VerifyNativeItems();VerifySwapsAndCurrentInventory();
  var good=Convert();var character=CodexChat.Items(good["characters"]).Single();var talents=CodexChat.Map(character["talent"]);
  Check(ConvertInt(talents["burst"])==10&&ConvertInt(talents["skill"])==10,"constellation bonus removed without changing base skill");
  Check(!character.ContainsKey("ascension"),"unobserved ascension stays absent");
  var weapon=CodexChat.Items(good["weapons"]).Single();Check(!weapon.ContainsKey("id")&&!weapon.ContainsKey("lock"),"type ID and unknown lock are not instance data");
  var artifact=CodexChat.Items(good["artifacts"]).Single();Check(CodexChat.S(artifact,"setKey")=="DesertPavilionChronicle"&&CodexChat.S(artifact,"slotKey")=="flower","numeric catalog and slot mapping");
  Check(System.Convert.ToDouble(CodexChat.Items(artifact["substats"]).First()["value"])==14.0,"percentage is GOOD percentage, not fraction");
  var old=Map(CatheryneTools.Json().Serialize(good));var spare=new Dictionary<string,object>(weapon);spare["location"]="";spare["level"]=80;old["weapons"]=new[]{weapon,spare};
  var merged=AccountMerge.Merge(old,Convert());Check(CodexChat.Items(merged["weapons"]).Count()==2,"unequipped weapon retained");
  merged=AccountMerge.Merge(merged,Convert());Check(CodexChat.Items(merged["weapons"]).Count()==2,"repeat refresh is idempotent");
  var changed=Convert();CodexChat.Items(changed["weapons"]).Single()["refinement"]=2;
  merged=AccountMerge.Merge(merged,changed);Check(CodexChat.Items(merged["weapons"]).Count()==2,"ambiguous upgrade does not create phantom inventory");
  Check(ConvertInt(AccountMerge.Equipped(merged,"weapons","Wanderer").Single()["refinement"])==2,"current equipped observation wins for build and character views");
  Check(CodexChat.Items(merged["weapons"]).Any(x=>x.ContainsKey("location")&&Equals(x["location"],"")),"known unequipped item preserved");
  merged=AccountMerge.Merge(merged,changed);Check(AccountMerge.Equipped(merged,"weapons","Wanderer").Length==1,"pending observation never duplicates");
  var other=Convert();CodexChat.Map(other["catheryne"])["uid"]="800000002";Reject(()=>AccountMerge.Merge(merged,other),"different UID rejected");
  var full=Map(@"{""format"":""GOOD"",""weapons"":[],""catheryne"":{""coverage"":{""weapons"":""full""}}}");var scanned=AccountMerge.Merge(merged,full);Check(AccountMerge.Equipped(scanned,"weapons","Wanderer").Length==0,"later full weapon scan clears pending weapon observations");
  var moved=Convert();CodexChat.Items(moved["weapons"]).Single()["location"]="Jean";var swapped=AccountMerge.Merge(good,moved);Check(CodexChat.Items(swapped["weapons"]).Count()==1&&AccountMerge.Equipped(swapped,"weapons","Jean").Length==1,"moved exact equipment reuses instance");
  var unknown=Fixture();CodexChat.Map(CodexChat.Items(unknown["list"]).Single()["weapon"])["id"]=999999;var partial=HoyoAccountConverter.Convert(unknown,"800000001","os_asia",new Dictionary<string,object>(),HoyoAccountConverter.Catalog());Check(CodexChat.Items(partial["weapons"]).Count()==1&&!CodexChat.Items(partial["weapons"]).Single().ContainsKey("key")&&CodexChat.S(CodexChat.Items(partial["weapons"]).Single(),"gameId")=="999999","unknown weapon is usable without a guessed GOOD key");
  var traveler=Fixture();var basis=CodexChat.Map(CodexChat.Items(traveler["list"]).Single()["base"]);basis["id"]=10000005;basis["element"]="Pyro";var tg=HoyoAccountConverter.Convert(traveler,"800000001","os_asia",new Dictionary<string,object>(),HoyoAccountConverter.Catalog());Check(CodexChat.S(CodexChat.Items(tg["characters"]).Single(),"key")=="TravelerPyro"&&AccountMerge.Equipped(tg,"weapons","TravelerPyro").Length==1,"traveler element key and shared equipment location");
  var unequipped=Convert();unequipped["artifacts"]=new object[0];var cleared=AccountMerge.Merge(good,unequipped);Check(CodexChat.Items(cleared["artifacts"]).Count()==1&&AccountMerge.Equipped(cleared,"artifacts","Wanderer").Length==0,"empty observed equipment retains owned item but clears stale location");
  string root=Path.Combine(Path.GetTempPath(),"hoyo-account-test-"+Guid.NewGuid().ToString("N"));Directory.CreateDirectory(root);
  try{
   string file=Path.Combine(root,"fixture.json");File.WriteAllText(file,CatheryneTools.Json().Serialize(good));new ProfileStore(root).Import("account",file);
   string pointer=Path.Combine(root,"profiles","default","account","current.json"),before=File.ReadAllText(pointer);
   var blocked=(AiTaskRecord)new CatheryneTools(root).Run("catheryne_execute",new Dictionary<string,object>{{"action","collection.refresh"},{"parameters",new Dictionary<string,object>{{"kind","auto"}}}},"test","missing-login");Check(blocked.State=="blocked"&&blocked.Action=="hoyolab_login","automatic missing login requests common login instead of starting game input");
   AppPreferences.Set("resinUid","800000001",root);AppPreferences.Set("resinServer","os_asia",root);using(var db=new LocalDataService(root))db.SetSecret("hoyolab","fixture");
   var failure=new HoyoAccountService(root,(c,u,s,e,p,l)=>{throw new IOException("fixture network failure");});Reject(()=>failure.Refresh(),"API failure reported");Check(File.ReadAllText(pointer)==before,"failure preserves current snapshot");
   int requests=0;var live=Fixture();var incremental=new HoyoAccountService(root,(c,u,s,e,p,l)=>{requests++;return e=="character/list"?Map(@"{""list"":[{""id"":10000075}]}"):e=="character/detail"?live:Map(@"{""achievement_num"":1427}");});
   incremental.Refresh(true);string imported=File.ReadAllText(pointer);int first=requests;incremental.Refresh(true);Check(requests==first&&File.ReadAllText(pointer)==imported,"recent snapshot uses cache");
   incremental.Refresh(false);Check(requests>first&&File.ReadAllText(pointer)==imported,"unchanged remote data does not create a snapshot");
   CodexChat.Map(CodexChat.Items(live["list"]).Single()["base"])["actived_constellation_num"]=4;incremental.Refresh(false);Dictionary<string,object> changedReference;var changedSnapshot=new CatheryneTools(root).AccountSnapshot(out changedReference);Check(ConvertInt(CodexChat.Items(changedSnapshot["characters"]).Single()["constellation"])==4,"existing character information changes are persisted");
   File.WriteAllText(file,CatheryneTools.Json().Serialize(Convert()));new ProfileStore(root).Import("account",file);first=requests;incremental.Refresh(true);Check(requests>first,"intervening import invalidates cache");
   AppPreferences.Set("resinUid","800000002",root);Reject(()=>incremental.Refresh(true),"cached identity cannot bypass account guard");
   Check(new ProfileStore(root).AchievementStates().Count==0,"category summary never imports individual achievements");
  }finally{Directory.Delete(root,true);}
 }
 static int ConvertInt(object value){return System.Convert.ToInt32(value);}
}
