using System;using System.Collections.Generic;using System.IO;using System.Linq;
internal static class MaterialInventoryTests {
 static Dictionary<string,object> M(string json){return CatheryneTools.Json().Deserialize<Dictionary<string,object>>(json);}
 static void Check(bool pass,string message){if(!pass)throw new Exception("Materials: "+message);}
 static void Reject(Action action,string message){bool threw=false;try{action();}catch{threw=true;}Check(threw,message);}
 internal static void Run(){
  Check(ProfileStore.ImportKind(M(@"{""format"":""GOOD"",""materials"":{""Mora"":0}}"))=="account","central import detects material account files");
  Check(ProfileStore.ImportKind(M(@"{""Version"":1,""Data"":{}}"))=="achievements"&&ProfileStore.ImportKind(M(@"{""format"":""Catheryne.Achievements"",""version"":1,""completed"":[]}"))=="achievements","central import detects both supported achievement formats");Reject(()=>ProfileStore.ImportKind(M(@"{""unknown"":true}")),"central import rejects unrelated files");Check(MaterialInventory.CountText(M(@"{""quantity"":null}"))==Locale.T("수량 미확인"),"unknown count label is explicit");
  string at="2026-09-30T00:00:00Z";
  var data=M(@"{""has_user_info"":true,""overall_consume"":[{""id"":202,""name"":""Mora"",""num"":100,""lack_num"":0},{""id"":104003,""name"":""XP"",""num"":50,""lack_num"":20}],""available_material"":[{""id"":202,""num"":9999}]}");
  var rows=MaterialInventory.FromCalculator(data,at);Check(rows.Length==2&&rows.All(x=>x["quantity"]==null),"calculator allocations never become raw backpack quantities");Reject(()=>MaterialInventory.FromCalculator(M(@"{""has_user_info"":false}"),at),"unauthenticated cost result never becomes inventory");
  var old=AccountIdentity.Import(M(@"{""format"":""GOOD"",""materials"":{""Mora"":12345,""HerosWit"":27},""catheryne"":{""scannedAt"":""2026-09-30T00:00:00Z"",""uid"":""800000001"",""server"":""os_asia""}}"));Check(MaterialInventory.Rows(old).Any(x=>CodexChat.S(x,"itemId")=="202"&&MaterialInventory.Number(x["quantity"],"count")==12345),"scan keys resolve to official numeric IDs");
  var incoming=new Dictionary<string,object>{{"format",AccountIdentity.Format},{"materialInventory",rows}};var merged=AccountMerge.Merge(old,incoming);Check(MaterialInventory.Rows(merged).Single(x=>CodexChat.S(x,"itemId")=="202")["quantity"].ToString()=="12345","calculator preserves previously measured stock");
  var displayRows=AccountMerge.Inventory(merged,"materials");Check(displayRows.Length==2&&displayRows.Any(x=>MaterialInventory.CountText(x)=="12,345"),"shared account inventory uses canonical material observations");
  rows.Single(x=>CodexChat.S(x,"itemId")=="202")["icon"]="https://act-webstatic.hoyoverse.com/fixture.png";merged=AccountMerge.Merge(merged,incoming);var enriched=MaterialInventory.Rows(merged).Single(x=>CodexChat.S(x,"itemId")=="202");Check(CodexChat.S(enriched,"icon").Length>0&&enriched["quantity"].ToString()=="12345","display enrichment preserves measured stock");
  var unknown=AccountIdentity.Import(M(@"{""format"":""GOOD"",""materials"":{""FutureMaterial"":8}}"));Check(MaterialInventory.Rows(unknown).Single()["itemId"].ToString()=="good:FutureMaterial","new unmapped material is preserved without guessed numeric ID");Reject(()=>AccountIdentity.Import(M(@"{""format"":""GOOD"",""materials"":{""Mora"":-1}}")),"negative scan quantity rejected");
  var newer=AccountIdentity.Import(M(@"{""format"":""GOOD"",""materials"":{""Mora"":0},""catheryne"":{""scannedAt"":""2026-09-30T01:00:00Z""}}"));merged=AccountMerge.Merge(merged,newer);Check(MaterialInventory.Rows(merged).Length==2&&MaterialInventory.Rows(merged).Single(x=>CodexChat.S(x,"itemId")=="202")["quantity"].ToString()=="0","partial scan preserves other stock and observed zero");var exported=AccountIdentity.Export(merged);Check(MaterialInventory.Rows(AccountIdentity.Import(exported)).Length==2,"GOOD roundtrip preserves material observations");Check(CodexChat.Map(exported["materials"])["Mora"].ToString()=="0"&&!merged.ContainsKey("materials"),"GOOD material counts project current canonical observations, not old raw import");
  string root=Path.Combine(Path.GetTempPath(),"material-test-"+Guid.NewGuid().ToString("N"));Directory.CreateDirectory(root);try{
   AppPreferences.Set("resinUid","800000001",root);AppPreferences.Set("resinServer","os_asia",root);using(var db=new LocalDataService(root))db.SetSecret("hoyolab","fixture");
   var service=new HoyoMaterialService(root,(c,u,s,e,p)=>e=="sync/avatar/list"?M(@"{""list"":[{""id"":10000075,""level_current"":80,""element_attr_id"":2}]}"):data);service.Refresh();Dictionary<string,object> pointer;var snap=new CatheryneTools(root).AccountSnapshot(out pointer);Check(MaterialInventory.Rows(snap).Length==2,"service persists through canonical profile store");Check(new ProfileStore(root).CollectionImports().ContainsKey("materials"),"shared collection freshness recognizes canonical material inventory");string before=CodexChat.S(pointer,"snapshot");Reject(()=>new HoyoMaterialService(root,(c,u,s,e,p)=>{throw new IOException("fixture");}).Refresh(),"failed fetch is surfaced");new CatheryneTools(root).AccountSnapshot(out pointer);Check(CodexChat.S(pointer,"snapshot")==before,"network failure preserves previous inventory");
   string file=Path.Combine(root,"fixture.json");File.WriteAllText(file,@"{""format"":""GOOD"",""characters"":[{""key"":""Wanderer"",""gameId"":10000075,""level"":80}]}");new ProfileStore(root).Import("account",file);var goals=new GoalStore(root);goals.Save(new GoalRequest{Title="First",Category="character",CharacterKey="Wanderer",TargetLevel=85});goals.Save(new GoalRequest{Title="Second",Category="character",CharacterKey="Wanderer",TargetLevel=90});int plans=0;
   new HoyoMaterialService(root,(c,u,s,e,p)=>{if(e=="sync/avatar/list")return M(@"{""list"":[{""id"":10000075,""level_current"":80,""element_attr_id"":2}]}");var items=CodexChat.Items(p["items"]).ToArray();if(MaterialInventory.Number(items[0]["avatar_level_current"],"level")==80){plans++;Check(items.Length==1&&items[0]["avatar_level_target"].ToString()=="90","overlapping goals share one maximum target, not duplicate costs");}return data;}).Refresh();Check(plans==1,"active goals receive one combined calculation");
   var goal=goals.Read().Goals.First();goal.TargetTalent=9;goals.Save(goal);bool checkedTalents=false;var rules=MaterialInventory.Map(MaterialInventory.Map(HoyoAccountConverter.Catalog(),"talents"),"10000075");var expected=CharacterBuild.Read(root,CodexChat.Items(new CatheryneTools(root).AccountSnapshot(out pointer)["characters"]).Single()).Talents.Where(x=>x.Value>0).Select(x=>x.Key).ToArray();
   new HoyoMaterialService(root,(c,u,s,e,p)=>{if(e=="sync/avatar/list")return M(@"{""list"":[{""id"":10000075,""level_current"":80,""element_attr_id"":2}]}");if(e=="sync/avatar/detail")return new Dictionary<string,object>{{"skill_list",new[]{"auto","skill","burst"}.Select((k,i)=>new Dictionary<string,object>{{"name",CodexChat.S(CodexChat.Map(rules[k]),"name")},{"group_id",7500+i},{"level_current",1}}).ToArray()}};var items=CodexChat.Items(p["items"]).ToArray();if(MaterialInventory.Number(items[0]["avatar_level_current"],"level")==80){var skills=CodexChat.Items(items[0]["skill_list"]).ToArray();Check(skills.Length==expected.Length&&skills.All(x=>x["level_target"].ToString()=="9"),"only role-relevant talents use requested targets and verified skill group IDs");checkedTalents=true;}return data;}).Refresh();Check(checkedTalents,"talent goal reaches common calculator path");
   var latest=new CatheryneTools(root).AccountSnapshot(out pointer);Check(!HoyoMaterialService.PlanStale(root,latest),"new plan matches goals and observed account state");CodexChat.Items(latest["characters"]).Single()["level"]=81;Check(HoyoMaterialService.PlanStale(root,latest),"changed character level invalidates prior requirements");
  }finally{Directory.Delete(root,true);}
 }
}
