using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Security.Cryptography;

internal static class ModEngineTests {
 static void Check(bool value,string message){if(!value)throw new Exception(message);}
 static void Reject(Action action,string message){bool rejected=false;try{action();}catch{rejected=true;}Check(rejected,message);}
 internal static byte[] Dll(byte value){var data=new byte[512];data[0]=(byte)'M';data[1]=(byte)'Z';Array.Copy(BitConverter.GetBytes(0x80),0,data,0x3c,4);Array.Copy(BitConverter.GetBytes(0x4550),0,data,0x80,4);Array.Copy(BitConverter.GetBytes((ushort)0x8664),0,data,0x84,2);Array.Copy(BitConverter.GetBytes((ushort)0x2000),0,data,0x96,2);Array.Copy(BitConverter.GetBytes((ushort)0x20b),0,data,0x98,2);data[511]=value;return data;}
 static Dictionary<string,object> Mode(Dictionary<string,object> config){return CodexChat.Map(CodexChat.Map(CodexChat.Map(config["Importers"])["GIMI"])["Migoto"]);}
 static IEnumerable<T> Elements<T>(System.Windows.DependencyObject root) where T:System.Windows.DependencyObject {
  if(root is T)yield return (T)root;foreach(object child in System.Windows.LogicalTreeHelper.GetChildren(root))if(child is System.Windows.DependencyObject)foreach(var item in Elements<T>((System.Windows.DependencyObject)child))yield return item;
 }
 static IEnumerable<T> VisualElements<T>(System.Windows.DependencyObject root) where T:System.Windows.DependencyObject{if(root is T)yield return (T)root;for(int i=0;i<System.Windows.Media.VisualTreeHelper.GetChildrenCount(root);i++)foreach(var child in VisualElements<T>(System.Windows.Media.VisualTreeHelper.GetChild(root,i)))yield return child;}
 static void WaitFor(Func<bool> ready){
  var frame=new System.Windows.Threading.DispatcherFrame();var watch=System.Diagnostics.Stopwatch.StartNew();var timer=new System.Windows.Threading.DispatcherTimer{Interval=TimeSpan.FromMilliseconds(20)};
  timer.Tick+=(sender,args)=>{if(ready()||watch.ElapsedMilliseconds>3000){timer.Stop();frame.Continue=false;}};timer.Start();System.Windows.Threading.Dispatcher.PushFrame(frame);Check(ready(),"Runtime UI background status did not finish");
 }
 internal static void LayoutContracts(System.Windows.Window owner){
  string root=Path.Combine(Path.GetTempPath(),"mod-engine-ui-"+Guid.NewGuid().ToString("N")),runtime=ModIntegration.ManagedRoot(root),exe=Path.Combine(runtime,"Resources","Bin","XXMI Launcher.exe");Directory.CreateDirectory(Path.GetDirectoryName(exe));File.WriteAllText(exe,"fixture");AppPreferences.Set("xxmiPath",exe,root);
  var previous=System.Threading.SynchronizationContext.Current;System.Threading.SynchronizationContext.SetSynchronizationContext(new System.Windows.Threading.DispatcherSynchronizationContext());
  try{
   bool editable=true;var prepare=PanelUi.Button(Locale.T("실행 환경 준비"));var connect=PanelUi.Button(Locale.T("기존 실행기 연결"));var open=PanelUi.Button(Locale.T("실행기 열기"));
   var options=new ModRuntimeOptions(owner,root,work=>System.Threading.Tasks.Task.FromResult(0),null,()=>editable,message=>{},prepare,connect,open,message=>{});
   WaitFor(()=>prepare.IsEnabled);Check(options.Summary.Text==Locale.T("실행 환경 준비 필요"),"Incomplete runtime summary claimed Ready");
   Check(Elements<System.Windows.Controls.Button>(options.View).Count(x=>Convert.ToString(x.Content)==Locale.T("원본 복원"))==0,"Original runtime displayed an inactive Restore action");
   var apply=Elements<System.Windows.Controls.Button>(options.View).Single(x=>Convert.ToString(x.Content)==Locale.T("적용"));Check(apply.IsEnabled,"Original runtime Apply was disabled");
   var management=Elements<System.Windows.Controls.Expander>(options.View).Single();Check(Equals(management.Tag,"inline")&&Elements<System.Windows.Controls.Button>(management).Count()==0,"Advanced management was nested or eagerly created");
   foreach(string file in new[]{"GIMI/d3dx.ini","GIMI/Core/GIMI/main.ini","Resources/Packages/XXMI/Manifest.json","Resources/Packages/XXMI/3dmloader.dll","Resources/Packages/XXMI/d3d11.dll","Resources/Packages/XXMI/d3dcompiler_47.dll","Resources/Packages/GI-FPS-Unlocker/Manifest.json","Resources/Packages/GI-FPS-Unlocker/unlockfps_nc.exe"}){string path=Path.Combine(runtime,file);Directory.CreateDirectory(Path.GetDirectoryName(path));File.WriteAllText(path,file.EndsWith("Manifest.json")?"{\"version\":\"1.1.7\"}":"fixture");}
   AtomicFile.Write(Path.Combine(runtime,"XXMI Launcher Config.json"),"{}");Directory.CreateDirectory(Path.Combine(runtime,"catheryne-4001"));AtomicFile.Write(Path.Combine(runtime,"catheryne-4001","state.json"),CatheryneTools.Json().Serialize(new ModEngineChoice{Enabled=true,PackageVersion="1.1.7",OriginalHash=new string('a',64),BuiltHash=new string('b',64),Commit=new string('c',40)}));options.Refresh();WaitFor(()=>apply.IsEnabled);
   var restore=Elements<System.Windows.Controls.Button>(options.View).Single(x=>Convert.ToString(x.Content)==Locale.T("원본 복원"));Check(restore.IsEnabled&&Convert.ToString(apply.Content)==Locale.T("다시 적용")&&options.Summary.Text.StartsWith(Locale.T("XXMI 준비됨")),"Selected runtime lost restore or summary state");
   var host=new System.Windows.Controls.Border{Child=options.View,Resources=owner.Resources,Padding=new System.Windows.Thickness(16),Background=new System.Windows.Media.SolidColorBrush(System.Windows.Media.Color.FromRgb(29,33,40))};
   host.SetValue(System.Windows.Documents.TextElement.ForegroundProperty,System.Windows.Media.Brushes.White);foreach(int width in new[]{180,560}){
    host.Measure(new System.Windows.Size(width,double.PositiveInfinity));host.Arrange(new System.Windows.Rect(0,0,width,host.DesiredSize.Height));host.UpdateLayout();
    var heading=VisualElements<System.Windows.Controls.TextBlock>(host).First(x=>x.Text.Contains(Locale.T("4001 대응")));Check(heading.TranslatePoint(new System.Windows.Point(),host).X+heading.ActualWidth<=width+.5,"Runtime heading exceeds its surface at width "+width);
    foreach(var action in new[]{apply,restore}){var label=VisualElements<System.Windows.Controls.TextBlock>(action).Single(x=>x.Text==Convert.ToString(action.Content));var origin=label.TranslatePoint(new System.Windows.Point(),action);Check(origin.X>=action.Padding.Left-.5&&origin.X+label.ActualWidth<=action.ActualWidth-action.Padding.Right+.5&&label.ActualHeight<=action.ActualHeight&&action.ActualHeight>=36,"Runtime action label is clipped at width "+width+": "+action.Content+" button="+action.ActualWidth+"x"+action.ActualHeight+" label="+label.ActualWidth+"x"+label.ActualHeight+" wrap="+label.TextWrapping+" max="+label.MaxWidth+" x="+origin.X+" padding="+action.Padding);}
    var image=new System.Windows.Media.Imaging.RenderTargetBitmap(width,(int)Math.Ceiling(host.DesiredSize.Height),96,96,System.Windows.Media.PixelFormats.Pbgra32);image.Render(host);var png=new System.Windows.Media.Imaging.PngBitmapEncoder();png.Frames.Add(System.Windows.Media.Imaging.BitmapFrame.Create(image));using(var output=File.Create(Path.Combine(Path.GetTempPath(),"catheryne-runtime-ui-"+width+".png")))png.Save(output);
   }
   management.IsExpanded=true;Check(Elements<System.Windows.Controls.Button>(management).Contains(connect)&&Elements<System.Windows.Controls.Button>(management).Contains(open),"Advanced management did not include the original launcher controls");
   editable=false;options.Availability();Check(new[]{apply,restore,prepare,connect,open}.All(x=>!x.IsEnabled),"Busy runtime leaves actions enabled");editable=true;options.Availability();Check(apply.IsEnabled&&restore.IsEnabled,"Busy UI lost the selected runtime");
   // The common close action restores the original list instance and the same work footer.
   var list=new System.Windows.Controls.StackPanel();var search=new System.Windows.Controls.TextBox{Text="preserved"};var filter=new System.Windows.Controls.ComboBox();filter.Items.Add("first");filter.Items.Add("second");filter.SelectedIndex=1;var indicator=new PanelWorkIndicator(true);var slot=new System.Windows.Controls.Grid{Height=36};slot.Children.Add(indicator.View);var scroll=new System.Windows.Controls.ScrollViewer{Height=80,Content=new System.Windows.Controls.Border{Height=2000}};list.Children.Add(search);list.Children.Add(filter);list.Children.Add(scroll);list.Children.Add(slot);
   var surface=new System.Windows.Controls.Border{Name="DetailPanel"};var window=new System.Windows.Window{Content=surface,Resources=owner.Resources};System.Windows.NameScope.SetNameScope(window,new System.Windows.NameScope());window.RegisterName("DetailPanel",surface);var detail=new DetailPanel(window);Action showList=()=>detail.Show("mods/contract","모드",list,scrollBody:false);
   showList();surface.Measure(new System.Windows.Size(600,400));surface.Arrange(new System.Windows.Rect(0,0,600,400));surface.UpdateLayout();scroll.ScrollToVerticalOffset(230);surface.UpdateLayout();WaitFor(()=>scroll.VerticalOffset>0);double offset=scroll.VerticalOffset;Action showSettings=()=>detail.Show("mods/runtime-contract","실행 환경",options.View,closed:()=>{PanelUi.Detach(slot);list.Children.Add(slot);},back:showList,footer:slot);showSettings();indicator.Begin("4001 대응 준비 중…");Check(!list.Children.Contains(slot)&&slot.Parent is System.Windows.Controls.Border,"Work footer was duplicated instead of moved");
   foreach(int width in new[]{320,900}){surface.Measure(new System.Windows.Size(width,400));surface.Arrange(new System.Windows.Rect(0,0,width,400));surface.UpdateLayout();Check(slot.ActualHeight==36&&slot.TranslatePoint(new System.Windows.Point(),surface).Y+slot.ActualHeight<=400,"Runtime work footer was clipped on a small screen");}
   var shell=(System.Windows.Controls.Grid)surface.Child;var close=(System.Windows.Controls.Button)((System.Windows.Controls.DockPanel)shell.Children[0]).Children[0];close.RaiseEvent(new System.Windows.RoutedEventArgs(System.Windows.Controls.Button.ClickEvent));
   Check(!detail.IsShowing("mods/contract")&&!detail.IsShowing("mods/runtime-contract")&&surface.Visibility==System.Windows.Visibility.Collapsed&&list.Children.Contains(slot)&&search.Text=="preserved"&&filter.SelectedIndex==1&&Math.Abs(scroll.VerticalOffset-offset)<.1,"Close did not dismiss the runtime panel or preserve its list state");showList();showSettings();shell=(System.Windows.Controls.Grid)surface.Child;var back=(System.Windows.Controls.Button)((System.Windows.Controls.DockPanel)shell.Children[0]).Children[1];Check(Convert.ToString(back.ToolTip)==Locale.T("뒤로가기"),"Runtime child page lacks the common Back control");back.RaiseEvent(new System.Windows.RoutedEventArgs(System.Windows.Controls.Button.ClickEvent));Check(detail.IsShowing("mods/contract")&&search.Text=="preserved"&&filter.SelectedIndex==1&&Math.Abs(scroll.VerticalOffset-offset)<.1&&list.Children.Contains(slot),"Back lost list state or the shared work footer");detail.Hide();window.Close();
  }finally{System.Threading.SynchronizationContext.SetSynchronizationContext(previous);ModManager.DeleteInside(root,Path.GetTempPath());}
 }
 internal static void Run(){
  string root=Path.Combine(Path.GetTempPath(),"mod-engine-contract-"+Guid.NewGuid().ToString("N")),runtime=Path.Combine(root,"runtime"),libs=Path.Combine(runtime,"Resources","Packages","XXMI"),gimi=Path.Combine(runtime,"GIMI");Directory.CreateDirectory(libs);Directory.CreateDirectory(gimi);
  string configFile=Path.Combine(runtime,"XXMI Launcher Config.json"),dll=Path.Combine(gimi,"d3d11.dll"),state=Path.Combine(runtime,"catheryne-4001","state.json");
  try{
   var config=new Dictionary<string,object>{{"future",123},{"Importers",new Dictionary<string,object>{{"GIMI",new Dictionary<string,object>{{"Migoto",new Dictionary<string,object>{{"unsafe_mode",false},{"future",456}}}}}}}};
   ModEngineConsent.Sign(runtime,config);AtomicFile.Write(configFile,CatheryneTools.Json().Serialize(config));
   string publicKey=File.ReadAllText(Path.Combine(runtime,"Resources","Security","public_key.der"));string keyHash=UpdateService.Hash(Path.Combine(runtime,"Resources","Security","private_key.der"));
   ModEngineConsent.Sign(runtime,config);Check(UpdateService.Hash(Path.Combine(runtime,"Resources","Security","private_key.der"))==keyHash,"Consent replaced an existing XXMI key");
   Action<byte[],string> package=(bytes,version)=>{var signatures=new Dictionary<string,string>();using(var key=CngKey.Import(Convert.FromBase64String(File.ReadAllText(Path.Combine(runtime,"Resources","Security","private_key.der"))),CngKeyBlobFormat.Pkcs8PrivateBlob)){foreach(string name in new[]{"3dmloader.dll","d3d11.dll","d3dcompiler_47.dll"}){File.WriteAllBytes(Path.Combine(libs,name),bytes);signatures[name]=ModEngineConsent.Sign(key,bytes);}}AtomicFile.Write(Path.Combine(libs,"Manifest.json"),CatheryneTools.Json().Serialize(new{version=version,signatures=signatures}));};
   Action<string,string> verify=(path,name)=>ModRuntimePackages.ValidateLibraryAt(Path.Combine(path,"Resources","Packages","XXMI"),name,publicKey);
   var original=Dll(1);package(original,"1.1.7");File.WriteAllBytes(dll,original);
   Directory.CreateDirectory(Path.Combine(gimi,"Mods","Personal"));string personal=Path.Combine(gimi,"Mods","Personal","effect.ini");File.WriteAllText(personal,"[TextureOverrideFixture]");
   int builds=0;Func<string,string,Action<ModProgress>,ModEngineBuildResult> build=(version,folder,progress)=>{builds++;return new ModEngineBuildResult{Bytes=Dll((byte)(builds+1)),Commit=new string('a',40)};};
   ModEngine4001.Apply(runtime,null,()=>false,build,null,verify);Check(ModEngine4001.Status(runtime).Applied,"Managed engine or consent was not applied");Check(File.ReadAllBytes(Path.Combine(libs,"d3d11.dll")).SequenceEqual(original),"Signed package was modified");Check(File.ReadAllText(personal)=="[TextureOverrideFixture]","Engine management changed a personal mod");config=StoryClient.Read(configFile);Check(Equals(config["future"],123)&&Equals(Mode(config)["future"],456),"Apply discarded unrelated config");
   ModEngine4001.Ensure(runtime,null,()=>false,build,verify);Check(builds==1,"Unchanged engine rebuilt at every launch");
   byte[] applied=File.ReadAllBytes(dll),beforeConfig=File.ReadAllBytes(configFile),beforeState=File.ReadAllBytes(state);
   Reject(()=>ModEngine4001.Restore(runtime,null,()=>true,null,verify),"Busy restore was accepted");Check(File.ReadAllBytes(dll).SequenceEqual(applied),"Busy guard changed the engine");
   Reject(()=>ModEngine4001.Apply(runtime,null,()=>false,build,step=>{if(step=="config")throw new IOException("fixture");},verify),"Failed commit was accepted");
   Check(File.ReadAllBytes(dll).SequenceEqual(applied)&&File.ReadAllBytes(configFile).SequenceEqual(beforeConfig)&&File.ReadAllBytes(state).SequenceEqual(beforeState),"Apply rollback failed to restore DLL, config and state");
   Reject(()=>ModEngine4001.Apply(runtime,null,()=>false,(v,s,p)=>{throw new IOException("fixture");},null,verify),"Build failure was accepted");Check(File.ReadAllBytes(dll).SequenceEqual(applied)&&File.ReadAllBytes(state).SequenceEqual(beforeState),"Failed build changed selection or engine");
   Reject(()=>ModEngine4001.Apply(runtime,null,()=>false,(v,s,p)=>new ModEngineBuildResult{Bytes=new byte[256],Commit=new string('a',40)},null,verify),"Invalid build result was installed");
   File.WriteAllBytes(dll,Dll(99));Reject(()=>ModEngine4001.Ensure(runtime,null,()=>false,build,verify),"External replacement was silently accepted");Check(File.ReadAllBytes(dll).SequenceEqual(Dll(99)),"Ensure overwrote an external change");
   ModEngine4001.Restore(runtime,null,()=>false,null,verify);config=StoryClient.Read(configFile);Check(File.ReadAllBytes(dll).SequenceEqual(original)&&Equals(Mode(config)["unsafe_mode"],false)&&!Mode(config).ContainsKey("unsafe_mode_signature")&&!ModEngine4001.Read(runtime).Enabled,"Restore did not recover original engine and setting presence");
   ModEngine4001.Apply(runtime,null,()=>false,build,null,verify);package(Dll(7),"1.1.8");int before=builds;ModEngine4001.Ensure(runtime,null,()=>false,build,verify);Check(builds==before+1&&ModEngine4001.Read(runtime).PackageVersion=="1.1.8"&&ModEngine4001.Status(runtime).Applied,"Update did not reconcile the selected engine");
   applied=File.ReadAllBytes(dll);beforeConfig=File.ReadAllBytes(configFile);beforeState=File.ReadAllBytes(state);
   Reject(()=>ModEngine4001.Restore(runtime,null,()=>false,step=>{if(step=="state")throw new IOException("fixture");},verify),"Failed restore was accepted");
   Check(File.ReadAllBytes(dll).SequenceEqual(applied)&&File.ReadAllBytes(configFile).SequenceEqual(beforeConfig)&&File.ReadAllBytes(state).SequenceEqual(beforeState),"Restore rollback failed");
   package(Dll(8),"1.1.9");Reject(()=>ModEngine4001.Ensure(runtime,null,()=>false,(v,s,p)=>{throw new IOException("fixture");},verify),"Failed update rebuild was accepted");Check(File.ReadAllBytes(dll).SequenceEqual(applied)&&ModEngine4001.Read(runtime).Enabled,"Update failure lost prior engine or choice");
   ModEngine4001.Restore(runtime,null,()=>false,null,verify);Check(File.ReadAllBytes(dll).SequenceEqual(Dll(8)),"Restore installed an incompatible pre-update DLL");
   File.WriteAllBytes(Path.Combine(libs,"d3d11.dll"),Dll(9));Reject(()=>ModEngine4001.Apply(runtime,null,()=>false,build,null,verify),"Corrupted original package was accepted");Check(File.ReadAllBytes(dll).SequenceEqual(Dll(8)),"Signature failure changed the deployed engine");
   Reject(()=>ModEngineBuild.SourceCommit("../latest"),"Source version injection was accepted");
   // This protocol adapts only our explicit engine choice; absent choice leaves external runtimes alone.
   string blank=Path.Combine(root,"blank");Directory.CreateDirectory(blank);ModEngine4001.Ensure(blank,null,()=>false,build,verify);Check(!Directory.Exists(Path.Combine(blank,"catheryne-4001")),"Default mode created engine state");
  }finally{ModManager.DeleteInside(root,Path.GetTempPath());}
 }
}
