using System;using System.IO;using System.IO.Compression;using System.Linq;using System.Collections.Generic;
internal static class ModManagerTests {
 static void GroupContracts(){
  string root=Path.Combine(Path.GetTempPath(),"mod-groups-"+Guid.NewGuid().ToString("N"));var manager=new ModManager(root,()=>false);var initial=manager.Read();var water=ModBuiltins.ListEntries(initial.Items).Single(x=>ModBuiltins.GroupOf(x[0])!=null);
  Check(water.Length==3&&ModBuiltins.ListEntries(initial.Items).Count()==7,"Water package must have one card and three independent identities");
  Check((Locale.IsEnglish?new[]{"bubbles","contrails","filter"}:new[]{"기포","잔상","필터"}).All(x=>ModPanel.SearchEntry(water,x))&&ModPanel.SearchEntry(water,ModPanel.EntryName(water)),"Grouped search hides an option alias");
  for(int mask=0;mask<8;mask++){
   var state=manager.Read();foreach(var item in state.Items)item.Enabled=false;for(int i=0;i<water.Length;i++)state.Items.Single(x=>x.Id==water[i].Id).Enabled=(mask&(1<<i))!=0;
   Directory.CreateDirectory(Path.Combine(root,"mods"));string file=Path.Combine(root,"mods","state.json");AtomicFile.Write(file,CatheryneTools.Json().Serialize(state));string before=File.ReadAllText(file);var read=manager.Read();var entries=ModBuiltins.ListEntries(read.Items).ToArray();Check(entries.SelectMany(x=>x).Select(x=>x.Id).Distinct().Count()==read.Items.Count&&File.ReadAllText(file)==before,"Grouping writes state or drops option identities");
   foreach(var item in read.Items.Where(x=>ModBuiltins.GroupOf(x)!=null)){Directory.CreateDirectory(manager.Payload(item));File.WriteAllText(Path.Combine(manager.Payload(item),"effect.ini"),"namespace = "+item.Builtin+"\n[TextureOverrideFixture]");}
   string runtime=Path.Combine(root,"runtime");manager.Apply(runtime);string applied=Path.Combine(runtime,"GIMI","Mods","Catheryne");Check(water.All(x=>Directory.Exists(Path.Combine(applied,x.Id))==read.Items.Single(y=>y.Id==x.Id).Enabled),"Grouped option selection changed executable projection");
  }
  var prior=manager.Read();manager.SetEnabled(water[0].Id,false);var after=manager.Read();Check(water.Skip(1).All(x=>prior.Items.Single(y=>y.Id==x.Id).Enabled==after.Items.Single(y=>y.Id==x.Id).Enabled),"Turning off one grouped option changed another");manager.DisableAll();Check(!manager.Enabled,"Disable-all misses grouped options");ModManager.DeleteInside(root,Path.GetTempPath());
 }
 static void Check(bool condition,string message){if(!condition)throw new Exception(message);}
 internal static void Run(){ModEngineTests.Run();BindingContracts();LaunchContracts();StartupPresentationContracts();GroupContracts();PresentationContracts();PackageContracts();RuntimeContracts();string root=Path.Combine(Path.GetTempPath(),"catheryne-mod-test-"+Guid.NewGuid().ToString("N"));Directory.CreateDirectory(root);try{
  string data=Path.Combine(root,"data"),source=Path.Combine(root,"personal-mod"),runtime=Path.Combine(root,"xxmi");Directory.CreateDirectory(source);File.WriteAllText(Path.Combine(source,"skin.ini"),"[TextureOverrideTest]\nhash = aabbccdd");File.WriteAllText(Path.Combine(source,"mesh.buf"),"fixture");
  var mods=new ModManager(data,()=>false);Check(mods.Read().Items.Count(x=>x.Builtin!=null)==ModBuiltins.Catalog.Length&&mods.Read().Items.All(x=>!x.Enabled),"Builtins missing or enabled by default");Check(!mods.Enabled&&!mods.Pending,"Empty mod route changed");var item=mods.Import(source);Check(!item.Enabled&&!mods.Enabled,"Imported mod enabled without selection");mods.SetEnabled(item.Id,true);Check(mods.Enabled&&mods.Pending,"Enabled route missing");mods.Apply(runtime);Check(File.Exists(Path.Combine(runtime,"GIMI","Mods","Catheryne",item.Id,"skin.ini"))&&!mods.Pending,"Active projection missing");Check(File.ReadAllText(Path.Combine(source,"skin.ini")).Contains("aabbccdd"),"Original mod changed");mods.DisableAll();Check(!mods.Enabled&&mods.Pending,"Disable-all route failed");mods.Apply(runtime);Check(!Directory.GetFiles(Path.Combine(runtime,"GIMI","Mods","Catheryne"),"*.ini",SearchOption.AllDirectories).Any(),"Disabled mod still loads");mods.SetEnabled(item.Id,true);mods.Apply(runtime);Check(mods.Read().Items.Count(x=>x.Builtin==null)==1,"Managed projection rediscovered");
  string exe=Path.Combine(runtime,"Resources","Bin","XXMI Launcher.exe");Directory.CreateDirectory(Path.GetDirectoryName(exe));File.WriteAllText(exe,"fixture");ModIntegration.Connect(data,exe,()=>false);string external=Path.Combine(runtime,"GIMI","Mods","Existing");Directory.CreateDirectory(external);File.WriteAllText(Path.Combine(external,"mod.ini"),"[TextureOverrideTest]");var a=mods.Read().Items.Single(x=>x.ExternalFolder!=null);var b=mods.Read().Items.Single(x=>x.ExternalFolder!=null);Check(a.Id==b.Id,"External identity unstable");mods.SetEnabled(a.Id,false);mods.Apply(runtime);Check(Directory.Exists(Path.Combine(runtime,"GIMI","Mods","DISABLED_Existing")),"External toggle failed");mods.SetEnabled(a.Id,true);mods.Apply(runtime);Check(Directory.Exists(external),"External restore failed");
  var config=UnlockerOptions.Defaults();config["GamePath"]=Path.Combine(root,"Game Folder","GenshinImpact.exe");config["FPSTarget"]=144;config["UnknownFutureOption"]="preserve";File.WriteAllText(Path.Combine(runtime,"XXMI Launcher Config.json"),"{\"Future\":123,\"Importers\":{\"GIMI\":{\"Importer\":{\"unknown_setting\":42}}}}");var mapped=ModIntegration.Configure(runtime,config,true);var importer=CodexChat.Map(CodexChat.Map(CodexChat.Map(mapped["Importers"])["GIMI"])["Importer"]);Check(Convert.ToInt32(mapped["Future"])==123&&Convert.ToInt32(importer["unknown_setting"])==42,"Unknown XXMI configuration discarded");Check(Convert.ToInt32(importer["unlock_fps_value"])==144&&Equals(importer["unlock_fps"],true)&&Convert.ToString(importer["launch_options"]).Contains("-screen-fullscreen"),"FPS/display settings not bridged");Check(!ModIntegration.ImporterReady(runtime),"Unprepared importer reported ready");File.WriteAllText(Path.Combine(runtime,"GIMI","d3dx.ini"),"[Include]");Check(ModIntegration.ImporterReady(runtime),"Prepared importer missing");var info=ModIntegration.StartInfo(runtime,Convert.ToString(config["GamePath"]));Check(info.Arguments.Contains("--nogui")&&info.Arguments.Contains("\""),"Quoted quick launch missing");
  string bad=Path.Combine(root,"bad.zip");using(var zip=ZipFile.Open(bad,ZipArchiveMode.Create)){var e=zip.CreateEntry("../escape.ini");using(var w=new StreamWriter(e.Open()))w.Write("bad");}bool rejected=false;try{mods.Import(bad);}catch(InvalidDataException){rejected=true;}Check(rejected&&!File.Exists(Path.Combine(data,"mods","escape.ini")),"Archive traversal accepted");
  File.WriteAllText(Path.Combine(source,"payload.exe"),"fixture");rejected=false;try{mods.Import(source);}catch(InvalidDataException){rejected=true;}Check(rejected,"Executable mod payload accepted");
  Check(mods.Read().Items.Count(x=>x.Builtin==null)==2,"Failed import changed registry");
  string disabled=Path.Combine(runtime,"GIMI","Mods","DISABLEDAlreadyOff");Directory.CreateDirectory(disabled);File.WriteAllText(Path.Combine(disabled,"mod.ini"),"[TextureOverrideFixture]");var importedExternal=mods.Read().Items.Single(x=>x.Name=="AlreadyOff");Check(!importedExternal.Enabled,"Disabled external mod activated on discovery");mods.SetEnabled(importedExternal.Id,true);mods.Apply(runtime);Check(Directory.Exists(Path.Combine(runtime,"GIMI","Mods","AlreadyOff")),"Existing disabled naming not restored");
  mods.DisableAll();Check(!ModIntegration.TryStart(data,config,false,()=>false),"All-off route opened XXMI");
  bool busy=true;var guarded=new ModManager(data,()=>busy);string before=File.ReadAllText(Path.Combine(data,"mods","state.json"));int blocked=0;
  foreach(Action change in new Action[]{()=>guarded.Import(source),()=>guarded.SetEnabled(item.Id,true),()=>guarded.DisableAll(),()=>guarded.SetTarget(item.Id,"common"),()=>guarded.Apply(runtime),()=>guarded.ForLaunch(active=>{throw new Exception("Busy launch callback ran");})}){try{change();}catch(InvalidOperationException){blocked++;}}
  Check(blocked==6&&before==File.ReadAllText(Path.Combine(data,"mods","state.json")),"Busy mutation changed registry");busy=false;guarded.SetEnabled(item.Id,true);
  Check(PanelNavigation.Group("Graphics")=="화면·성능"&&PanelNavigation.Group("Mods")=="화면·성능"&&PanelNavigation.Group("SettingsPage")=="설정","Menu owners disagree");
  Check(ModBuiltins.Catalog.All(x=>x.Available),"Builtins must be connected");
  mods.SetTarget(item.Id,"character:Wanderer");Check(ModManager.Kind(mods.Read().Items.Single(x=>x.Id==item.Id))=="character","Character filter metadata missing");mods.SetTarget(item.Id,"common");Check(ModManager.Kind(mods.Read().Items.Single(x=>x.Id==item.Id))=="common","Common filter metadata missing");mods.SetTarget(item.Id,"");Check(ModManager.Kind(mods.Read().Items.Single(x=>x.Id==item.Id))=="unclassified","Unknown target discarded");Check(ModManager.InferTarget("Wanderer_skin")=="character:Wanderer"&&ModManager.InferTarget("Mystery mod")==null,"Filename inference invented a target");
  string skin=Path.Combine(root,"Wanderer_skin");Directory.CreateDirectory(skin);File.WriteAllText(Path.Combine(skin,"skin.ini"),"[Constants]");var categorized=mods.Import(skin);Check(categorized.Target=="character:Wanderer","Import classification missing");mods.SetTarget(categorized.Id,"");Check(ModManager.Kind(mods.Read().Items.Single(x=>x.Id==categorized.Id))=="unclassified","Explicit unknown target overridden by inference");
  rejected=false;try{mods.SetTarget(item.Id,"character:Unknown");}catch(ArgumentException){rejected=true;}Check(rejected,"Invalid character classification accepted");

  var transparency=mods.Read().Items.Single(x=>x.Builtin=="transparency");mods.SetEnabled(transparency.Id,true);rejected=false;try{mods.Apply(runtime);}catch(InvalidOperationException){rejected=true;}Check(rejected,"Missing TexFx accepted");
  string texfx=Path.Combine(runtime,"GIMI","Core","GIMI","Libraries","TexFx","Config.ini");Directory.CreateDirectory(Path.GetDirectoryName(texfx));File.WriteAllText(texfx,"namespace = TexFx\n[Constants]\nglobal $uncensor = 2\n");string prior=File.ReadAllText(texfx);mods.Apply(runtime);
  Check(File.ReadAllText(Path.Combine(runtime,"GIMI","Mods","Catheryne",transparency.Id,"TexFxSettings.ini")).Contains(@"post $\TexFx\uncensor = 0")&&File.ReadAllText(texfx)==prior,"TexFx user settings changed library");
  string settings=Path.Combine(mods.Payload(transparency),"TexFxSettings.ini");File.WriteAllText(settings,"namespace = TexFx\n[Constants]\npost $uncensor = 0");mods.Apply(runtime);Check(File.ReadAllText(settings).Contains("namespace = Catheryne.Transparency"),"Cached generated settings were not migrated");
  File.WriteAllText(Path.Combine(mods.Payload(categorized),"mod.ini"),"namespace = TexFx\n[Constants]");mods.SetEnabled(categorized.Id,true);bool duplicate=false;try{mods.Apply(runtime);}catch(InvalidOperationException){duplicate=true;}Check(duplicate,"Duplicate library reached original XXMI dialog");mods.SetEnabled(categorized.Id,false);
  DateTime unchanged=File.GetLastWriteTimeUtc(settings);mods.Apply(runtime);Check(File.GetLastWriteTimeUtc(settings)==unchanged,"Unchanged generated INI invalidated optimizer cache");
  string rogue=Path.Combine(mods.Payload(categorized),"rogue.ini");File.WriteAllText(rogue,"[System]\n[Constants]");mods.SetEnabled(categorized.Id,true);bool rejectedGlobal=false;try{mods.Apply(runtime);}catch(InvalidOperationException){rejectedGlobal=true;}Check(rejectedGlobal&&!File.Exists(Path.Combine(runtime,"GIMI","Mods","Catheryne",categorized.Id,"rogue.ini")),"Global loader configuration reached native XXMI warning");mods.SetEnabled(categorized.Id,false);File.Delete(rogue);
  mods.SetEnabled(transparency.Id,false);mods.Apply(runtime);Check(!Directory.Exists(Path.Combine(runtime,"GIMI","Mods","Catheryne",transparency.Id))&&File.ReadAllText(texfx)==prior,"Disabled builtin left settings behind");
  var uid=mods.Read().Items.Single(x=>x.Builtin=="hide-uid");string uidPayload=mods.Payload(uid);Directory.CreateDirectory(Path.Combine(uidPayload,"UILib"));File.WriteAllText(Path.Combine(uidPayload,"uid.ini"),"namespace = HideUID");File.WriteAllText(Path.Combine(uidPayload,"UILib","UILib.ini"),"namespace = UI");mods.SetEnabled(uid.Id,true);File.WriteAllText(Path.Combine(runtime,"GIMI","Mods","DISABLED_Existing","UILib.ini"),"namespace = UI");mods.SetEnabled(a.Id,true);mods.Apply(runtime);Check(!Directory.Exists(Path.Combine(runtime,"GIMI","Mods","Catheryne",uid.Id,"UILib")),"Duplicate UI library projected");mods.SetEnabled(a.Id,false);mods.Apply(runtime);Check(Directory.Exists(Path.Combine(runtime,"GIMI","Mods","Catheryne",uid.Id,"UILib")),"Missing builtin dependency not restored");
  mods.SetEnabled(a.Id,true);File.Delete(Path.Combine(runtime,"GIMI","Mods","DISABLED_Existing","UILib.ini"));string nestedDisabled=Path.Combine(runtime,"GIMI","Mods","DISABLED_Existing","DISABLED_Library");Directory.CreateDirectory(nestedDisabled);File.WriteAllText(Path.Combine(nestedDisabled,"UILib.ini"),"namespace = UI");mods.Apply(runtime);Check(Directory.Exists(Path.Combine(runtime,"GIMI","Mods","Catheryne",uid.Id,"UILib")),"Disabled nested library reused");
  var clutter=mods.Read().Items.Single(x=>x.Builtin=="ui-clutter");string clutterPayload=mods.Payload(clutter);Directory.CreateDirectory(Path.Combine(clutterPayload,"UILib"));File.WriteAllText(Path.Combine(clutterPayload,"main.ini"),"namespace = ClutterReducer\n[Constants]\nglobal $FRAMERATE = 60");File.WriteAllText(Path.Combine(clutterPayload,"UILib","UILib.ini"),"namespace = UI");mods.SetEnabled(clutter.Id,true);mods.Apply(runtime);
  string projection=Path.Combine(runtime,"GIMI","Mods","Catheryne");Check(Directory.Exists(Path.Combine(projection,uid.Id,"UILib"))&&!Directory.Exists(Path.Combine(projection,clutter.Id,"UILib")),"Two builtins duplicated or removed the shared UI library");string frameSettings=Path.Combine(projection,clutter.Id,"ClutterRuntime.ini");Check(File.ReadAllText(frameSettings).Contains(@"post $\ClutterReducer\FRAMERATE = 144"),"Clutter animation frame rate not taken from canonical launch configuration");DateTime frameTime=File.GetLastWriteTimeUtc(frameSettings);mods.Apply(runtime);Check(frameTime==File.GetLastWriteTimeUtc(frameSettings),"Unchanged frame setting discarded native optimizer cache");
  mods.SetEnabled(uid.Id,false);mods.Apply(runtime);Check(Directory.Exists(Path.Combine(projection,clutter.Id,"UILib")),"Shared UI library was not transferred to remaining builtin");mods.SetEnabled(uid.Id,true);string userUi=Path.Combine(runtime,"GIMI","Mods","Existing","UI.ini");File.WriteAllText(userUi,"namespace = UI");mods.Apply(runtime);Check(!Directory.Exists(Path.Combine(projection,uid.Id,"UILib"))&&!Directory.Exists(Path.Combine(projection,clutter.Id,"UILib")),"External UI library was duplicated");File.Delete(userUi);
  string coreUi=Path.Combine(runtime,"GIMI","Core","GIMI","Libraries","UI.ini");File.WriteAllText(coreUi,"namespace = UI");mods.Apply(runtime);Check(!Directory.Exists(Path.Combine(projection,uid.Id,"UILib"))&&!Directory.Exists(Path.Combine(projection,clutter.Id,"UILib")),"Core UI library was duplicated");File.Delete(coreUi);File.WriteAllText(Path.Combine(runtime,"XXMI Launcher Config.json"),"{}");mods.Apply(runtime);Check(File.ReadAllText(frameSettings).Contains("FRAMERATE = 60"),"Incomplete runtime configuration did not use regular game frame rate");
  mods.DisableAll();mods.SetEnabled(item.Id,true);mods.Apply(runtime);File.Delete(Path.Combine(mods.Payload(item),"skin.ini"));File.Delete(Path.Combine(mods.Payload(item),"mesh.buf"));Directory.Delete(mods.Payload(item));bool failed=false;try{mods.Apply(runtime);}catch(IOException){failed=true;}Check(failed&&File.Exists(Path.Combine(runtime,"GIMI","Mods","Catheryne",item.Id,"skin.ini")),"Failed projection destroyed prior mod files");
 }finally{Directory.Delete(root,true);}}
 static void PresentationContracts(){
  string root=Path.Combine(Path.GetTempPath(),"catheryne-mod-presentation-"+Guid.NewGuid().ToString("N"));Directory.CreateDirectory(root);
  try{
   string account=Path.Combine(root,"account.json");File.WriteAllText(account,"{\"format\":\"GOOD\",\"characters\":[{\"key\":\"Wanderer\",\"identity\":\"game:10000075\",\"gameId\":10000075,\"level\":90},{\"gameId\":10000999,\"names\":{\"ko\":\"새 캐릭터\"},\"level\":88}]}");new ProfileStore(root).Import("account",account);var manager=new ModManager(root,()=>false);Check(manager.Characters().Length==2,"Owned character list changed account facts");
   string source=Path.Combine(root,"anonymous");Directory.CreateDirectory(source);File.WriteAllText(Path.Combine(source,"mod.ini"),"[Constants]");var item=manager.Import(source,"character:game:10000999");Check(item.Target=="character:game:10000999"&&!item.Enabled,"Owned character context was discarded");manager.SetTarget(item.Id,"character:Wanderer");Check(manager.Read().Items.Single(x=>x.Id==item.Id).Target=="character:game:10000075","Catalog alias did not resolve to owned identity");manager.SetTarget(item.Id,"character:game:10000999");
   string named=Path.Combine(root,"새 캐릭터_의상");Directory.CreateDirectory(named);File.WriteAllText(Path.Combine(named,"mod.ini"),"[Constants]");Check(manager.Import(named).Target=="character:game:10000999","New owned character name needed a release mapping");
   string preview=Path.Combine(source,"preview.png");var bitmap=new System.Windows.Media.Imaging.RenderTargetBitmap(2,2,96,96,System.Windows.Media.PixelFormats.Pbgra32);var encoder=new System.Windows.Media.Imaging.PngBitmapEncoder();encoder.Frames.Add(System.Windows.Media.Imaging.BitmapFrame.Create(bitmap));using(var output=File.Create(preview))encoder.Save(output);
   manager.SetCover(item.Id,preview);item=manager.Read().Items.Single(x=>x.Id==item.Id);Check(ModArtwork.Local(item,manager)==Path.Combine(root,"mods","covers",item.Id+".png"),"Selected cover escaped private cover storage");Check(!Directory.GetFiles(manager.Payload(item),"*.png",SearchOption.AllDirectories).Any(),"Presentation image entered executable projection");
   string prior=File.ReadAllText(Path.Combine(root,"mods","state.json"));File.WriteAllText(preview,"invalid image");bool rejected=false;try{manager.SetCover(item.Id,preview);}catch{rejected=true;}Check(rejected&&File.ReadAllText(Path.Combine(root,"mods","state.json"))==prior,"Bad cover changed mod registry");
   item.Cover="../account.json";Check(ModArtwork.Local(item,manager)==null,"Unsafe cover path accepted");
  }finally{Directory.Delete(root,true);}
 }
 static void PackageContracts(){
  string root=Path.Combine(Path.GetTempPath(),"modpk-"+Guid.NewGuid().ToString("N"));Directory.CreateDirectory(root);
  try{
   Check(ModBuiltins.Catalog.Select(x=>x.Id).Distinct().Count()==ModBuiltins.Catalog.Length&&new[]{"ui-clutter","outline-resizer","water-censor","water-bubbles","water-contrails","switch-prompts"}.All(key=>ModBuiltins.Catalog.Any(x=>x.Key==key&&x.Available)),"Curated builtin identities or new candidates missing");
   Check(ModBuiltins.Catalog.Select(x=>x.Order).Distinct().Count()==ModBuiltins.Catalog.Length&&ModBuiltins.Catalog.All(x=>!string.IsNullOrEmpty(x.Author)&&!string.IsNullOrEmpty(x.Description)),"Builtin detail metadata or recommendation order missing");
   var ordered=ModBuiltins.Ordered(ModBuiltins.Catalog.Reverse().Select(x=>new ManagedMod{Id=x.Id,Builtin=x.Key,Name=x.Name}).Concat(new[]{new ManagedMod{Id="personal",Name="AAA"}})).ToArray();Check(ordered.First().Builtin=="dark-loading"&&ordered.Last().Id=="personal"&&ordered.Select(x=>x.Id).Distinct().Count()==ordered.Length,"Recommendation order changed builtin identity or personal grouping");
   string cache=Path.Combine(root,"mods","packages");Directory.CreateDirectory(cache);string archive=Path.Combine(cache,"fixture.zip");using(var zip=ZipFile.Open(archive,ZipArchiveMode.Create)){foreach(var entry in new[]{new[]{"README.txt","Original instructions"},new[]{"Module/DISABLED-Bubbles.ini","namespace = Bubbles"},new[]{"Module/Other.ini","namespace = Other"},new[]{"Module/Extras/UID.ini","namespace = Extra"}}){using(var writer=new StreamWriter(zip.CreateEntry(entry[0]).Open()))writer.Write(entry[1]);}}
   string stage=Path.Combine(root,"stage");Directory.CreateDirectory(stage);var selected=new BuiltinPackage{Folder="Selected",File="fixture",Hash=UpdateService.Hash(archive),Source="https://example.invalid/fixture",Credit="Fixture",SelectPath="Module/DISABLED-Bubbles.ini"};ModBuiltins.Unpack(root,stage,selected,null);string folder=Path.Combine(stage,"Selected");Check(Directory.GetFiles(folder,"*.ini",SearchOption.AllDirectories).Length==1&&File.ReadAllText(Path.Combine(folder,"Bubbles.ini"))=="namespace = Bubbles"&&File.ReadAllText(Path.Combine(folder,"README.txt"))=="Original instructions","Selected module changed bytes or enabled unrelated optional effects");
   var full=new BuiltinPackage{Folder="Full",File="fixture",Hash=selected.Hash,Source=selected.Source,Credit="Fixture",SelectPath="Module",DisabledFolder="Extras"};ModBuiltins.Unpack(root,stage,full,null);Check(File.Exists(Path.Combine(stage,"Full","Other.ini"))&&File.Exists(Path.Combine(stage,"Full","DISABLED_Extras","UID.ini"))&&!Directory.Exists(Path.Combine(stage,"Full","Module")),"Vendor wrapper or optional extras projection changed relative module layout");
   string before=File.ReadAllText(Path.Combine(stage,"Full","Other.ini"));var bad=new BuiltinPackage{Folder="Bad",File="fixture",Hash=selected.Hash,Source=selected.Source,Credit="Fixture",SelectPath="../escape.ini"};bool rejected=false;try{ModBuiltins.Unpack(root,stage,bad,null);}catch(InvalidDataException){rejected=true;}Check(rejected&&before==File.ReadAllText(Path.Combine(stage,"Full","Other.ini")),"Package content selection escaped its folder");
  }finally{Directory.Delete(root,true);}
 }
 static void BindingContracts(){
  string root=Path.Combine(Path.GetTempPath(),"mod-keys-"+Guid.NewGuid().ToString("N"));Directory.CreateDirectory(root);try{
   string source=Path.Combine(root,"fixture");Directory.CreateDirectory(source);string original="; original\r\n\r\nnamespace = Fixture\r\n[KeyToggle]\r\ncondition = $active\r\nkey = no_modifiers F11 ; preserve comment\r\nkey = XB_A\r\nback = NO_ALT CTRL F11\r\n\r\n[CommandListFixture]\r\nkey = F3\r\n";File.WriteAllText(Path.Combine(source,"effect.ini"),original);string disabled=Path.Combine(source,"DISABLED_Optional");Directory.CreateDirectory(disabled);File.WriteAllText(Path.Combine(disabled,"other.ini"),"[KeyDisabled]\nkey = F11");var manager=new ModManager(root,()=>false);var item=manager.Import(source);var keys=ModBindings.Read(item,manager);Check(keys.Length==3&&keys[0].Line==5,"Binding parser includes disabled INIs or non-Key command sections");Check(!ModBindings.CanEdit(keys[1])&&ModBindings.CanEdit(keys[0]),"Unknown controller syntax must stay read-only");
   Check(ModBindings.Overlap("f11","ctrl VK_F11")&&!ModBindings.Overlap("no_modifiers f11","ctrl F11")&&ModBindings.Overlap("VK_OEM_PLUS","0xBB")&&!ModBindings.Overlap("Alt 0","no_alt 0"),"Modifier wildcard overlap or key aliases are incorrect");
   string captured=ModBindings.Capture(System.Windows.Input.Key.F12,System.Windows.Input.ModifierKeys.Control);Check(ModBindings.Display(captured)=="Ctrl+F12"&&!ModBindings.Overlap(captured,"no_modifiers F12"),"Captured bindings must forbid unspecified modifiers");
   manager.SetEnabled(item.Id,true);string runtime=ModIntegration.ManagedRoot(root);Directory.CreateDirectory(Path.Combine(runtime,"Resources","Bin"));File.WriteAllText(Path.Combine(runtime,"Resources","Bin","XXMI Launcher.exe"),"");manager.Apply(runtime);string signature=manager.Read().AppliedSignature;manager.SetKey(item.Id,keys[0],captured);Check(manager.Pending&&manager.Read().Items.Single(x=>x.Id==item.Id).Keys.Count==1,"Key override must be canonical and pending");manager.Apply(runtime);string output=File.ReadAllText(Path.Combine(runtime,"GIMI","Mods","Catheryne",item.Id,"effect.ini"));Check(output.Contains("key = "+captured+" ; preserve comment")&&output.Contains("key = XB_A")&&output.Contains("back = NO_ALT CTRL F11")&&output.Contains("condition = $active"),"Projection changed unrelated binding, condition, or comment");Check(File.ReadAllText(Path.Combine(manager.Payload(item),"effect.ini"))==original,"Original mod bytes must remain unchanged");
   keys=ModBindings.Read(manager.Read().Items.Single(x=>x.Id==item.Id),manager);manager.SetKey(item.Id,keys[2],"no_modifiers F9");manager.Apply(runtime);output=File.ReadAllText(Path.Combine(runtime,"GIMI","Mods","Catheryne",item.Id,"effect.ini"));Check(output.Contains("back = no_modifiers F9")&&output.Contains(captured),"Independent bindings overwrite one another");manager.SetKey(item.Id,keys[0],null);Check(manager.Read().Items.Single(x=>x.Id==item.Id).Keys.Count==1,"Reset cleared other overrides");manager.SetKey(item.Id,keys[2],null);Check(ModManager.Signature(manager.Read())==signature,"Reset failed to restore the original signature");
   bool blocked=false;try{new ModManager(root,()=>true).SetKey(item.Id,keys[0],captured);}catch(InvalidOperationException){blocked=true;}Check(blocked&&manager.Read().Items.Single(x=>x.Id==item.Id).Keys.Count==0,"In-game binding edit changed stored state");
   string projected=Path.Combine(runtime,"GIMI","Mods","Catheryne",item.Id,"effect.ini");manager.SetKey(item.Id,keys[0],captured);manager.SetKey(item.Id,keys[2],"no_modifiers F9");manager.Apply(runtime);string together=File.ReadAllText(projected);Check(together.Contains(captured)&&together.Contains("back = no_modifiers F9")&&together.Contains("; preserve comment"),"Batched bindings dropped an override or author comment");
   DateTime cached=File.GetLastWriteTimeUtc(projected);manager.Apply(runtime);Check(File.GetLastWriteTimeUtc(projected)==cached&&File.ReadAllText(projected)==together,"Unchanged key overrides invalidated XXMI's INI cache");manager.SetKey(item.Id,keys[0],null);manager.SetKey(item.Id,keys[2],null);manager.Apply(runtime);
   string payload=Path.Combine(manager.Payload(item),"effect.ini");cached=File.GetLastWriteTimeUtc(projected);File.WriteAllText(payload,original.Replace("condition = $active","condition = $update"));File.SetLastWriteTimeUtc(payload,cached);manager.Apply(runtime);Check(File.ReadAllText(projected).Contains("condition = $update")&&File.GetLastWriteTimeUtc(projected)!=cached,"Changed canonical INI with reused timestamp remained cached");File.WriteAllText(payload,original);manager.Apply(runtime);
   manager.SetKey(item.Id,keys[0],captured);string prior=File.ReadAllText(Path.Combine(runtime,"GIMI","Mods","Catheryne",item.Id,"effect.ini"));File.WriteAllText(Path.Combine(manager.Payload(item),"effect.ini"),original.Replace("no_modifiers F11","no_modifiers F10"));bool stale=false;try{manager.Apply(runtime);}catch(InvalidDataException){stale=true;}Check(stale&&File.ReadAllText(Path.Combine(runtime,"GIMI","Mods","Catheryne",item.Id,"effect.ini"))==prior,"Changed author binding silently applied stale override or destroyed previous projection");
  }finally{ModManager.DeleteInside(root,Path.GetTempPath());}
 }
 static void LaunchContracts(){
  const string success="root DEBUG App Start\nSuccessfully passed late d3d11.dll -> GenshinImpact.exe hook check!";const string failure="root DEBUG App Start\nFailed to verify d3d11.dll -> GenshinImpact.exe hook!";
  Check(ModLaunch.Result(success)=="verified"&&ModLaunch.Result(failure)=="failed"&&ModLaunch.Result(success+"\nroot DEBUG App Start\nApplicationEvents.StartGameExe")=="pending","Launch reader reused previous launch or conflated request with connection");
  DateTime since=DateTime.UtcNow;string game=Path.Combine(Path.GetTempPath(),"GenshinImpact.exe"),dll=Path.Combine(Path.GetTempPath(),"GIMI","d3d11.dll");Func<DateTime,string> proof=time=>"D3D11 DLL starting init - v 1.3.16 - "+time.ToLocalTime().ToString("ddd MMM d HH:mm:ss yyyy",System.Globalization.CultureInfo.InvariantCulture)+"\nGame path: "+game+"\n3DMigoto path: "+dll+"\n";string current=proof(since.AddSeconds(2));
  Check(ModLaunch.Initialized(current,game,dll,since)&&!ModLaunch.Initialized(proof(since.AddMinutes(-2)),game,dll,since),"DLL proof reused stale launch");
  Check(!ModLaunch.Initialized(current,game+".other",dll,since)&&!ModLaunch.Initialized(current,game,dll+".other",since)&&!ModLaunch.Initialized(current+"D3D11 DLL starting init - incomplete",game,dll,since),"DLL proof accepted a different target, loader, or incomplete session");
  using(var fake=System.Diagnostics.Process.GetCurrentProcess())ModLaunch.Wait(fake,()=>failure,null,100,()=>ModLaunch.Initialized(current,game,dll,since));
  string root=Path.Combine(Path.GetTempPath(),"mod-launch-proof-"+Guid.NewGuid().ToString("N"));Directory.CreateDirectory(root);try{var mapped=ModIntegration.Configure(root,new Dictionary<string,object>{{"GamePath",game}},false);var gim=CodexChat.Map(CodexChat.Map(mapped["Importers"])["GIMI"]);var importer=CodexChat.Map(gim["Importer"]);var logging=CodexChat.Map(CodexChat.Map(CodexChat.Map(importer["d3dx_ini"])["core"])["Logging"]);Check(Equals(logging["log_level"],"warning")&&Equals(logging["unbuffered"],1),"Quiet DLL evidence logging missing");logging["log_level"]="debug";logging["future"]="preserve";AtomicFile.Write(Path.Combine(root,"XXMI Launcher Config.json"),CatheryneTools.Json().Serialize(mapped));mapped=ModIntegration.Configure(root,new Dictionary<string,object>{{"GamePath",game}},false);logging=CodexChat.Map(CodexChat.Map(CodexChat.Map(CodexChat.Map(CodexChat.Map(CodexChat.Map(mapped["Importers"])["GIMI"])["Importer"])["d3dx_ini"])["core"])["Logging"]);Check(Equals(logging["log_level"],"debug")&&Equals(logging["future"],"preserve"),"Existing logging options discarded");string file=Path.Combine(root,"d3d11_log.txt");File.WriteAllText(file,current+new string('x',20000));Check(ModLaunch.DllLog(file).Length==8192&&ModLaunch.Initialized(ModLaunch.DllLog(file),game,dll,since),"DLL reader dropped the header or reads unbounded files");}finally{ModManager.DeleteInside(root,Path.GetTempPath());}
  using(var fake=System.Diagnostics.Process.GetCurrentProcess()){ModLaunch.Wait(fake,()=>success,null,100);bool rejected=false;try{ModLaunch.Wait(fake,()=>failure,null,100);}catch(InvalidOperationException){rejected=true;}Check(rejected,"Unverified hook accepted as mod success");bool timed=false;try{ModLaunch.Wait(fake,()=>"",null,1);}catch(TimeoutException){timed=true;}Check(timed,"Missing launch evidence was accepted");}
 }

 static void StartupPresentationContracts(){
  string root=Path.Combine(Path.GetTempPath(),"mod-startup-"+Guid.NewGuid().ToString("N")),runtime=Path.Combine(root,"runtime"),main=Path.Combine(runtime,"GIMI","Core","GIMI","main.ini"),user=Path.Combine(runtime,"GIMI","d3dx_user.ini");Directory.CreateDirectory(Path.GetDirectoryName(main));
  try{
   string source="namespace = GIMIv8\n[Constants]\nglobal persist $first_run = 1\nglobal $show_user_guide = 0\n[KeyGuide]\nkey = F12\n$show_user_guide = 0,1\n[ResourceVersionNotification]\ntype = Buffer\ndata = \"GIMI F12 TO SHOW GUIDE\"\n";
   string personal="[Constants]\n$\\GIMIv8\\first_run = 1\n$\\Personal\\variant = 3\n";File.WriteAllText(main,source);File.WriteAllText(user,personal);
   var manager=new ModManager(root,()=>false);manager.Apply(runtime);string startup=Path.Combine(runtime,"GIMI","Mods","Catheryne","Startup.ini"),text=File.ReadAllText(startup);
   Check(text.Contains(@"post $\GIMIv8\first_run = 0")&&!text.Contains("[Present]")&&!text.Contains("$show_user_guide"),"Startup guide default overrides manual toggles or runs every frame");
   string resource=@"Resource\GIMIv8\VersionNotification";
   Check(text.Contains("post "+resource+" = ref "+resource+"\npost "+resource+" = null\n"),"Startup banner must be materialized once before clearing its lazy resource");
   Check(File.ReadAllText(main)==source&&File.ReadAllText(user)==personal,"Startup default changed original Core or personal mod state");
   DateTime modified=File.GetLastWriteTimeUtc(startup);manager.Apply(runtime);Check(File.GetLastWriteTimeUtc(startup)==modified,"Unchanged startup configuration invalidated native optimization");
   File.WriteAllText(main,source.Replace("GIMIv8","GIMIv9"));manager.Apply(runtime);text=File.ReadAllText(startup);Check(text.Contains(@"post $\GIMIv9\first_run = 0")&&text.Contains(@"Resource\GIMIv9\VersionNotification")&&!text.Contains("GIMIv8"),"Startup presentation retained an old importer namespace");
   string withoutBanner=source.Substring(0,source.IndexOf("[ResourceVersionNotification]",StringComparison.Ordinal));File.WriteAllText(main,withoutBanner);manager.Apply(runtime);text=File.ReadAllText(startup);Check(text.Contains("first_run")&&!text.Contains("VersionNotification"),"Unsupported banner resource was referenced");
   File.WriteAllText(main,source.Replace("global persist $first_run = 1","; unsupported guide"));manager.Apply(runtime);text=File.ReadAllText(startup);Check(text.Contains("VersionNotification")&&!text.Contains("first_run"),"Independent banner configuration added an unknown guide variable");
   File.WriteAllText(main,withoutBanner.Replace("global persist $first_run = 1","; unsupported importer"));manager.Apply(runtime);Check(!File.Exists(startup)&&File.ReadAllText(user)==personal,"Unknown importer created unsupported startup commands");
  }finally{ModManager.DeleteInside(root,Path.GetTempPath());}
 }
 static void RuntimeContracts(){
  string root=Path.Combine(Path.GetTempPath(),"catheryne-runtime-contract-"+Guid.NewGuid().ToString("N"));Directory.CreateDirectory(root);
  try{
   string commands=Path.Combine(root,"commands.xcmd"),core=Path.Combine(root,"Core","Old");Directory.CreateDirectory(core);File.WriteAllText(Path.Combine(core,"old.ini"),"fixture");File.WriteAllText(commands,"[PreInstall]\ndelete = Core/Old\n[PostInstall]\n");ModRuntimePackages.Commands(commands,"PreInstall",root);Check(!Directory.Exists(core),"Upstream cleanup command ignored");
   foreach(string path in new[]{"Mods/Personal","Core","Core/../Mods/Personal","C:/Outside"}){File.WriteAllText(commands,"[PreInstall]\ndelete = "+path);bool blocked=false;try{ModRuntimePackages.Commands(commands,"PreInstall",root);}catch(System.IO.InvalidDataException){blocked=true;}Check(blocked,"Unsafe package command accepted");}
   var package=new Dictionary<string,object>{{"deployed_version","8.9.1"},{"latest_version","9.0.0"}};
   var catalog=new Dictionary<string,object>{{"GIMI",package}};var packages=new Dictionary<string,object>{{"packages",catalog}};
   var config=new Dictionary<string,object>{{"Launcher",new Dictionary<string,object>{{"future",123}}},{"Packages",packages}};ModRuntimePackages.ConfigureQuickLaunch(config);
   Check(Equals(CodexChat.Map(config["Launcher"])["auto_update"],false)&&Convert.ToInt32(CodexChat.Map(config["Launcher"])["future"])==123,"Headless launch changed unrelated settings");Check(CodexChat.S(CodexChat.Map(CodexChat.Map(CodexChat.Map(config["Packages"])["packages"])["GIMI"]),"latest_version")=="8.9.1","Upstream update dialog not suppressed");
   byte[] data=System.Text.Encoding.UTF8.GetBytes("signed original package");
   using(var key=System.Security.Cryptography.CngKey.Create(System.Security.Cryptography.CngAlgorithm.ECDsaP384))using(var ec=new System.Security.Cryptography.ECDsaCng(key)){
    ec.HashAlgorithm=System.Security.Cryptography.CngAlgorithm.Sha256;byte[] point=key.Export(System.Security.Cryptography.CngKeyBlobFormat.EccPublicBlob),header=Convert.FromBase64String("MHYwEAYHKoZIzj0CAQYFK4EEACIDYgAEYac352uRGKZh6LOwK0fVDW/TpyECEfnRtUp+bP2PJPP63SWOkJ3a/d9pAnPfYezRVJ1hWjZtpRTT8HEAN/b4mWpJvqO43SAEV/1Q6vz9Rk/VvRV3jZ6B/tmqVnIeHKEb").Take(24).ToArray();byte[] derKey=new byte[120];Array.Copy(header,derKey,header.Length);derKey[23]=4;Array.Copy(point,8,derKey,24,96);byte[] signed=ec.SignData(data);var integers=new List<byte>();for(int part=0;part<2;part++){byte[] integer=signed.Skip(part*48).Take(48).SkipWhile(x=>x==0).ToArray();if(integer.Length==0)integer=new byte[]{0};if(integer[0]>=128)integer=new byte[]{0}.Concat(integer).ToArray();integers.Add(2);integers.Add((byte)integer.Length);integers.AddRange(integer);}byte[] signature=new byte[]{0x30,(byte)integers.Count}.Concat(integers).ToArray();string encoded=Convert.ToBase64String(signature),publicKey=Convert.ToBase64String(derKey);Check(ModRuntimePackages.Verify(publicKey,encoded,data),"Author signature rejected");data[0]^=1;Check(!ModRuntimePackages.Verify(publicKey,encoded,data)&&!ModRuntimePackages.Verify(publicKey,"broken",data),"Modified package accepted");
   }
   bool guarded=false;try{ModRuntimePackages.Prepare(root,busy:()=>true);}catch(InvalidOperationException){guarded=true;}Check(guarded&&!Directory.Exists(Path.Combine(root,"Resources")),"Busy preparation touched runtime files");
  }finally{Directory.Delete(root,true);}
 }

}
