using System;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Media;
using System.Windows.Threading;
using System.Windows.Input;

internal static class ModPanel {
 static readonly Brush Imported=new SolidColorBrush(Color.FromRgb(64,90,139)),Builtin=new SolidColorBrush(Color.FromRgb(47,105,86));
 static Border Pill(string text,Brush color){return new Border{Child=new TextBlock{Text=Locale.T(text),Foreground=Brushes.White,FontSize=11},Background=color,CornerRadius=new CornerRadius(11),Padding=new Thickness(8,3,8,3),HorizontalAlignment=HorizontalAlignment.Left};}
 internal static Border Card(ManagedMod item,ModManager manager,FrameworkElement actions,PanelWorkIndicator activity,string name,string help,Dictionary<string,object> owner=null){
  var spec=item.Builtin==null?null:ModBuiltins.Catalog.Single(x=>x.Key==item.Builtin);var art=new ModArtwork.CardImage(spec){Opacity=spec==null?.72:.92};var portrait=new Image{Stretch=Stretch.UniformToFill,Opacity=0.72};
  if(item.Builtin==null&&ModManager.Kind(item)=="character"){
   if(owner!=null)AccountIdentity.Portrait(portrait,owner,512);
  }
  ModArtwork.Present(art,item,manager,decodeEdge:spec==null?768:Math.Min(2048,Math.Max(768,(int)Math.Ceiling(720/spec.PreviewRegion.Width))));var grid=new Grid{ClipToBounds=true};grid.Children.Add(portrait);grid.Children.Add(art);grid.Children.Add(new Border{Background=new LinearGradientBrush(new GradientStopCollection{new GradientStop(Color.FromArgb(238,24,28,34),0),new GradientStop(Color.FromArgb((byte)(spec==null?175:125),24,28,34),0.62),new GradientStop(Color.FromArgb((byte)(spec==null?100:64),24,28,34),1)},0)});
  var content=new Grid{Margin=new Thickness(16)};content.ColumnDefinitions.Add(new ColumnDefinition());content.ColumnDefinitions.Add(new ColumnDefinition{Width=GridLength.Auto});
  var title=new TextBlock{Text=name,Foreground=Brushes.White,FontSize=16,FontWeight=FontWeights.SemiBold,TextWrapping=TextWrapping.Wrap,TextTrimming=TextTrimming.CharacterEllipsis,MaxHeight=44,ToolTip=name,Margin=new Thickness(0,0,12,0),VerticalAlignment=VerticalAlignment.Center};var heading=PanelUi.Heading(title,help==null?null:PanelUi.Help(help),wrap:true);heading.VerticalAlignment=VerticalAlignment.Center;content.Children.Add(heading);
  var badge=Pill(item.Builtin==null?"가져옴":"기본 제공",item.Builtin==null?Imported:Builtin);badge.VerticalAlignment=VerticalAlignment.Center;badge.RenderTransform=new TranslateTransform();Action alignBadge=()=>((TranslateTransform)badge.RenderTransform).Y=-(title.ActualHeight+badge.ActualHeight)/2-8;title.SizeChanged+=(s,e)=>alignBadge();badge.SizeChanged+=(s,e)=>alignBadge();content.Children.Add(badge);
  Grid.SetColumn(actions,1);actions.VerticalAlignment=VerticalAlignment.Center;content.Children.Add(actions);grid.Children.Add(content);
  activity.View.VerticalAlignment=VerticalAlignment.Bottom;activity.View.Margin=new Thickness(16,0,16,10);grid.Children.Add(activity.View);
  var card=new Border{Child=grid,Height=144,CornerRadius=PanelUi.Corners,Background=new SolidColorBrush(Color.FromRgb(40,47,57)),Margin=new Thickness(0,0,0,12)};grid.SizeChanged+=(s,e)=>grid.Clip=new RectangleGeometry(new Rect(0,0,grid.ActualWidth,grid.ActualHeight),PanelUi.SurfaceRadius,PanelUi.SurfaceRadius);return card;
 }
 static string CharacterName(Dictionary<string,object>[] owned,string key){var row=owned.FirstOrDefault(x=>AccountIdentity.Key(x)==key);return row==null?GameCatalog.Name(key):AccountIdentity.Name(row);}
 static ComboBoxItem CharacterChoice(Dictionary<string,object> row,string tag){
  var content=new StackPanel{Orientation=Orientation.Horizontal};var image=new Image{Width=28,Height=28,Stretch=Stretch.Uniform,Margin=new Thickness(0,0,8,0)};GameCatalog.SidePortrait(image,row);content.Children.Add(image);content.Children.Add(new TextBlock{Text=AccountIdentity.Name(row),VerticalAlignment=VerticalAlignment.Center,TextTrimming=TextTrimming.CharacterEllipsis});return new ComboBoxItem{Content=content,Tag=tag};
 }
 internal static string NameOf(ManagedMod item){return ModBuiltins.NameOf(item);}
 internal static string EntryName(ManagedMod[] items){var group=ModBuiltins.GroupOf(items[0]);return group==null?NameOf(items[0]):Locale.T(group.Name);}
 internal static bool SearchEntry(ManagedMod[] items,string query){return (EntryName(items)+" "+string.Join(" ",items.Select(NameOf))).IndexOf(query,StringComparison.CurrentCultureIgnoreCase)>=0;}
 internal static FrameworkElement GroupOptions(ManagedMod[] items,Func<ManagedMod,PanelWorkIndicator,CheckBox> create,Action refresh){
  var body=new StackPanel();var activity=new PanelWorkIndicator(true);
  foreach(var item in items){var spec=ModBuiltins.Catalog.Single(x=>x.Key==item.Builtin);body.Children.Add(PanelUi.Row(Locale.T(spec.Name),create(item,activity),Locale.T(spec.Description)));}
  activity.View.Margin=new Thickness(0);body.Children.Add(activity.View);
  var timer=new DispatcherTimer{Interval=TimeSpan.FromSeconds(1)};timer.Tick+=(s,e)=>refresh();body.IsVisibleChanged+=(s,e)=>{if(body.IsVisible){refresh();timer.Start();}else timer.Stop();};body.Unloaded+=(s,e)=>timer.Stop();refresh();return body;
 }
 internal static FrameworkElement DetailContent(ManagedMod item,ModManager manager,Dictionary<string,object>[] owned,FrameworkElement options=null,Func<bool> editable=null,Action changed=null){
  var spec=item.Builtin==null?null:ModBuiltins.Catalog.Single(x=>x.Key==item.Builtin);var group=ModBuiltins.GroupOf(item);var body=new StackPanel();body.Children.Add(Pill(spec==null?"가져옴":"기본 제공",spec==null?Imported:Builtin));
  var image=new Image{Stretch=spec!=null&&(spec.Preview??"").StartsWith("solid:",StringComparison.Ordinal)?Stretch.Fill:Stretch.Uniform};var hero=new Border{Child=image,Height=220,Background=new SolidColorBrush(Color.FromRgb(20,24,29)),CornerRadius=PanelUi.Corners,ClipToBounds=true,Margin=new Thickness(0,12,0,12)};hero.SizeChanged+=(o,e)=>hero.Clip=new RectangleGeometry(new Rect(0,0,hero.ActualWidth,hero.ActualHeight),PanelUi.SurfaceRadius,PanelUi.SurfaceRadius);body.Children.Add(hero);
  bool hasPortrait=false;if(spec==null&&ModManager.Kind(item)=="character"){var owner=owned.FirstOrDefault(x=>AccountIdentity.Key(x)==item.Target.Substring(10));if(owner!=null){hasPortrait=true;AccountIdentity.Portrait(image,owner,768);}}
  string preview=spec==null?null:spec.Photos.FirstOrDefault(x=>(spec.Preview??"").EndsWith(System.IO.Path.GetFileName(x),StringComparison.OrdinalIgnoreCase))??spec.Preview;var photos=spec==null?new string[0]:new[]{preview}.Concat(spec.Photos).Where(x=>!string.IsNullOrEmpty(x)).Distinct().ToArray();int selected=0;if(photos.Length==0&&!hasPortrait&&ModArtwork.Local(item,manager)==null)hero.Visibility=Visibility.Collapsed;
  var previous=PanelUi.Button("‹");var next=PanelUi.Button("›");var count=PanelUi.Text("",true);count.Margin=new Thickness(0);count.HorizontalAlignment=HorizontalAlignment.Center;count.VerticalAlignment=VerticalAlignment.Center;
  foreach(var button in new[]{previous,next}){button.MinWidth=0;button.Width=36;button.Margin=new Thickness(0);button.Height=36;}System.Windows.Automation.AutomationProperties.SetName(previous,Locale.T("이전 사진"));System.Windows.Automation.AutomationProperties.SetName(next,Locale.T("다음 사진"));
  Action showPhoto=()=>{if(photos.Length>0){image.Source=null;ModArtwork.Present(image,item,manager,photos[selected]);}else ModArtwork.Present(image,item,manager);count.Text=(selected+1)+" / "+photos.Length;previous.IsEnabled=selected>0;next.IsEnabled=selected+1<photos.Length;};previous.Click+=(o,e)=>{if(selected>0){selected--;showPhoto();}};next.Click+=(o,e)=>{if(selected+1<photos.Length){selected++;showPhoto();}};
  if(photos.Length>1){var navigation=new Grid{Margin=new Thickness(0,0,0,16)};previous.HorizontalAlignment=HorizontalAlignment.Left;next.HorizontalAlignment=HorizontalAlignment.Right;navigation.Children.Add(previous);navigation.Children.Add(count);navigation.Children.Add(next);body.Children.Add(navigation);}showPhoto();if(options!=null)body.Children.Add(options);
  var info=new StackPanel();if(spec!=null){info.Children.Add(PanelUi.Text(Locale.T(group==null?spec.Description:group.Description)));var metadata=PanelUi.LinkRow(Locale.T("원본 페이지"),Locale.T("이동"),spec.Source,error=>info.Children.Add(PanelUi.Text(error.Message,true)));metadata.Inlines.InsertBefore(metadata.Inlines.FirstInline,new System.Windows.Documents.Run(Locale.T("제작자")+": "+spec.Author+"\n"+Locale.T("버전")+": "+Locale.T(spec.Version)+"\n"));info.Children.Add(metadata);}else if(ModManager.Kind(item)=="character")info.Children.Add(PanelUi.Text(CharacterName(owned,item.Target.Substring(10)),true));body.Children.Add(info);body.Children.Add(BindingOptions(item,manager,editable??(()=>!ProcessGuard.Busy()),changed??(()=>{})));
  var management=new StackPanel();if(spec!=null){management.Children.Add(PanelUi.Text(Locale.T(group==null?spec.Help:group.Help),true));var credits=spec.Packages.Select(x=>x.Credit).Distinct().ToArray();if(credits.Length>0)management.Children.Add(PanelUi.Text(string.Join("\n",credits),true));foreach(var package in spec.Packages.GroupBy(x=>x.Source).Select(x=>x.First()).Where(x=>x.Source!=spec.Source))management.Children.Add(PanelUi.LinkRow(Locale.T("구성요소 출처"),package.Folder,package.Source,error=>management.Children.Add(PanelUi.Text(error.Message,true))));}
  string folder=ModManager.Source(item,manager);var related=group==null?new[]{item}:manager.Read().Items.Where(x=>ModBuiltins.GroupOf(x)==group).ToArray();
  string runtime=ModIntegration.RuntimeRoot(manager.Root,false);
  foreach(var member in related){string memberFolder=ModManager.Source(member,manager);if(group!=null){management.Children.Add(PanelUi.Text(NameOf(member),true));management.Children.Add(PanelUi.Text(Locale.T(ModBuiltins.Catalog.Single(x=>x.Key==member.Builtin).Help),true));}management.Children.Add(PanelUi.Text(Locale.T("모드 파일")+"\n"+memberFolder,true));var open=PanelUi.Button(Locale.T("모드 폴더 열기"));open.IsEnabled=System.IO.Directory.Exists(memberFolder);open.Click+=(o,e)=>OpenDetailTarget(memberFolder,management);management.Children.Add(open);
   if(runtime!=null&&member.ExternalFolder==null){string projection=System.IO.Path.Combine(ModIntegration.ModsFolder(runtime),"Catheryne",member.Id);management.Children.Add(PanelUi.Text(Locale.T("게임 적용 폴더")+"\n"+projection,true));var applied=PanelUi.Button(Locale.T("게임 적용 폴더 열기"));applied.IsEnabled=System.IO.Directory.Exists(projection);applied.Click+=(o,e)=>OpenDetailTarget(projection,management);management.Children.Add(applied);}
  }
  if(runtime!=null){string log=System.IO.Path.Combine(runtime,"XXMI Launcher Log.txt");var logButton=PanelUi.Button(Locale.T("실행 로그 열기"));logButton.IsEnabled=System.IO.File.Exists(log);logButton.Click+=(o,e)=>OpenDetailTarget(log,management);management.Children.Add(logButton);}
  if(spec==null&&System.IO.Directory.Exists(folder)){try{var readme=ModManager.SafeFiles(folder).Take(20000).Where(x=>System.IO.Path.GetFileNameWithoutExtension(x).Equals("README",StringComparison.OrdinalIgnoreCase)&&new[]{".txt",".md",""}.Contains(System.IO.Path.GetExtension(x).ToLowerInvariant())&&new System.IO.FileInfo(x).Length<=65536).OrderBy(x=>x.Length).FirstOrDefault();if(readme!=null)body.Children.Add(PanelUi.Details(Locale.T("원본 안내"),PanelUi.Text(System.IO.File.ReadAllText(readme),true)));}catch(Exception error){body.Children.Add(PanelUi.Text(error.Message,true));}}
  body.Children.Add(PanelUi.Details(Locale.T("관리"),management));return body;
 }
 internal static FrameworkElement BindingOptions(ManagedMod item,ModManager manager,Func<bool> editable,Action changed){
  var body=new StackPanel();var bindings=ModBindings.Read(item,manager);if(bindings.Length==0){var spec=item.Builtin==null?null:ModBuiltins.Catalog.Single(x=>x.Key==item.Builtin);if(spec!=null&&!string.IsNullOrEmpty(spec.Controls))body.Children.Add(PanelUi.Details(Locale.T("단축키"),PanelUi.Text(Locale.T(spec.Controls),true)));return body;}
  var controls=new List<Button>();var notice=PanelUi.Text("",true);notice.Margin=new Thickness(0,0,0,12);Action check=null;
  check=()=>{var current=manager.Read();var active=ModBindings.Active(current,manager);var conflicts=bindings.SelectMany(key=>ModBindings.Conflicts(key,active)).Distinct().ToArray();notice.Text=conflicts.Length==0?"":Locale.Format("단축키가 겹칠 수 있습니다: {0}",string.Join(", ",conflicts));notice.Visibility=conflicts.Length==0?Visibility.Collapsed:Visibility.Visible;};body.Children.Add(notice);
  foreach(var key in bindings){
   var change=PanelUi.Button(ModBindings.Display(key.Value));change.Margin=new Thickness(0);change.MinWidth=100;change.ToolTip=Locale.T("클릭한 뒤 새 단축키를 누르세요. Esc는 취소합니다.");controls.Add(change);
   var reset=PanelUi.Button("↺");reset.MinWidth=0;reset.Width=32;reset.Padding=new Thickness(0);reset.Margin=new Thickness(8,0,0,0);reset.ToolTip=Locale.T("원본 단축키로 복원");System.Windows.Automation.AutomationProperties.SetName(reset,Locale.T("원본 단축키로 복원"));controls.Add(reset);
   bool listening=false;Action restore=()=>{listening=false;change.Content=ModBindings.Display(key.Value);};
   Action<string> save=value=>{try{ModManager.EnsureEditable();manager.SetKey(item.Id,key,value);key.Value=value??key.Original;restore();check();changed();}catch(Exception error){restore();notice.Text=error.Message;notice.Visibility=Visibility.Visible;}};
   change.Click+=(s,e)=>{if(!editable())return;listening=!listening;change.Content=listening?Locale.T("단축키 입력…"):ModBindings.Display(key.Value);change.Focus();};change.LostKeyboardFocus+=(s,e)=>restore();
   change.PreviewKeyDown+=(s,e)=>{if(!listening)return;e.Handled=true;Key pressed=e.Key==Key.System?e.SystemKey:e.Key;if(pressed==Key.Escape){restore();return;}if(!editable()){restore();return;}string value=ModBindings.Capture(pressed,Keyboard.Modifiers);if(value!=null)save(value);};reset.Click+=(s,e)=>{if(editable())save(null);};
   if(!ModBindings.CanEdit(key)){change.IsEnabled=false;reset.Visibility=Visibility.Collapsed;change.ToolTip=key.Editable?Locale.T("이 단축키 문법은 원본 안내에서 확인해 주세요."):Locale.T("원본 실행기의 단축키는 해당 실행기에서 변경해 주세요.");}
   var actions=new StackPanel{Orientation=Orientation.Horizontal};actions.Children.Add(change);actions.Children.Add(reset);body.Children.Add(PanelUi.Row(key.Section.Substring(Math.Min(3,key.Section.Length))+(key.Option=="back"?" · "+Locale.T("역방향"):""),actions));
  }
  Action availability=()=>{bool available=editable();for(int i=0;i<bindings.Length;i++){controls[i*2].IsEnabled=available&&ModBindings.CanEdit(bindings[i]);controls[i*2+1].IsEnabled=available&&ModBindings.CanEdit(bindings[i])&&bindings[i].Value!=bindings[i].Original;}};
  var timer=new DispatcherTimer{Interval=TimeSpan.FromSeconds(1)};timer.Tick+=(s,e)=>availability();body.IsVisibleChanged+=(s,e)=>{if(body.IsVisible){availability();timer.Start();}else timer.Stop();};body.Unloaded+=(s,e)=>timer.Stop();check();availability();return PanelUi.SectionHelp(Locale.T("단축키"),Locale.T("원본 INI의 키를 조회합니다. 변경은 다음 게임 실행부터 적용되고 원본 파일은 유지합니다. 모드의 캐릭터·장면 조건은 해석하지 않으므로 겹침은 가능성으로 표시합니다. 실행 환경과 외부 연결 모드는 조회만 지원합니다."),body);
 }

 static void OpenDetailTarget(string target,Panel errors){try{System.Diagnostics.Process.Start(new System.Diagnostics.ProcessStartInfo(target){UseShellExecute=true});}catch(Exception error){errors.Children.Add(PanelUi.Text(error.Message,true));}}
 internal static void ShowDetails(Window window,DetailPanel detail,ManagedMod item,ModManager manager,Dictionary<string,object>[] owned,Action back,FrameworkElement options=null,Func<bool> editable=null,Action changed=null){var group=ModBuiltins.GroupOf(item);string name=group==null?NameOf(item):Locale.T(group.Name);detail.Show("mods/detail/"+(group==null?item.Id:group.Key),name,DetailContent(item,manager,owned,options,editable,changed),back:back,owner:"mods");}
 internal static void Show(Window window,DetailPanel detail){
  var manager=new ModManager(Setup.DataFolder);var owned=manager.Characters();var body=new StackPanel();body.SetValue(System.Windows.Documents.TextElement.ForegroundProperty,Brushes.White);
  ModRuntimeOptions runtimeOptions=null;var status=PanelUi.Text("",true);status.TextWrapping=TextWrapping.NoWrap;status.TextTrimming=TextTrimming.CharacterEllipsis;status.Margin=new Thickness(0);var list=PanelUi.CardList();bool working=false,hasEnabled=false;var switches=new List<Tuple<CheckBox,bool>>();var summaries=new List<Action<ModState>>();var metadata=new List<Control>();var operation=new PanelWorkIndicator(true);
  var add=PanelUi.Button(Locale.T("압축 파일 선택"));var folder=PanelUi.Button(Locale.T("폴더 선택"));var off=PanelUi.Button(Locale.T("전체 끄기"));var prepare=PanelUi.Button(Locale.T("실행 환경 준비"));var connect=PanelUi.Button(Locale.T("기존 실행기 연결"));var open=PanelUi.Button(Locale.T("실행기 열기"));
  var search=new TextBox{Margin=new Thickness(0,0,0,12)};var category=new ComboBox{MinHeight=40,Margin=new Thickness(0,0,8,0)};category.SetResourceReference(FrameworkElement.StyleProperty,"OptionsCombo");foreach(string name in new[]{"전체","게임","캐릭터"})category.Items.Add(Locale.T(name));category.SelectedIndex=0;
  var character=new ComboBox{MinHeight=40,Margin=new Thickness(0,0,0,12)};character.SetResourceReference(FrameworkElement.StyleProperty,"OptionsCombo");character.Items.Add(new ComboBoxItem{Content=Locale.T("캐릭터 선택"),Tag=""});foreach(var row in owned)character.Items.Add(CharacterChoice(row,AccountIdentity.Key(row)));character.SelectedIndex=0;
  var emptyOwned=PanelUi.Text(Locale.T("보유 캐릭터 정보가 없습니다."),true);var collect=PanelUi.Button(Locale.T("계정 정보 최신화"));collect.Click+=(s,e)=>PanelNavigation.Open(window,"Collection");var empty=new StackPanel();empty.Children.Add(emptyOwned);empty.Children.Add(collect);
  var layout=new Grid();FrameworkElement runtimeView=null;Action showList=()=>detail.Show("mods",Locale.T("모드"),layout,scrollBody:false);Action render=null,monitor=null;Action<string> error=text=>{status.Text=Locale.T(text);status.ToolTip=new TextBlock{Text=status.Text,TextWrapping=TextWrapping.Wrap,MaxWidth=320};};
  Func<string> context=()=>category.SelectedIndex==1?"common":category.SelectedIndex==2&&Convert.ToString(((ComboBoxItem)character.SelectedItem).Tag).Length>0?"character:"+Convert.ToString(((ComboBoxItem)character.SelectedItem).Tag):null;
  Action availability=()=>{bool busy=ProcessGuard.Busy(),editable=!busy&&!working;foreach(var button in new[]{add,folder})button.IsEnabled=editable;off.IsEnabled=editable&&hasEnabled;foreach(var entry in switches)entry.Item1.IsEnabled=editable&&entry.Item2;foreach(var control in metadata)control.IsEnabled=editable;category.IsEnabled=character.IsEnabled=search.IsEnabled=!working;layout.AllowDrop=editable;if(runtimeOptions!=null)runtimeOptions.Availability();if(busy)error("게임 종료 후 모드를 변경할 수 있습니다.");else if(status.Text==Locale.T("게임 종료 후 모드를 변경할 수 있습니다."))status.Text=manager.Pending?Locale.T("다음 게임 실행부터 적용됩니다."):"";};
  Action<ModProgress> report=update=>window.Dispatcher.Invoke(new Action(()=>operation.Update(update.Stage,update.Downloaded,update.Total)));
  Func<Func<Task>,Task> run=async work=>{if(working)return;working=true;availability();status.Text="";try{ModManager.EnsureEditable();await work();render();}catch(Exception e){error(e.Message);}finally{working=false;availability();operation.Finish();if(runtimeOptions!=null)runtimeOptions.Refresh();}};
  Action<string> import=async path=>{string target=context();await run(async()=>{operation.Begin("가져오는 중…");await Task.Run(()=>manager.Import(path,target));});};
  add.Click+=(s,e)=>{var picker=new Microsoft.Win32.OpenFileDialog{Filter="Mods|*.zip;*.7z;*.rar",Multiselect=false,Title=Locale.T("모드 가져오기")};if(picker.ShowDialog(window)==true)import(picker.FileName);};folder.Click+=(s,e)=>{using(var picker=new System.Windows.Forms.FolderBrowserDialog()){if(picker.ShowDialog()==System.Windows.Forms.DialogResult.OK)import(picker.SelectedPath);}};
  off.Click+=(s,e)=>{try{manager.DisableAll();foreach(var entry in switches)entry.Item1.IsChecked=false;hasEnabled=false;foreach(var summary in summaries)summary(manager.Read());status.Text=manager.Pending?Locale.T("다음 게임 실행부터 적용됩니다."):"";availability();}catch(Exception ex){error(ex.Message);}};
  prepare.Click+=async(s,e)=>await run(async()=>{operation.Begin("실행 환경 확인 중…");await Task.Run(()=>ModIntegration.EnsureRuntime(Setup.DataFolder,report));});connect.Click+=(s,e)=>{var picker=new Microsoft.Win32.OpenFileDialog{Filter="XXMI Launcher|XXMI Launcher.exe",Title="XXMI Launcher"};if(picker.ShowDialog(window)==true)try{ModIntegration.Connect(Setup.DataFolder,picker.FileName);render();runtimeOptions.Refresh();}catch(Exception ex){error(ex.Message);}};open.Click+=(s,e)=>{try{ModIntegration.OpenSetup(Setup.DataFolder);}catch(Exception ex){error(ex.Message);}};
  layout.DragOver+=(s,e)=>{e.Effects=!working&&!ProcessGuard.Busy()&&e.Data.GetDataPresent(DataFormats.FileDrop)?DragDropEffects.Copy:DragDropEffects.None;e.Handled=true;};layout.Drop+=(s,e)=>{if(working||ProcessGuard.Busy())return;var paths=e.Data.GetData(DataFormats.FileDrop) as string[];if(paths==null||paths.Length!=1){error("모드는 한 번에 하나씩 가져와 주세요.");return;}import(paths[0]);e.Handled=true;};
  var importActions=PanelUi.Actions(add,folder);importActions.Margin=new Thickness(0);body.Children.Add(PanelUi.SectionHelp(Locale.T("모드 가져오기"),Locale.T("압축 파일이나 폴더를 끌어와도 됩니다. 캐릭터를 선택한 상태에서는 그 캐릭터에 배정합니다. 대표 이미지를 자동으로 찾고, ⋯에서 직접 선택할 수도 있습니다. 가져온 모드는 꺼진 상태로 등록하며 자동 업데이트하지 않습니다."),importActions));
  var filters=new Grid{Margin=new Thickness(0,0,0,12)};filters.ColumnDefinitions.Add(new ColumnDefinition());filters.ColumnDefinitions.Add(new ColumnDefinition{Width=GridLength.Auto});filters.Children.Add(category);off.Margin=new Thickness(0);Grid.SetColumn(off,1);filters.Children.Add(off);body.Children.Add(filters);body.Children.Add(character);body.Children.Add(empty);body.Children.Add(PanelUi.SearchInput(search,Locale.T("모드 검색")));
  var slot=new Grid{Height=36,Margin=new Thickness(0,0,0,8)};slot.Children.Add(status);slot.Children.Add(operation.View);body.Children.Add(slot);
  var runtimeHelp=Locale.T("XXMI와 GIMI를 내부에서 준비합니다. 실행 구성요소는 하루에 한 번 제작자 서명을 확인해 업데이트합니다. 모드 적용과 최적화는 원본 XXMI 경로를 사용합니다. 게임 중에는 모드에 포함된 단축키로 전환할 수 있지만 모드 설치·파일 교체·런처 스위치는 게임 종료 후 변경합니다. 기존 실행기 연결과 실행기 열기는 고급 관리용입니다. 공식 서버의 모드 사용은 제재 위험이 있습니다.");
  runtimeOptions=new ModRuntimeOptions(window,Setup.DataFolder,run,report,()=>!working&&!ProcessGuard.Busy(),message=>operation.Begin(message),prepare,connect,open,error);
  var settings=PanelUi.Button(Locale.T("실행 환경 설정"));settings.Margin=new Thickness(0);settings.ToolTip=new TextBlock{Text=runtimeHelp,TextWrapping=TextWrapping.Wrap,MaxWidth=320};
  settings.Click+=(s,e)=>{var view=runtimeOptions.View;if(runtimeView==null){runtimeView=view;view.IsVisibleChanged+=(sender,args)=>monitor();view.Unloaded+=(sender,args)=>monitor();}detail.Show("mods/runtime",Locale.T("실행 환경"),view,closed:()=>{PanelUi.Detach(slot);body.Children.Add(slot);if(monitor!=null)monitor();},back:showList,owner:"mods",footer:slot);runtimeOptions.Refresh();monitor();};
  var runtime=PanelUi.Row(runtimeOptions.Summary,settings,responsive:true);runtime.Margin=new Thickness(0,12,0,0);
  layout.RowDefinitions.Add(new RowDefinition{Height=GridLength.Auto});layout.RowDefinitions.Add(new RowDefinition());layout.RowDefinitions.Add(new RowDefinition{Height=GridLength.Auto});layout.Children.Add(body);Grid.SetRow(list,1);layout.Children.Add(list);Grid.SetRow(runtime,2);layout.Children.Add(runtime);
  Action refreshSelection=()=>{var latest=manager.Read();hasEnabled=latest.Items.Any(x=>x.Enabled);foreach(var summary in summaries)summary(latest);status.Text=manager.Pending?Locale.T("다음 게임 실행부터 적용됩니다."):"";};
  Func<ManagedMod,PanelWorkIndicator,CheckBox> makeSwitch=(item,activity)=>{
   var spec=item.Builtin==null?null:ModBuiltins.Catalog.Single(x=>x.Key==item.Builtin);var toggle=PanelUi.Toggle(item.Enabled,NameOf(item),true);switches.Add(Tuple.Create(toggle,spec==null||spec.Available));toggle.ToolTip=Locale.T("다음 게임 실행부터 적용됩니다.");
   toggle.Click+=async(sender,args)=>{if(working)return;bool enabled=toggle.IsChecked==true,previous=item.Enabled;working=true;availability();activity.Begin(enabled?"실행 환경 확인 중…":"모드 설정 중…");Action<ModProgress> update=value=>window.Dispatcher.Invoke(new Action(()=>activity.Update(value.Stage,value.Downloaded,value.Total)));try{ModManager.EnsureEditable();await Task.Run(()=>ModIntegration.SetEnabled(Setup.DataFolder,item.Id,enabled,update));item.Enabled=enabled;refreshSelection();activity.Finish();}catch(Exception ex){toggle.IsChecked=previous;activity.Finish(ex.Message);}finally{working=false;availability();runtimeOptions.Refresh();}};return toggle;
  };
  render=()=>{
   list.Items.Clear();switches.Clear();summaries.Clear();metadata.Clear();var state=manager.Read();hasEnabled=state.Items.Any(x=>x.Enabled);status.Text=manager.Pending?Locale.T("다음 게임 실행부터 적용됩니다."):"";
   character.Visibility=category.SelectedIndex==2&&owned.Length>0?Visibility.Visible:Visibility.Collapsed;empty.Visibility=category.SelectedIndex==2&&owned.Length==0?Visibility.Visible:Visibility.Collapsed;string selected=Convert.ToString(((ComboBoxItem)character.SelectedItem).Tag);
   var shown=ModBuiltins.ListEntries(state.Items).Where(entry=>category.SelectedIndex==0||ModManager.Kind(entry[0])==(category.SelectedIndex==1?"common":"character")).Where(entry=>category.SelectedIndex!=2||selected.Length==0||entry[0].Target=="character:"+selected).Where(entry=>SearchEntry(entry,search.Text)||(ModManager.Kind(entry[0])=="character"&&CharacterName(owned,entry[0].Target.Substring(10)).IndexOf(search.Text,StringComparison.CurrentCultureIgnoreCase)>=0));
   foreach(var entry in shown){var item=entry[0];var group=ModBuiltins.GroupOf(item);
    var spec=item.Builtin==null?null:ModBuiltins.Catalog.Single(x=>x.Key==item.Builtin);string name=EntryName(entry);var actions=new StackPanel{Orientation=Orientation.Horizontal};var activity=new PanelWorkIndicator(true);
    if(group==null)actions.Children.Add(makeSwitch(item,activity));else{var summary=PanelUi.Text("",true);summary.Margin=new Thickness(0);summary.VerticalAlignment=VerticalAlignment.Center;Action<ModState> update=latest=>{int count=entry.Count(member=>latest.Items.Any(x=>x.Id==member.Id&&x.Enabled));summary.Text=Locale.Format("사용 중 {0}/{1}",count,entry.Length);summary.Foreground=count>0?new SolidColorBrush(Color.FromRgb(185,230,216)):new SolidColorBrush(Color.FromRgb(194,201,210));};summaries.Add(update);update(state);actions.Children.Add(summary);}
    if(spec==null){var more=PanelUi.Button("⋯");more.MinWidth=0;more.Width=30;more.VerticalAlignment=VerticalAlignment.Center;more.Padding=new Thickness(0);more.Margin=new Thickness(8,0,0,0);more.ToolTip=Locale.T("모드 관리");metadata.Add(more);more.Click+=(sender,args)=>{if(working||ProcessGuard.Busy())return;var menu=PanelUi.Menu();var image=new MenuItem{Header=Locale.T("대표 이미지 선택")};image.Click+=async(o,e)=>{var picker=new Microsoft.Win32.OpenFileDialog{Filter="Images|*.png;*.jpg;*.jpeg;*.bmp",Title=Locale.T("대표 이미지 선택")};if(picker.ShowDialog(window)==true)await run(async()=>await Task.Run(()=>manager.SetCover(item.Id,picker.FileName)));};menu.Items.Add(image);menu.Items.Add(new Separator());
      Action<string,string> choice=(title,target)=>{var option=new MenuItem{Header=title,IsCheckable=true,IsChecked=item.Target==target};option.Click+=(o,e)=>{try{manager.SetTarget(item.Id,target);render();}catch(Exception ex){error(ex.Message);}};menu.Items.Add(option);};choice(Locale.T("게임 전체"),"common");choice(Locale.T("미분류"),"unclassified");foreach(var row in owned){var option=new MenuItem{Header=((ComboBoxItem)CharacterChoice(row,"")).Content,IsCheckable=true,IsChecked=item.Target=="character:"+AccountIdentity.Key(row)};string target="character:"+AccountIdentity.Key(row);option.Click+=(o,e)=>{try{manager.SetTarget(item.Id,target);render();}catch(Exception ex){error(ex.Message);}};menu.Items.Add(option);}menu.PlacementTarget=more;menu.MaxHeight=360;menu.IsOpen=true;};actions.Children.Add(more);}
    var card=Card(item,manager,actions,activity,name,spec==null?null:Locale.T(group==null?spec.Help:group.Help),ModManager.Kind(item)=="character"?owned.FirstOrDefault(x=>AccountIdentity.Key(x)==item.Target.Substring(10)):null);PanelInteraction.OpenSurface(card,name,()=>{if(!working)try{FrameworkElement options=null;if(group!=null){var members=manager.Read().Items.Where(x=>ModBuiltins.GroupOf(x)==group).OrderBy(x=>ModBuiltins.Catalog.Single(b=>b.Key==x.Builtin).Order).ToArray();options=GroupOptions(members,makeSwitch,availability);var ownedOptions=options;options.Unloaded+=(o,e)=>switches.RemoveAll(x=>PanelInteraction.Within(x.Item1,ownedOptions));}ShowDetails(window,detail,item,manager,owned,()=>{refreshSelection();showList();},options,()=>!working&&!ProcessGuard.Busy(),refreshSelection);}catch(Exception ex){error(ex.Message);}});list.Items.Add(card);
   }
   if(list.Items.Count==0)list.Items.Add(PanelUi.Text(Locale.T("조건에 맞는 모드가 없습니다."),true));availability();
  };
  search.TextChanged+=(s,e)=>render();category.SelectionChanged+=(s,e)=>render();character.SelectionChanged+=(s,e)=>render();System.Windows.Automation.AutomationProperties.SetName(category,Locale.T("모드 분류"));System.Windows.Automation.AutomationProperties.SetName(character,Locale.T("보유 캐릭터"));
  var timer=new DispatcherTimer{Interval=TimeSpan.FromSeconds(1)};timer.Tick+=(s,e)=>availability();monitor=()=>{if(layout.IsVisible||(runtimeView!=null&&runtimeView.IsVisible))timer.Start();else timer.Stop();};layout.IsVisibleChanged+=(s,e)=>monitor();try{render();}catch(Exception ex){error(ex.Message);}showList();
 }
}
