using System;
using System.Linq;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Markup;
using System.IO;
internal static class PanelInteractionTests {
 static ScrollViewer FindScroll(DependencyObject root){var own=root as ScrollViewer;if(own!=null)return own;for(int i=0;i<System.Windows.Media.VisualTreeHelper.GetChildrenCount(root);i++){var found=FindScroll(System.Windows.Media.VisualTreeHelper.GetChild(root,i));if(found!=null)return found;}return null;}
 internal static void Run(){
  var window=(Window)XamlReader.Parse(File.ReadAllText(Path.Combine(AppDomain.CurrentDomain.BaseDirectory,"Main.xaml")));
  PanelUi.ApplyGeometry(window);if((CornerRadius)window.Resources["SurfaceCorners"]!=PanelUi.Corners)throw new Exception("Surface geometry has a second source");
  foreach(string name in new[]{"FPS","UseHDR","UsePowerSave","MonitorNum","AdditionalCommandLine","DllList","WindowMode","ResolutionMode","AiPreset","PersonalPreset","SavePersonalPreset"})if(window.FindName(name)==null)throw new Exception("Display control removed: "+name);
  var presets=new DisplayPresets(Path.Combine(Path.GetTempPath(),"display-binding-"+Guid.NewGuid().ToString("N")));var options=new UnlockerOptionsPanel(window,message=>{},()=>true,presets);var values=UnlockerOptions.Defaults();values["FPSTarget"]=144;values["UseHDR"]=true;values["UsePowerSave"]=true;values["MonitorNum"]=2;options.Load(values);options.SetEditable(false);foreach(string name in new[]{"UseHDR","UsePowerSave","MonitorNum","WindowMode"})if(((Control)window.FindName(name)).IsEnabled)throw new Exception("Game guard lost: "+name);options.SetEditable(true);var result=options.Read();if(Convert.ToInt32(result["FPSTarget"])!=144||!Equals(result["UseHDR"],true)||Convert.ToInt32(result["MonitorNum"])!=2)throw new Exception("Display regrouping changed stored values");
  var toggle=PanelUi.Toggle(false,"fixture");toggle.ApplyTemplate();if(toggle.Template.FindName("Knob",toggle)==null)throw new Exception("Toggle animation template invalid");toggle.IsChecked=true;toggle.IsChecked=false;var outlined=PanelUi.Toggle(false,"image switch",true);outlined.ApplyTemplate();var track=(Border)outlined.Template.FindName("Track",outlined);if(track.BorderThickness!=new Thickness(1)||track.BorderBrush==System.Windows.Media.Brushes.Transparent)throw new Exception("Image switch must retain a visible outline");
  // Cropping must cover every viewport, preserve aspect ratio and honor edge focal points.
  foreach(var sourceSize in new[]{new Size(1920,1080),new Size(800,1600),new Size(1,1)})foreach(double cardWidth in new[]{300.0,640.0})foreach(var focus in new[]{new Point(0,0),new Point(.5,.5),new Point(1,1)}){
   var bounds=ModArtwork.CoverBounds(sourceSize,new Size(cardWidth,144),focus);
   if(bounds.Left>0.001||bounds.Top>0.001||bounds.Right<cardWidth-.001||bounds.Bottom<143.999||Math.Abs(bounds.Width/bounds.Height-sourceSize.Width/sourceSize.Height)>.001)throw new Exception("Mod background leaves a gap or distorts the image");
  }
  var centerBounds=ModArtwork.CoverBounds(new Size(100,200),new Size(400,144),new Point(.5,.5));if(centerBounds!=new Rect(0,-328,400,800))throw new Exception("Imported cover no longer uses centered uniform fill");
  var edgeBounds=ModArtwork.CoverBounds(new Size(100,200),new Size(400,144),new Point(.5,0));if(edgeBounds.Top!=0)throw new Exception("Top focal point is cropped out");
  foreach(var builtin in ModBuiltins.Catalog)if(builtin.PreviewRegion.IsEmpty||!new Rect(0,0,1,1).Contains(builtin.PreviewRegion)||builtin.PreviewRegion.Width<=0||builtin.PreviewRegion.Height<=0||builtin.PreviewFocus.X<0||builtin.PreviewFocus.X>1||builtin.PreviewFocus.Y<0||builtin.PreviewFocus.Y>1)throw new Exception("Builtin artwork framing is outside its source");
  var activity=new PanelWorkIndicator(true);var card=ModPanel.Card(new ManagedMod{Id="12345678901234567890123456789012",Name="fixture"},new ModManager(Path.Combine(Path.GetTempPath(),"unused-mod-layout")),toggle,activity,"A long mod title that wraps within the card","Help follows the title");card.Resources=window.Resources;Action measure=()=>{card.Measure(new Size(320,double.PositiveInfinity));card.Arrange(new Rect(0,0,320,card.DesiredSize.Height));card.UpdateLayout();var content=((Grid)card.Child).Children.OfType<Grid>().Single();var title=content.Children.OfType<TextBlock>().Single();double titleCenter=title.TranslatePoint(new Point(0,title.ActualHeight/2),card).Y,toggleCenter=toggle.TranslatePoint(new Point(0,toggle.ActualHeight/2),card).Y;if(Math.Abs(titleCenter-card.Height/2)>0.1||Math.Abs(toggleCenter-titleCenter)>0.1)throw new Exception("Mod title and switch are not centered in the card");};measure();double idle=card.DesiredSize.Height;activity.Begin("Downloading...");activity.Update("Downloading...",10,100);measure();if(card.DesiredSize.Height!=idle)throw new Exception("Mod progress changes card extent");activity.Finish("A long visible failure that stays inside the fixed card");measure();if(card.DesiredSize.Height!=idle)throw new Exception("Mod error changes card extent");activity.Finish();measure();if(card.DesiredSize.Height!=idle)throw new Exception("Mod completion changes card extent");
  var surface=new Border();var surfaceBody=new StackPanel();surface.Child=surfaceBody;var surfaceTitle=new TextBlock{Text="Detail"};var surfaceSwitch=new CheckBox();var surfaceHelp=new Button();surfaceBody.Children.Add(surfaceTitle);surfaceBody.Children.Add(surfaceSwitch);surfaceBody.Children.Add(surfaceHelp);if(!PanelInteraction.SurfaceHit(surfaceTitle,surface)||PanelInteraction.SurfaceHit(surfaceSwitch,surface)||PanelInteraction.SurfaceHit(surfaceHelp,surface)||PanelInteraction.SurfaceHit(new Border(),surface))throw new Exception("Card detail activation must exclude nested switches and buttons");
  int openings=0;PanelInteraction.OpenSurface(surface,"Fixture",()=>openings++);foreach(var source in new System.Windows.DependencyObject[]{surfaceSwitch,surfaceHelp,surfaceTitle}){surface.RaiseEvent(new System.Windows.Input.MouseButtonEventArgs(System.Windows.Input.Mouse.PrimaryDevice,0,System.Windows.Input.MouseButton.Left){RoutedEvent=UIElement.PreviewMouseLeftButtonDownEvent,Source=source});surface.RaiseEvent(new System.Windows.Input.MouseButtonEventArgs(System.Windows.Input.Mouse.PrimaryDevice,0,System.Windows.Input.MouseButton.Left){RoutedEvent=UIElement.MouseLeftButtonUpEvent,Source=source});}if(openings!=1)throw new Exception("Only the card body should activate details");
  string detailRoot=Path.Combine(Path.GetTempPath(),"readonly-mod-detail-"+Guid.NewGuid().ToString("N"));var detailContent=ModPanel.DetailContent(new ManagedMod{Id="12345678901234567890123456789012",Name="Fixture"},new ModManager(detailRoot),new System.Collections.Generic.Dictionary<string,object>[0]);if(Directory.Exists(detailRoot))throw new Exception("Reading mod details must not create installation files");
  var groupItems=ModBuiltins.Catalog.Where(x=>x.Group!=null).Select(x=>new ManagedMod{Id=x.Id,Name=x.Name,Builtin=x.Key,Enabled=x.Key=="water-bubbles"}).ToArray();var groupSwitches=new System.Collections.Generic.Dictionary<string,CheckBox>();var changed=new System.Collections.Generic.List<string>();var groupOptions=ModPanel.GroupOptions(groupItems,(member,progress)=>{var control=PanelUi.Toggle(member.Enabled,ModPanel.NameOf(member));control.Click+=(o,e)=>changed.Add(member.Id);groupSwitches.Add(member.Id,control);return control;},()=>{});
  if(groupSwitches.Count!=3||groupSwitches.Count(x=>x.Value.IsChecked==true)!=1||groupSwitches[groupItems.Single(x=>x.Builtin=="water-bubbles").Id].IsChecked!=true)throw new Exception("Group details lost independent saved choices");foreach(var pair in groupSwitches)pair.Value.RaiseEvent(new RoutedEventArgs(System.Windows.Controls.Primitives.ButtonBase.ClickEvent,pair.Value));if(changed.Distinct().Count()!=3)throw new Exception("Group detail switches are bound to the wrong option");
  var groupedDetail=ModPanel.DetailContent(groupItems[0],new ModManager(detailRoot),new System.Collections.Generic.Dictionary<string,object>[0],groupOptions);if(Directory.Exists(detailRoot))throw new Exception("Reading grouped details must preserve the read-only path");
  var date=new DatePicker{Style=(Style)window.Resources[typeof(DatePicker)],SelectedDate=new DateTime(2026,10,1)};date.Resources=window.Resources;date.ApplyTemplate();var calendar=(Popup)date.Template.FindName("PART_Popup",date);if(!(calendar.Child is System.Windows.Controls.Calendar)||((Border)date.Template.FindName("Surface",date)).CornerRadius!=PanelUi.Corners)throw new Exception("Date picker lost its canonical surface or calendar");((System.Windows.Controls.Calendar)calendar.Child).SelectedDate=new DateTime(2026,10,2);if(date.SelectedDate!=new DateTime(2026,10,2))throw new Exception("Date selection binding changed");date.Text=new DateTime(2026,10,3).ToShortDateString();if(date.SelectedDate!=new DateTime(2026,10,3))throw new Exception("Typed date binding changed");
  var list=PanelUi.CardList();list.Resources=window.Resources;list.Items.Add(card);for(int i=0;i<5;i++)list.Items.Add(new Border{Height=144,Margin=new Thickness(0,0,0,12)});Action arrangeList=()=>{list.Measure(new Size(320,350));list.Arrange(new Rect(0,0,320,350));list.UpdateLayout();};arrangeList();var scroller=FindScroll(list);if(scroller==null)throw new Exception("Mod list has no scroll host");scroller.ScrollToVerticalOffset(37.5);arrangeList();if(Math.Abs(scroller.VerticalOffset-37.5)>0.1)throw new Exception("Card scrollbar must move continuously inside an item");double offset=scroller.VerticalOffset,extent=scroller.ExtentHeight,width=scroller.ViewportWidth;foreach(Action state in new Action[]{()=>activity.Begin("Preparing..."),()=>activity.Finish("An error that should not shift the list"),()=>activity.Finish()}){state();arrangeList();if(scroller.VerticalOffset!=offset||scroller.ExtentHeight!=extent||scroller.ViewportWidth!=width)throw new Exception("Mod work changes scroll extent, position or width");}
  var body=new StackPanel();window.Content=body;var combo=new ComboBox{Style=(Style)window.Resources["OptionsCombo"]};body.Children.Add(combo);combo.Items.Add("First");combo.ApplyTemplate();var popup=(Popup)combo.Template.FindName("PART_Popup",combo);
  if(!PanelInteraction.Within(popup.Child,window)||!PanelInteraction.Within(popup.Child,combo))throw new Exception("Dropdown content must belong to its control and window");
  var item=new ComboBoxItem{Content="Second"};combo.Items.Add(item);if(!PanelInteraction.Within(item,window))throw new Exception("Dropdown item must retain its panel ownership");
  if(PanelInteraction.Within(new Border(),window))throw new Exception("Outside click must remain outside");
 }
}
