using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;

internal static class TheaterPlanningTests {
 static Dictionary<string,object> D(string text){return CatheryneTools.Json().Deserialize<Dictionary<string,object>>(text);}
 static Dictionary<string,object> M(object value){return CodexChat.Map(value);}
 static Dictionary<string,object> Copy(Dictionary<string,object> value){return D(CatheryneTools.Json().Serialize(value));}
 static void Check(bool value,string message){if(!value)throw new Exception("Theater planning: "+message);}
 static void Reject(Action action,string message){try{action();}catch(ArgumentException){return;}catch(InvalidOperationException){return;}throw new Exception("Theater planning accepted: "+message);}
 internal static object[] Assessment(){return TheaterPlanning.CheckKinds.Select(kind=>(object)D(CatheryneTools.Json().Serialize(new{kind=kind,status="passed",evidence="Fictional test source covers this requirement; not a real performance claim."}))).ToArray();}
 internal static object[] Remaining(int first,int total,string identity=null){return Enumerable.Range(first,total-first+1).Select(act=>(object)D(CatheryneTools.Json().Serialize(new{id="act:"+act,act=act,title=act+"막",requirements="Game mechanic not yet observed",status=identity==null?"unverified":"supported",team=identity==null?new string[0]:new[]{identity},evidence=identity==null?"Enemy information missing":"Fictional matchup source",fallback="Recheck the visible fight before committing"}))).ToArray();}
 internal static void Run(string root){
  var state=D("{\"participantsConfirmed\":true,\"planChanges\":[],\"totalActs\":2,\"completedActs\":0,\"act\":1,\"partySize\":1,\"members\":{\"Fischl\":{\"available\":true,\"vigor\":2},\"Nahida\":{\"available\":false,\"vigor\":2}}}");
  var plan=D("{\"team\":[\"Fischl\"]}");plan["assessment"]=Assessment();plan["battlePlan"]=Remaining(1,2,"Fischl");TheaterPlanning.Validate(state,plan,true);
  var missing=Copy(state);missing.Remove("participantsConfirmed");Reject(()=>TheaterPlanning.Validate(missing,plan,true),"owned roster is not the confirmed registered pool");missing=Copy(state);missing.Remove("partySize");Reject(()=>TheaterPlanning.Validate(missing,plan,true),"party size cannot be guessed");
  var borrowed=D(CatheryneTools.Json().Serialize(new TheaterKnowledge(root).Character(D("{\"key\":\"Fischl\",\"level\":90,\"constellation\":2,\"hoyolab\":{\"skills\":[{\"name\":\"Fixture skill\",\"level\":9,\"desc\":\"<p>Conditional healing</p>\"}]}}"),"Fischl",null,0,"",D("{\"identity\":\"Fischl\",\"source\":\"support\",\"constellation\":6}"))));Check(Equals(borrowed["ownedBuildApplies"],false)&&Convert.ToInt32(M(borrowed["observedCast"])["constellation"])==6&&CodexChat.Items(borrowed["officialSkills"]).Count()==1,"borrowed constellation and gear never inherit the owned build while descriptions remain readable");
  var invalid=Copy(plan);invalid.Remove("assessment");Reject(()=>TheaterPlanning.Validate(state,invalid,true),"team without evidence checks");
  invalid=Copy(plan);M(CodexChat.Items(invalid["assessment"]).First())["status"]="failed";Reject(()=>TheaterPlanning.Validate(state,invalid,true),"known failed mechanics");
  invalid=Copy(plan);invalid["battlePlan"]=Remaining(1,1,"Fischl");Reject(()=>TheaterPlanning.Validate(state,invalid,true),"missing future act");
  invalid=Copy(plan);M(state["members"])["Fischl"]=D("{\"available\":true,\"vigor\":1}");Reject(()=>TheaterPlanning.Validate(state,invalid,true),"same character spent beyond known vigor");M(state["members"])["Fischl"]=D("{\"available\":true,\"vigor\":2}");
  invalid=Copy(plan);var second=CodexChat.Items(invalid["battlePlan"]).Last();second["team"]=new[]{"Nahida"};Reject(()=>TheaterPlanning.Validate(state,invalid,true),"unrecruited supported plan");second["status"]="recruitment";TheaterPlanning.Validate(state,invalid,true);
  state["requiredChallenges"]=new[]{"extra:1"};Reject(()=>TheaterPlanning.Validate(state,plan,true),"missing requested bonus");state["completedChallenges"]=new[]{"extra:1"};TheaterPlanning.Validate(state,plan,true);
  state["lastPlan"]=plan;state["planChanges"]=new[]{"members:Fischl"};var audit=M(CatheryneTools.Json().DeserializeObject(CatheryneTools.Json().Serialize(TheaterPlanning.Audit(state))));Check(((System.Collections.IEnumerable)audit["affectedBattles"]).Cast<object>().Count()==2&&Convert.ToInt32(audit["remainingRequiredSlots"])==2,"all affected future deployments and confirmed bonus clears are counted");
  state["planChanges"]=new[]{"recruited:Nahida"};audit=M(CatheryneTools.Json().DeserializeObject(CatheryneTools.Json().Serialize(TheaterPlanning.Audit(state))));Check(((System.Collections.IEnumerable)audit["affectedBattles"]).Cast<object>().Count()==2,"a new recruitment opens candidates for all remaining fights");
  invalid=Copy(plan);invalid["team"]=new[]{"Nahida"};invalid["battlePlan"]=Remaining(1,2,"Nahida");M(state["members"])["Nahida"]=D("{\"available\":true,\"vigor\":2}");Reject(()=>TheaterPlanning.Validate(state,invalid,true),"changed party without changed evidence");invalid["changeReason"]="Observed recruitment improves mechanic coverage";TheaterPlanning.Validate(state,invalid,true);
  var blocked=M(new TheaterService(root,()=>{throw new IOException("fixture refresh failure");}).Run("start",D("{\"goal\":\"test\"}"),"freshness-failure"));Check(Equals(blocked["started"],false)&&blocked["session"]==null&&M(CatheryneTools.Json().DeserializeObject(CatheryneTools.Json().Serialize(blocked["preparation"]))).ContainsKey("Id"),"failed refresh has visible preparation and no new run");
  int refreshes=0;var service=new TheaterService(root,()=>{refreshes++;return "Fixture account refreshed";});var created=M(M(service.Run("start",D("{\"goal\":\"test\"}"),"freshness-success"))["session"]);service.Run("start",D("{\"goal\":\"test\"}"),"freshness-success");Check(refreshes==1,"resuming an active run preserves pinned data");var policy=D(CatheryneTools.Json().Serialize(service.Run("knowledge",D("{\"topic\":\"principles\"}"),"freshness-success")));Check(Convert.ToInt32(policy["version"])==TheaterPlanning.Version,"principles are pinned to the new run");
  string run=Convert.ToString(created["id"]);int revision=0;
  Func<string,Dictionary<string,object>,object> observed=(eventId,delta)=>service.Run("observe",new Dictionary<string,object>{{"session_id",run},{"event_id",eventId},{"expected_revision",revision++},{"source","user"},{"evidence","Synthetic confirmed game state"},{"delta",delta}},"freshness-success");
  observed("initial",D("{\"participantsConfirmed\":true,\"phase\":\"party\",\"totalActs\":2,\"completedActs\":0,\"act\":1,\"partySize\":1,\"members\":[{\"identity\":\"Fischl\",\"available\":true,\"vigor\":2},{\"identity\":\"Nahida\",\"available\":false,\"vigor\":2}]}"));
  var first=D("{\"reason\":\"Fixture fight\",\"futurePlan\":\"Two fixtures\",\"alternatives\":\"Fixture fallback\",\"team\":[\"Fischl\"]}");first["session_id"]=run;first["event_id"]="first";first["expected_revision"]=revision++;first["assessment"]=Assessment();first["battlePlan"]=Remaining(1,2,"Fischl");service.Run("recommend",first,"freshness-success");
  observed("clear",D("{\"completedActs\":1,\"act\":2,\"members\":[{\"identity\":\"Fischl\",\"vigor\":1}]}"));
  var current=M(M(service.Status("freshness-success")["session"])["state"]);Check(TheaterPlanning.Remaining(current,M(current["lastPlan"])).Length==1,"finished fights are removed from reused plans before vigor arithmetic");
  var follow=Copy(first);follow["event_id"]="follow";follow["expected_revision"]=revision;follow.Remove("battlePlan");Reject(()=>service.Run("recommend",follow,"freshness-success"),"changed planning assumptions cannot silently reuse an unchecked plan");follow["battlePlan"]=Remaining(2,2,"Fischl");service.Run("recommend",follow,"freshness-success");revision++;
  observed("recruit",D("{\"members\":[{\"identity\":\"Nahida\",\"available\":true}]}"));current=M(M(service.Status("freshness-success")["session"])["state"]);Check(((System.Collections.IEnumerable)current["planChanges"]).Cast<object>().Select(Convert.ToString).Contains("recruited:Nahida"),"real incremental recruitment invalidates the global candidate set");
  state["challenge"]="Bonus fixture";invalid=Copy(plan);invalid["changeReason"]="Fixture";Reject(()=>TheaterPlanning.Validate(state,invalid,true),"bonus party cannot escape the future resource budget");state.Remove("challenge");
  string markup="<main><p>Updated Aug 17, 2026</p><astro-island component-url=\"/_astro/Teams.fixture.js\" props=\""+System.Net.WebUtility.HtmlEncode("{\"party\":[0,{\"1\":[1,[[0,{\"id\":[0,\"10000001,10000002,10000003,10000004\"],\"value\":[0,0.2]}]]]}]}")+"\"></astro-island></main>";
  var statistics=TheaterStatistics.Parse(markup);Check(Equals(statistics["eligibleForRanking"],false)&&statistics["sampleSize"]==null&&statistics["period"]==null&&M(statistics["teamsByRound"]).Count==1,"unknown statistical cohort is never a ranking prior");
  Reject(()=>TheaterStatistics.Parse(markup.Replace("0.2","1.2")),"invalid public usage rate");Reject(()=>TheaterStatistics.Parse(markup.Replace("10000004","10000001")),"duplicate public team member");
  string html="<main><script>ignore()</script><h1>Test</h1><p>Skill<br>Condition &amp; uptime</p></main>";Check(!TheaterCombatReference.CleanHtml(html).Contains("ignore")&&TheaterCombatReference.CleanHtml(html).Contains("Condition & uptime"),"reference scripts are never read as skills");
  var index=TheaterCombatReference.GuideIndex("<a href=\"https://keqingmains.com/q/vodyanitsa-quickguide/\">Guide</a>");Check(TheaterCombatReference.GuideUrl(index,D("{\"gameId\":10000140,\"names\":{\"en\":\"Vodyanitsa\"}}"))=="https://keqingmains.com/q/vodyanitsa-quickguide/","new official names use the current source index, independent of GOOD support");
 }
}
