using System;
using System.Collections.Generic;
using System.Linq;

// One discoverable schema for embedded chat and the MCP adapter.
internal static class TheaterToolContract {
 static object F(string type,string description="",params string[] values){var d=new Dictionary<string,object>{{"type",type}};if(description.Length>0)d["description"]=description;if(values.Length>0)d["enum"]=values;return d;}
 static object Obj(Dictionary<string,object> fields,params string[] required){return new{type="object",properties=fields,required=required,additionalProperties=false};}
 static object Rows(object item,int max){return new{type="array",items=item,maxItems=max};}
 static object Ids(){return Rows(F("string"),8);}
 internal static object Definition(){
  var member=Obj(new Dictionary<string,object>{{"identity",F("string")},{"name",F("string")},{"source",F("string","","owned","trial","support")},{"available",F("boolean")},{"vigor",new{type=new[]{"integer","null"},minimum=0,maximum=100}},{"level",new{type=new[]{"integer","null"},minimum=0,maximum=100}},{"constellation",new{type=new[]{"integer","null"},minimum=0,maximum=6}}},"identity");
  var effect=Obj(new Dictionary<string,object>{{"id",F("string")},{"name",F("string")},{"description",F("string")},{"level",new{type=new[]{"integer","null"},minimum=0,maximum=100}},{"removed",F("boolean")}},"id");
  var choice=Obj(new Dictionary<string,object>{{"id",F("string")},{"kind",F("string","","character","card","enemy","event")},{"text",F("string","Printed character name only; effects belong in description.")},{"description",F("string")},{"identity",F("string")},{"position",F("string")},{"cost",new{type=new[]{"integer","null"},minimum=0}},{"reward",new{type=new[]{"integer","null"},minimum=0}},{"level",new{type=new[]{"integer","null"},minimum=0,maximum=100}}},"id","kind","text");
  var delta=Obj(new Dictionary<string,object>{{"phase",F("string","","setup","choice","party","combat","result")},{"act",F("integer")},{"totalActs",F("integer")},{"completedActs",F("integer")},{"partySize",F("integer")},{"participantsConfirmed",F("boolean")},{"flowers",F("integer")},{"difficulty",F("string")},{"target",F("string")},{"challenge",F("string")},{"rules",F("string")},{"lastResult",F("string")},{"members",Rows(member,100)},{"cards",Rows(effect,100)},{"reactions",Rows(effect,100)},{"choices",Rows(choice,100)},{"party",Ids()},{"requiredChallenges",Rows(F("string"),20)},{"completedChallenges",Rows(F("string"),20)}});
  var check=Obj(new Dictionary<string,object>{{"kind",F("string","",TheaterPlanning.CheckKinds)},{"status",F("string","","passed","unknown","failed")},{"evidence",F("string","Concrete mechanic/skill/gear/source evidence; unknown is not passed.")}},"kind","status","evidence");
  var battle=Obj(new Dictionary<string,object>{{"id",F("string")},{"act",F("integer","Base act only; omit for bonus battles.")},{"title",F("string")},{"requirements",F("string")},{"team",Ids()},{"status",F("string","supported means source-backed, not guaranteed clear.","supported","recruitment","unverified","blocked")},{"evidence",F("string")},{"fallback",F("string")}},"id","title","requirements","status","evidence","fallback");
  var fields=new Dictionary<string,object>{{"view",F("string","Decision responses omit repeated reference prose and detailed future evidence; full returns everything.","decision","full")},{"battle_ids",Rows(F("string"),40)},{"battleChanges",Rows(battle,40)},{"reviewedBattles",Rows(F("string","Affected existing fight reviewed without changes."),40)},{"force",F("boolean")},{"goal",F("string")},{"use_saved_account",F("boolean","Only after the user explicitly requests continuing with existing account data after refresh failure.")},{"session_id",F("string")},{"expected_revision",F("integer")},{"event_id",F("string","Unique mutation ID, including recommend, finish and end.")},{"source",F("string","Required for observe/select/finish/end.","capture","user")},{"evidence",F("string")},{"capture_id",F("string","Required whenever source=capture.")},{"delta",delta},{"topic",F("string","","principles","rules","events","season","official","teams","reactions","amplifying","additive","gauge","damage","lunar","stellar","guides","statistics","character")},{"offset",F("integer")},{"query",F("string","Character topic requires the exact pinned account or participant identity; otherwise search text.")},{"section",F("string","","characters","weapons","artifacts")},{"path",F("string")},{"reason",F("string")},{"futurePlan",F("string")},{"alternatives",F("string")},{"choice_id",F("string")},{"team",Ids()},{"assessment",Rows(check,5)},{"battlePlan",Rows(battle,40)},{"changeReason",F("string","Changed evidence and downstream consequences when changing a prior party.")},{"rotation",Rows(Obj(new Dictionary<string,object>{{"identity",F("string")},{"action",F("string")}},"identity","action"),24)}};
  var required=new Dictionary<string,string[]>{{"start",new[]{"goal"}},{"resume",new[]{"session_id"}},{"plan",new[]{"session_id"}},{"roster",new[]{"session_id","section"}},{"capture",new[]{"session_id"}},{"knowledge",new[]{"topic"}},{"observe",new[]{"session_id","expected_revision","event_id","source","evidence","delta"}},{"recommend",new[]{"session_id","expected_revision","event_id","reason","futurePlan","alternatives"}},{"select",new[]{"session_id","expected_revision","event_id","source","evidence","choice_id"}},{"finish",new[]{"session_id","expected_revision","event_id","source","evidence"}},{"end",new[]{"session_id","expected_revision","event_id","source","evidence"}}};
  var conditions=required.Select(pair=>(object)new Dictionary<string,object>{{"if",new{properties=new{command=new{ @enum=new[]{pair.Key}}}}},{"then",new{properties=new{parameters=new{required=pair.Value}}}}}).ToList();
  conditions.Add(new Dictionary<string,object>{{"if",new{properties=new{parameters=new{properties=new{source=new{ @enum=new[]{"capture"}}},required=new[]{"source"}}}}},{"then",new{properties=new{parameters=new{required=new[]{"capture_id"}}}}}});
  conditions.Add(new Dictionary<string,object>{{"if",new{properties=new{command=new{ @enum=new[]{"recommend"}},parameters=new{required=new[]{"team"}}}}},{"then",new{properties=new{parameters=new{required=new[]{"assessment"}}}}}});
  return new{type="function",name="catheryne_theater",description=TheaterService.Guide,inputSchema=new{type="object",properties=new{command=F("string","",TheaterService.Commands),parameters=Obj(fields)},required=new[]{"command","parameters"},additionalProperties=false,allOf=conditions}};
 }
}
